package store

const (
	apiAuditEventsPath = "/api/v1/audit/events"
	apiSecretsPath = "/api/v1/secrets"
	apiUsersPath = "/api/v1/users"
	sqlIncrReadCount = "read_count + 1"
	sqlJoinGroups = "JOIN groups ON groups.id = group_roles.group_id AND groups.deleted_at IS NULL"
	sqlJoinRolePerms = "JOIN role_permissions ON permissions.id = role_permissions.permission_id"
	sqlJoinUserGroups = "JOIN user_groups ON user_groups.group_id = group_roles.group_id"
	sqlOrderCreatedAtDesc = "created_at DESC"
	sqlOrderIDAsc = "id ASC"
	sqlWhereDeletedBefore = "deleted_at IS NOT NULL AND deleted_at < ?"
	sqlWhereExpired = "expires_at IS NOT NULL AND expires_at <= ?"
	sqlWhereGRNotExpired = "group_roles.expires_at IS NULL OR group_roles.expires_at > ?"
	sqlWhereGroupRoleEnv = "group_id = ? AND role_id = ? AND project_id = ? AND environment_id = ?"
	sqlWhereID = "id = ?"
	sqlWhereIDsDeletedBefore = "id IN ? AND deleted_at IS NOT NULL AND deleted_at < ?"
	sqlWhereIsSecret = "s.is_secret = ?"
	sqlWhereProjectID = "project_id = ?"
	sqlWhereSecretNodeID = "secret_node_id = ?"
	sqlWhereShareActive = "secret_id = ? AND recipient_id = ? AND is_group = ? AND deleted_at IS NULL"
	sqlWhereUGUserID = "user_groups.user_id = ?"
	sqlWhereURNotExpired = "user_roles.expires_at IS NULL OR user_roles.expires_at > ?"
	sqlWhereURUserID = "user_roles.user_id = ?"
	sqlWhereUserID = "user_id = ?"
	sqlWhereUserIDIn = "user_id IN (?)"
	sqlWhereUserRoleEnv = "user_id = ? AND role_id = ? AND project_id = ? AND environment_id = ?"
)
