package store

import (
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"testing"
)

// remoteUnsupportedStatus categorizes why a RemoteStorage method is still an
// unconditional remoteUnsupported(...) stub.
type remoteUnsupportedStatus int

const (
	// statusIntentional means the stub is permanent by design — verified (not
	// assumed) to have no reachable caller under storage.type: remote, or to be
	// already superseded by a different mechanism. See Reason for the specific
	// citation.
	statusIntentional remoteUnsupportedStatus = iota
	// statusKnownGap means the stub is a confirmed, currently-reachable bug —
	// something breaks under storage.type: remote today. Tracked in
	// docs/security/HARDENING-BACKLOG.md; see Reason for the finding reference.
	statusKnownGap
)

type remoteUnsupportedEntry struct {
	status remoteUnsupportedStatus
	reason string
}

// remoteUnsupportedAllowlist is the exhaustive, reasoned inventory of every
// RemoteStorage method that still returns ErrRemoteUnsupported, generated by a
// round-119 classification audit (four independent read-only investigations,
// each tracing every method's real internal/core caller(s) and HTTP/gRPC
// reachability under storage.type: remote — not guessed). See
// docs/security/HARDENING-BACKLOG.md's round 119 entry for the full audit
// narrative and per-method citations.
//
// TestRemoteUnsupportedStubsAreAllowlisted below asserts this list is an EXACT
// match (not a superset) against the current source: a PR that adds a new
// unlisted remoteUnsupported(...) call fails immediately (forcing the same
// real-caller-tracing classification this list was built from, not a guess);
// a PR that fixes a listed method and forgets to remove its entry also fails
// (keeping this list from silently accumulating stale entries as gaps get
// closed round by round).
var remoteUnsupportedAllowlist = map[string]remoteUnsupportedEntry{
	// --- Confirmed genuinely permanent (11) ---

	"CountStaleMachineIdentitiesByProject": {statusIntentional,
		"the #393 grouped hygiene rollup query runs server-side only; documented in-code on the method itself"},

	"CreateNotification": {statusIntentional,
		"round 116 (#516): no self-scoped route an end-user credential could hit to create/escalate an arbitrary notification, and rightly so"},
	"HasUnreadNotification": {statusIntentional,
		"round 116 (#516): same reasoning as CreateNotification — no legitimate remote caller for this raw check"},
	"GetUnreadNotification": {statusIntentional,
		"round 116 (#516): same reasoning as CreateNotification"},
	"UpdateNotification": {statusIntentional,
		"round 116 (#516): same reasoning as CreateNotification — List/Count are proxied; raw mutation isn't a legitimate remote-caller need"},

	"WithAuditCheckpointLock": {statusIntentional,
		"round 119 audit: the entire audit-checkpoint feature (VerifyAuditChain, CreateAuditCheckpoint, LatestAuditCheckpoint, UpdateAuditCheckpointAnchor) is independently, unconditionally unimplemented for RemoteStorage too — the audit chain data lives at the hub. Bypassing just this lock would block nothing that isn't already blocked"},

	"SetSecretCertNotAfter": {statusIntentional,
		"round 119 audit: every caller (internal/core/certificate.go, certificate_expiry.go) invokes this as `_ = c.storage.SetSecretCertNotAfter(...)`, explicitly discarding the error — a best-effort ADR-056 compliance-posture cache write, never certificate inspection/rotation correctness"},
	"TryIncrementSecretReadCount": {statusIntentional,
		"round 119 audit: a best-effort, display-only per-version counter (caller discards the error). Real max-reads ENFORCEMENT is a separate call one line earlier, TryIncrementSecretNodeReadCount, which fails CLOSED under storage.type: remote — so a MaxReads-configured secret already denies the read before this stub is ever reached"},

	"CreateMFAChallenge": {statusIntentional,
		"round 119 audit: core.CreateMFAChallenge checks the RemoteMFAVerifier interface before ever calling storage.CreateMFAChallenge — under storage.type: remote this raw stub is never reached regardless of which second factor (TOTP or WebAuthn) follows; confirmed by TestLogin_RemoteStorage_ProxiesMFACredentialCheck"},
	"MarkTOTPStepUsed": {statusIntentional,
		"round 119 audit: sole caller is VerifyMFACredentials, only invoked from VerifyMFALogin's branch that's bypassed entirely when RemoteMFAVerifier is present"},
	"ConsumeMFARecoveryCode": {statusIntentional,
		"round 119 audit: sole caller is VerifyMFACredentials, same bypassed-branch reasoning as MarkTOTPStepUsed — recovery codes are only ever consumed at login, never during enrollment/management"},

	// --- Confirmed genuine gaps, tracked for future fix rounds (24; UpdateLoginLockoutState
	// closed by #529, SSO login state closed by #521, GetActiveMFAChallenge/
	// ConsumeMFAChallenge (WebAuthn-as-second-factor login) closed by #522, Connect
	// ref-grant CRUD closed by #527, self-service access-request workflow closed by
	// #523, RBAC permission catalog (ListPermissions/GetPermission/
	// GetRolePermissions) closed by #526, WithSchedulerLock closed by #530,
	// project/environment catalog CRUD closed by #528) ---
	// See docs/security/HARDENING-BACKLOG.md's round 119 entry for full detail,
	// severity, and grouping. Each entry below cites the real caller/route a
	// round-119 audit traced (not assumed).
	//
	// SSO login (both OIDC and SAML) was fixed in #521: CreateSSOLoginState/
	// ConsumeSSOLoginState are now proxied via /api/v1/system/sso-state
	// (server/http/handlers/sso_state_proxy.go), no longer unconditional stubs —
	// see internal/storage/store/remote_sso.go.

	// Self-service access-requests (request/list/approve/reject/withdraw) were
	// fixed in #523: CreateAccessRequest/GetAccessRequest/UpdateAccessRequest/
	// ListAccessRequests/CreateAccessRequestApproval/ListAccessRequestApprovals
	// are now proxied via /api/v1/system/access-requests(+/{id}/approvals)
	// (server/http/handlers/access_request_proxy.go), no longer unconditional
	// stubs — see internal/storage/store/remote_invitations.go.

	// MFA enrollment/management (not just login) — 100% broken.
	"UpsertMFASecret": {statusKnownGap, "round 119: BeginMFAEnrollment, POST /auth/mfa/enroll"},
	"GetMFASecret": {statusKnownGap,
		"round 119: ActivateMFA (POST /auth/mfa/activate) and requireReauth (gates disable/regenerate-codes/WebAuthn register-delete)"},
	"ActivateMFASecret": {statusKnownGap, "round 119: ActivateMFA, POST /auth/mfa/activate"},
	"DeleteMFAForUser":  {statusKnownGap, "round 119: DisableMFA, POST /auth/mfa/disable"},
	"SetUserMFAEnabled": {statusKnownGap, "round 119: ActivateMFA and DisableMFA"},
	"CreateMFARecoveryCodes": {statusKnownGap,
		"round 119: ActivateMFA and RegenerateMFARecoveryCodes (POST /auth/mfa/recovery-codes/regenerate)"},
	"CountUnusedMFARecoveryCodes": {statusKnownGap,
		"round 119: MFARecoveryCodesRemaining, GET /auth/mfa/recovery-codes"},
	"DeleteMFARecoveryCodes": {statusKnownGap,
		"round 119: RegenerateMFARecoveryCodes, POST /auth/mfa/recovery-codes/regenerate"},

	// RBAC role-grant primitives + last-admin/escalation guards.
	"GetGroupRoleGrants": {statusKnownGap,
		"round 119: GetGroupRoles handler (GET /groups/{id}/roles) — the method's own doc comment claiming the HTTP handler reads local storage instead is stale/wrong"},
	"AssignRoleWithExpiry": {statusKnownGap,
		"round 119: JIT-assign-with-expiry (POST /user-roles with expires_at) and the access-request TTL-grant approval path"},
	"AssignRoleToGroupWithExpiry": {statusKnownGap,
		"round 119: JIT group role grants, POST /groups/{id}/roles with expires_at"},
	"RemoveAllProjectRoleGrants": {statusKnownGap,
		"round 119: RemoveProjectMember, DELETE /projects/{id}/members/{userId} — a routine member-offboarding action"},
	"ListGroupRoleAssignments": {statusKnownGap,
		"round 119: AddUserToGroup's escalation-by-proxy ceiling check, POST /groups/{id}/members — breaks adding a user to a group for every authenticated caller"},
	"ListGlobalAdminAssignmentsForUpdate": {statusKnownGap,
		"round 119: guardLastGlobalAdmin (last-install-admin lockout guard), reached via DELETE /user-roles"},
	"ListProjectRoleAssignments": {statusKnownGap,
		"round 119: multiple last-global-admin guards, access reviews, RestoreProject's admin-ceiling check, compliance posture, SCIM"},
	"ListProjectMachineRoleAssignments": {statusKnownGap,
		"round 119: machine-identity access-review coverage (#91), GET /projects/{id}/access-review"},

	// RBAC permission catalog (ListPermissions/GetPermission/GetRolePermissions) was
	// fixed in #526 — see internal/storage/store/remote_rbac.go.

	// Project / environment catalog CRUD was fixed in #528: ListProjects/
	// ListProjectsWithCounts/GetProject/UpdateProject/DeleteProject/RestoreProject/
	// ListEnvironments/ListEnvironmentsByProject/
	// ListEnvironmentsByProjectIncludingDeleted/ListProjectMembers/GetEnvironment/
	// DeleteEnvironment/RestoreEnvironment are now proxied via
	// /api/v1/system/projects* and /api/v1/system/environments*
	// (server/http/handlers/project_catalog_proxy.go,
	// environment_catalog_proxy.go), no longer unconditional stubs — see
	// internal/storage/store/remote_rbac.go's Project/Environment section. The
	// force=false delete guard now runs as ONE atomic storage.Storage call
	// (DeleteProjectIfEmpty) instead of a WithTransaction-wrapped
	// ListSecrets+DeleteProject pair, closing a TOCTOU window that pair would have
	// reopened across the HTTP hop (see that method's interface doc comment).
	// GetEnvironment's #499 carve-out inside core.CreateSecret is unaffected —
	// see internal/core/secrets.go.

	// Misc.
	"LastUserSecretActivity": {statusKnownGap,
		"round 119: GenerateProjectAccessReview (ISO 27001/SOC2 recertification) — degrades gracefully but the dormant-access signal is never available"},
	"LastUserRoleManagementActivity": {statusKnownGap,
		"round 119: compliance_posture.go's countDormantRoleGrants — degrades gracefully, same missing-signal issue"},
	"LastUserSecretDeletionActivity": {statusKnownGap, "round 119: same flow as LastUserRoleManagementActivity"},
	"LastUserSecretReadActivity":     {statusKnownGap, "round 119: same flow as LastUserRoleManagementActivity"},
	"LastUserSecretWriteActivity":    {statusKnownGap, "round 119: same flow as LastUserRoleManagementActivity"},
	"GetSecretIncludingDeleted": {statusKnownGap,
		"round 119: ScopeFromDeletedSecretParam's scope check ahead of POST /secrets/{id}/restore — every restore request 404s before ever reaching the (already-proxied) RestoreSecret"},
	"ListSharesByOwner": {statusKnownGap,
		"round 119: core.ListSharesByUser hard-fails (no fallback), backing the gRPC ListShares \"my shares\" call"},
	"CreateUserWithRoleGrants": {statusKnownGap,
		"round 119: CreateUserWithAssignments (atomic create-user+role-grants), POST /api/v1/users and gRPC CreateUser"},
}

// remoteUnsupportedCallRe matches the exact, 100%-consistent call pattern every
// stub in this package uses: remoteUnsupported("MethodName"). Verified by hand
// against every remote_*.go file before writing this test — no stub deviates
// from this literal-string-argument form.
var remoteUnsupportedCallRe = regexp.MustCompile(`remoteUnsupported\("([A-Za-z0-9_]+)"\)`)

// actualRemoteUnsupportedStubs scans every non-test remote_*.go source file in
// this package (except remote_unsupported.go itself, which only defines the
// helper) and returns the set of method names currently implemented as an
// unconditional remoteUnsupported(...) stub.
func actualRemoteUnsupportedStubs(t *testing.T) map[string]bool {
	t.Helper()
	found := map[string]bool{}
	entries, err := os.ReadDir(".")
	if err != nil {
		t.Fatalf("reading internal/storage/store: %v", err)
	}
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasPrefix(name, "remote_") || !strings.HasSuffix(name, ".go") ||
			strings.HasSuffix(name, "_test.go") || name == "remote_unsupported.go" {
			continue
		}
		b, err := os.ReadFile(filepath.Join(".", name))
		if err != nil {
			t.Fatalf("reading %s: %v", name, err)
		}
		for _, m := range remoteUnsupportedCallRe.FindAllStringSubmatch(string(b), -1) {
			found[m[1]] = true
		}
	}
	return found
}

// TestRemoteUnsupportedStubsAreAllowlisted is the completeness guard: every
// RemoteStorage method that still returns ErrRemoteUnsupported must be an
// EXACT match against remoteUnsupportedAllowlist above — no more, no less.
//
//   - A method that becomes a NEW unconditional stub (or is discovered and never
//     classified) fails this test immediately, forcing the same real-caller-
//     tracing investigation this list was built from before it can be merged —
//     preventing the silent, piecemeal rediscovery this campaign has repeated
//     for ~10 rounds (#503-class, #513, #517-520, and this round-119 audit
//     that found 55 more).
//   - A method that gets FIXED (proxied for real) but whose allowlist entry is
//     forgotten also fails this test, keeping the list from accumulating stale
//     "known gap" entries that no longer reflect reality — remove the entry in
//     the same PR that lands the fix.
func TestRemoteUnsupportedStubsAreAllowlisted(t *testing.T) {
	actual := actualRemoteUnsupportedStubs(t)

	var missingFromAllowlist []string // real stub, no allowlist entry — a new/forgotten gap
	for name := range actual {
		if _, ok := remoteUnsupportedAllowlist[name]; !ok {
			missingFromAllowlist = append(missingFromAllowlist, name)
		}
	}
	sort.Strings(missingFromAllowlist)

	var staleAllowlistEntries []string // allowlisted, but no longer an actual stub — fixed and forgotten
	for name := range remoteUnsupportedAllowlist {
		if !actual[name] {
			staleAllowlistEntries = append(staleAllowlistEntries, name)
		}
	}
	sort.Strings(staleAllowlistEntries)

	if len(missingFromAllowlist) > 0 {
		t.Errorf("found %d RemoteStorage method(s) returning ErrRemoteUnsupported with NO allowlist entry "+
			"in remoteUnsupportedAllowlist (internal/storage/store/remote_unsupported_completeness_test.go): %v\n"+
			"Every remoteUnsupported(...) call site must be classified as statusIntentional (verified permanent, "+
			"with a real reason) or statusKnownGap (a real, currently-reachable bug, referencing a backlog finding) "+
			"before it can be merged — trace the method's actual internal/core caller(s) and HTTP/gRPC reachability "+
			"under storage.type: remote, don't guess.", len(missingFromAllowlist), missingFromAllowlist)
	}
	if len(staleAllowlistEntries) > 0 {
		t.Errorf("found %d remoteUnsupportedAllowlist entr(y/ies) that are no longer actual "+
			"remoteUnsupported(...) stubs (they were fixed): %v\n"+
			"Remove these entries from remoteUnsupportedAllowlist — if the fix closed a tracked backlog "+
			"finding, this test failing is your reminder to also update docs/security/BUGS.md.", len(staleAllowlistEntries), staleAllowlistEntries)
	}
}
