package store

import (
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"testing"
)

// remoteUnsupportedStatus categorizes why a RemoteStorage method is still an
// unconditional remoteUnsupported(...) stub.
type remoteUnsupportedStatus int

const (
	// statusIntentional means the stub is permanent by design — verified (not
	// assumed) to have no reachable caller under storage.type: remote, or to be
	// already superseded by a different mechanism. See Reason for the specific
	// citation.
	statusIntentional remoteUnsupportedStatus = iota
	// statusKnownGap means the stub is a confirmed, currently-reachable bug —
	// something breaks under storage.type: remote today. Tracked in
	// docs/security/HARDENING-BACKLOG.md; see Reason for the finding reference.
	//
	// Round 119's entire genuine-gap list is closed as of #531, so no allowlist
	// entry currently uses this value — kept (not deleted) since the NEXT stub a
	// future round finds needs it immediately; deleting and re-adding it every
	// time the count round-trips through zero would just be churn.
	statusKnownGap //nolint:unused
)

type remoteUnsupportedEntry struct {
	status remoteUnsupportedStatus
	reason string
}

// remoteUnsupportedAllowlist is the exhaustive, reasoned inventory of every
// RemoteStorage method that still returns ErrRemoteUnsupported, generated by a
// round-119 classification audit (four independent read-only investigations,
// each tracing every method's real internal/core caller(s) and HTTP/gRPC
// reachability under storage.type: remote — not guessed). See
// docs/security/HARDENING-BACKLOG.md's round 119 entry for the full audit
// narrative and per-method citations.
//
// TestRemoteUnsupportedStubsAreAllowlisted below asserts this list is an EXACT
// match (not a superset) against the current source: a PR that adds a new
// unlisted remoteUnsupported(...) call fails immediately (forcing the same
// real-caller-tracing classification this list was built from, not a guess);
// a PR that fixes a listed method and forgets to remove its entry also fails
// (keeping this list from silently accumulating stale entries as gaps get
// closed round by round).
var remoteUnsupportedAllowlist = map[string]remoteUnsupportedEntry{
	// --- Confirmed genuinely permanent (16) ---

	"CountStaleMachineIdentitiesByProject": {statusIntentional,
		"the #393 grouped hygiene rollup query runs server-side only; documented in-code on the method itself"},

	"CreateNotification": {statusIntentional,
		"round 116 (#516): no self-scoped route an end-user credential could hit to create/escalate an arbitrary notification, and rightly so"},
	"HasUnreadNotification": {statusIntentional,
		"round 116 (#516): same reasoning as CreateNotification — no legitimate remote caller for this raw check"},
	"GetUnreadNotification": {statusIntentional,
		"round 116 (#516): same reasoning as CreateNotification"},
	"UpdateNotification": {statusIntentional,
		"round 116 (#516): same reasoning as CreateNotification — List/Count are proxied; raw mutation isn't a legitimate remote-caller need"},

	"WithAuditCheckpointLock": {statusIntentional,
		"round 119 audit: the entire audit-checkpoint feature (VerifyAuditChain, CreateAuditCheckpoint, LatestAuditCheckpoint, UpdateAuditCheckpointAnchor) is independently, unconditionally unimplemented for RemoteStorage too — the audit chain data lives at the hub. Bypassing just this lock would block nothing that isn't already blocked"},

	"SetSecretCertNotAfter": {statusIntentional,
		"round 119 audit: every caller (internal/core/certificate.go, certificate_expiry.go) invokes this as `_ = c.storage.SetSecretCertNotAfter(...)`, explicitly discarding the error — a best-effort ADR-056 compliance-posture cache write, never certificate inspection/rotation correctness"},
	"TryIncrementSecretReadCount": {statusIntentional,
		"round 119 audit: a best-effort, display-only per-version counter (caller discards the error). Real max-reads ENFORCEMENT is a separate call one line earlier, TryIncrementSecretNodeReadCount, which fails CLOSED under storage.type: remote — so a MaxReads-configured secret already denies the read before this stub is ever reached"},

	"CreateMFAChallenge": {statusIntentional,
		"round 119 audit: core.CreateMFAChallenge checks the RemoteMFAVerifier interface before ever calling storage.CreateMFAChallenge — under storage.type: remote this raw stub is never reached regardless of which second factor (TOTP or WebAuthn) follows; confirmed by TestLogin_RemoteStorage_ProxiesMFACredentialCheck"},
	"MarkTOTPStepUsed": {statusIntentional,
		"round 119 audit: sole caller is VerifyMFACredentials, only invoked from VerifyMFALogin's branch that's bypassed entirely when RemoteMFAVerifier is present"},
	"ConsumeMFARecoveryCode": {statusIntentional,
		"round 119 audit: sole caller is VerifyMFACredentials, same bypassed-branch reasoning as MarkTOTPStepUsed — recovery codes are only ever consumed at login, never during enrollment/management"},

	// --- Confirmed genuine gaps, tracked for future fix rounds (0; UpdateLoginLockoutState
	// closed by #529, SSO login state closed by #521, GetActiveMFAChallenge/
	// ConsumeMFAChallenge (WebAuthn-as-second-factor login) closed by #522, Connect
	// ref-grant CRUD closed by #527, self-service access-request workflow closed by
	// #523, RBAC permission catalog (ListPermissions/GetPermission/
	// GetRolePermissions) closed by #526, WithSchedulerLock closed by #530,
	// project/environment catalog CRUD closed by #528, MFA enrolment/management
	// closed by #524, RBAC role-grant primitives closed by #525, misc gaps (the
	// five LastUser*Activity methods, GetSecretIncludingDeleted, ListSharesByOwner,
	// CreateUserWithRoleGrants) closed by #531 — round 119's entire genuine-gap
	// list is now closed; #97 (MEDIUM, no further code action planned) and
	// #104/#253 (LOW, already settled) are the only backlog items left, see
	// docs/security/HARDENING-BACKLOG.md) ---
	// See docs/security/HARDENING-BACKLOG.md's round 119 entry for full detail,
	// severity, and grouping. Each entry below cites the real caller/route a
	// round-119 audit traced (not assumed).
	//
	// SSO login (both OIDC and SAML) was fixed in #521: CreateSSOLoginState/
	// ConsumeSSOLoginState are now proxied via /api/v1/system/sso-state
	// (server/http/handlers/sso_state_proxy.go), no longer unconditional stubs —
	// see internal/storage/store/remote_sso.go.

	// Self-service access-requests (request/list/approve/reject/withdraw) were
	// fixed in #523: CreateAccessRequest/GetAccessRequest/UpdateAccessRequest/
	// ListAccessRequests/CreateAccessRequestApproval/ListAccessRequestApprovals
	// are now proxied via /api/v1/system/access-requests(+/{id}/approvals)
	// (server/http/handlers/access_request_proxy.go), no longer unconditional
	// stubs — see internal/storage/store/remote_invitations.go.

	// MFA enrollment/management (not just login) — closed by #524: now proxied via
	// /api/v1/system/mfa (server/http/handlers/mfa_management_proxy.go), see
	// internal/storage/store/remote_mfa.go.

	// RBAC role-grant primitives + last-admin/escalation guards were closed by
	// #525: GetGroupRoleGrants/AssignRoleWithExpiry/AssignRoleToGroupWithExpiry/
	// RemoveAllProjectRoleGrants/ListGroupRoleAssignments/
	// ListGlobalAdminAssignmentsForUpdate/ListProjectRoleAssignments/
	// ListProjectMachineRoleAssignments are now proxied via
	// /api/v1/system/rbac/... (server/http/handlers/rbac_role_grants_proxy.go) —
	// see internal/storage/store/remote_rbac.go. RemoveUserRole's last-global-admin
	// guard additionally gained a new atomic primitive,
	// RemoveGlobalAdminRoleGuarded, folding the check and the removal into ONE
	// storage call (a naive two-call proxy would have reopened #340's
	// cross-process TOCTOU race across an HTTP hop — RemoteStorage.WithTransaction
	// is a no-op passthrough).

	// RBAC permission catalog (ListPermissions/GetPermission/GetRolePermissions) was
	// fixed in #526 — see internal/storage/store/remote_rbac.go.

	// Project / environment catalog CRUD was fixed in #528: ListProjects/
	// ListProjectsWithCounts/GetProject/UpdateProject/DeleteProject/RestoreProject/
	// ListEnvironments/ListEnvironmentsByProject/
	// ListEnvironmentsByProjectIncludingDeleted/ListProjectMembers/GetEnvironment/
	// DeleteEnvironment/RestoreEnvironment are now proxied via
	// /api/v1/system/projects* and /api/v1/system/environments*
	// (server/http/handlers/project_catalog_proxy.go,
	// environment_catalog_proxy.go), no longer unconditional stubs — see
	// internal/storage/store/remote_rbac.go's Project/Environment section. The
	// force=false delete guard now runs as ONE atomic storage.Storage call
	// (DeleteProjectIfEmpty) instead of a WithTransaction-wrapped
	// ListSecrets+DeleteProject pair, closing a TOCTOU window that pair would have
	// reopened across the HTTP hop (see that method's interface doc comment).
	// GetEnvironment's #499 carve-out inside core.CreateSecret is unaffected —
	// see internal/core/secrets.go.

	// Scheduler locking was fixed in #530: TryAcquireSchedulerLock/
	// ReleaseSchedulerLock are now proxied via /api/v1/system/scheduler-lock/*
	// (server/http/handlers/scheduler_lock_proxy.go), no longer an unconditional
	// stub — see internal/storage/store/remote_scheduler_lock.go. Each route
	// resolves its entire acquire/release decision in ONE storage.Storage call,
	// so no naive "check, then write" pair is ever exposed over the HTTP hop to
	// reopen the exclusivity race the lock exists to prevent.

	// Misc (#531): the five LastUser*Activity methods, GetSecretIncludingDeleted,
	// and ListSharesByOwner are now proxied via /api/v1/system/access-activity/*,
	// /api/v1/system/secrets/{id}/including-deleted, and
	// /api/v1/system/shares/by-owner/{ownerID} (server/http/handlers/
	// misc_remote_proxy.go). CreateUserWithRoleGrants required a new atomic
	// primitive rather than a naive two-call proxy — LocalStorage wraps the
	// user-create + role-grant inserts in one real DB transaction (ADR-028), and
	// RemoteStorage.WithTransaction is a no-op passthrough, so it's proxied as
	// ONE atomic call via POST /api/v1/system/users/with-role-grants instead —
	// see internal/storage/store/remote_users.go.

	// Secret ACL (RBAC Phase 3) — no proxy routes exist yet. A future PR will
	// add /api/v1/system/secret-acls endpoints mirroring the secret-dependencies
	// pattern. For now the five methods are intentional stubs: the ACL feature
	// only runs server-side and a remote-storage caller never directly invokes
	// ACL management or the folder-inheritance ancestor walk (the HTTP/gRPC
	// boundary owns authorization; HasSecretACL/AuthorizeSecret run on the server).
	"ListAllUserRoleGrants": {statusIntentional, "permission matrix is server-aggregated via GET /api/v1/rbac/permission-matrix; direct grant enumeration runs server-side"},

	// Temporal access schedule — schedule enforcement runs server-side inside
	// checkSecretAccessSchedule; a remote CLI caller never invokes these storage
	// primitives directly. Schedule management is exposed via HTTP handlers
	// (server/http/handlers/secret_schedule.go) under /api/v1/secrets/{id}/schedule.
	"GetSecretAccessSchedule":    {statusIntentional, "temporal schedule check runs server-side; schedule management routes are HTTP-proxied via secret_schedule.go"},
	"SetSecretAccessSchedule":    {statusIntentional, "temporal schedule check runs server-side; schedule management routes are HTTP-proxied via secret_schedule.go"},
	"DeleteSecretAccessSchedule": {statusIntentional, "temporal schedule check runs server-side; schedule management routes are HTTP-proxied via secret_schedule.go"},

	"CreateOrUpdateSecretACL":  {statusIntentional, "RBAC Phase 3 — no proxy route yet; ACL management is always server-side"},
	"ListSecretACLs":           {statusIntentional, "RBAC Phase 3 — no proxy route yet; ACL management is always server-side"},
	"ListSecretACLsByUser":     {statusIntentional, "RBAC Phase 3 — listing ACL-granted secrets for a user runs server-side in ListSecretsWithSharingInfo; the core function calls LocalStorage on the server, not RemoteStorage"},
	"GetSecretACL":             {statusIntentional, "RBAC Phase 3 — no proxy route yet; ACL management is always server-side"},
	"DeleteSecretACL":          {statusIntentional, "RBAC Phase 3 — no proxy route yet; ACL management is always server-side"},
	"GetSecretAncestors":       {statusIntentional, "RBAC Phase 3 — folder-ACL inheritance walk runs server-side; HasSecretACL uses ErrUnsupportedByBackend to skip the ancestor walk on remote callers"},

	"GetProjectUsageStats": {statusIntentional, "usage report queries run server-side; a future PR may add a /api/v1/system/usage proxy route"},

	// Anomaly config — server-side singleton; a remote-storage caller manages the
	// config via the REST endpoint (GET/PUT /api/v1/admin/anomaly-config), so the
	// storage layer itself is never reached through a remote hop.
	"GetAnomalyConfig":  {statusIntentional, "anomaly config is managed via /api/v1/admin/anomaly-config; raw storage call never reached from a remote-storage caller"},
	"SaveAnomalyConfig": {statusIntentional, "anomaly config is managed via /api/v1/admin/anomaly-config; raw storage call never reached from a remote-storage caller"},

	// Deployment-wide stats snapshots — saved and read server-side only.
	"SaveDeploymentStatsSnapshot":        {statusIntentional, "deployment-wide stats snapshots are saved server-side in GetDashboardStats; a remote caller never directly invokes this"},
	"GetPreviousDeploymentStatsSnapshot": {statusIntentional, "deployment-wide stats snapshot retrieval runs server-side; the trend is computed in core.GetDashboardStats, not in the CLI"},

	// Compliance posture snapshots — written and read inside GetCompliancePosture,
	// a server-side admin endpoint. No CLI/remote caller ever invokes these directly;
	// no REST proxy routes exist or are planned (the snapshot is internal telemetry,
	// not a user-facing API surface).
	"SaveCompliancePostureSnapshot":        {statusIntentional, "compliance posture snapshot writes are server-side only; GetCompliancePosture is a server-only admin endpoint with no remote caller"},
	"GetPreviousCompliancePostureSnapshot": {statusIntentional, "compliance posture snapshot reads are server-side only; same reasoning as SaveCompliancePostureSnapshot"},
}

// remoteUnsupportedCallRe matches the exact, 100%-consistent call pattern every
// stub in this package uses: remoteUnsupported("MethodName"). Verified by hand
// against every remote_*.go file before writing this test — no stub deviates
// from this literal-string-argument form.
var remoteUnsupportedCallRe = regexp.MustCompile(`remoteUnsupported\("([A-Za-z0-9_]+)"\)`)

// actualRemoteUnsupportedStubs scans every non-test remote_*.go source file in
// this package (except remote_unsupported.go itself, which only defines the
// helper) and returns the set of method names currently implemented as an
// unconditional remoteUnsupported(...) stub.
func actualRemoteUnsupportedStubs(t *testing.T) map[string]bool {
	t.Helper()
	found := map[string]bool{}
	entries, err := os.ReadDir(".")
	if err != nil {
		t.Fatalf("reading internal/storage/store: %v", err)
	}
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasPrefix(name, "remote_") || !strings.HasSuffix(name, ".go") ||
			strings.HasSuffix(name, "_test.go") || name == "remote_unsupported.go" {
			continue
		}
		b, err := os.ReadFile(filepath.Join(".", name))
		if err != nil {
			t.Fatalf("reading %s: %v", name, err)
		}
		for _, m := range remoteUnsupportedCallRe.FindAllStringSubmatch(string(b), -1) {
			found[m[1]] = true
		}
	}
	return found
}

// TestRemoteUnsupportedStubsAreAllowlisted is the completeness guard: every
// RemoteStorage method that still returns ErrRemoteUnsupported must be an
// EXACT match against remoteUnsupportedAllowlist above — no more, no less.
//
//   - A method that becomes a NEW unconditional stub (or is discovered and never
//     classified) fails this test immediately, forcing the same real-caller-
//     tracing investigation this list was built from before it can be merged —
//     preventing the silent, piecemeal rediscovery this campaign has repeated
//     for ~10 rounds (#503-class, #513, #517-520, and this round-119 audit
//     that found 55 more).
//   - A method that gets FIXED (proxied for real) but whose allowlist entry is
//     forgotten also fails this test, keeping the list from accumulating stale
//     "known gap" entries that no longer reflect reality — remove the entry in
//     the same PR that lands the fix.
func TestRemoteUnsupportedStubsAreAllowlisted(t *testing.T) {
	actual := actualRemoteUnsupportedStubs(t)

	var missingFromAllowlist []string // real stub, no allowlist entry — a new/forgotten gap
	for name := range actual {
		if _, ok := remoteUnsupportedAllowlist[name]; !ok {
			missingFromAllowlist = append(missingFromAllowlist, name)
		}
	}
	sort.Strings(missingFromAllowlist)

	var staleAllowlistEntries []string // allowlisted, but no longer an actual stub — fixed and forgotten
	for name := range remoteUnsupportedAllowlist {
		if !actual[name] {
			staleAllowlistEntries = append(staleAllowlistEntries, name)
		}
	}
	sort.Strings(staleAllowlistEntries)

	if len(missingFromAllowlist) > 0 {
		t.Errorf("found %d RemoteStorage method(s) returning ErrRemoteUnsupported with NO allowlist entry "+
			"in remoteUnsupportedAllowlist (internal/storage/store/remote_unsupported_completeness_test.go): %v\n"+
			"Every remoteUnsupported(...) call site must be classified as statusIntentional (verified permanent, "+
			"with a real reason) or statusKnownGap (a real, currently-reachable bug, referencing a backlog finding) "+
			"before it can be merged — trace the method's actual internal/core caller(s) and HTTP/gRPC reachability "+
			"under storage.type: remote, don't guess.", len(missingFromAllowlist), missingFromAllowlist)
	}
	if len(staleAllowlistEntries) > 0 {
		t.Errorf("found %d remoteUnsupportedAllowlist entr(y/ies) that are no longer actual "+
			"remoteUnsupported(...) stubs (they were fixed): %v\n"+
			"Remove these entries from remoteUnsupportedAllowlist — if the fix closed a tracked backlog "+
			"finding, this test failing is your reminder to also update docs/security/BUGS.md.", len(staleAllowlistEntries), staleAllowlistEntries)
	}
}
