package healthscan

import (
	"bytes"
	"encoding/json"
	"strings"
	"testing"
)

func sampleReport() *Report {
	findings := []Finding{
		{ID: "audit-devices", Title: "Audit devices", Severity: SeverityCritical, Evidence: "no audit device enabled", WhyItMatters: "no trail", Remediation: "enable one"},
		{ID: "version-eol", Title: "Vault version", Severity: SeverityInfo, Evidence: "1.17.6"},
	}
	r := &Report{
		GeneratedBy: "keyorix-migrate dev", VaultAddr: "https://vault.example.com",
		Findings: findings, Score: Score(findings), ScoreFormula: ScoreFormula, TopRisks: TopRisks(findings, 5),
		NotChecked: []NotChecked{{ID: "root-tokens", Reason: "requires POST, never issued"}},
		Footer:     "Generated by keyorix-migrate dev. For an expert review, see https://example.com/assessment.",
	}
	return r
}

func TestWriteMarkdown_ExecutiveSummary(t *testing.T) {
	var buf bytes.Buffer
	if err := WriteMarkdown(&buf, sampleReport()); err != nil {
		t.Fatalf("WriteMarkdown: %v", err)
	}
	out := buf.String()
	if !strings.Contains(out, "Score: 75/100") {
		t.Errorf("expected the score in the executive summary, got:\n%s", out)
	}
	if !strings.Contains(out, ScoreFormula) {
		t.Error("expected the score formula to be stated verbatim")
	}
	if !strings.Contains(out, "[audit-devices] Audit devices") {
		t.Error("expected the critical finding to appear in top risks")
	}
	if !strings.Contains(out, "## Not checked") || !strings.Contains(out, "root-tokens") {
		t.Error("expected the Not checked section")
	}
	if !strings.Contains(out, "## Migration readiness") {
		t.Error("expected a Migration readiness section even when nil")
	}
	if !strings.Contains(out, "Not available for this scan") {
		t.Error("expected the nil-MigrationReadiness case to say so plainly")
	}
	if !strings.Contains(out, sampleReport().Footer) {
		t.Error("expected the footer")
	}
}

func TestWriteMarkdown_MigrationReadinessPopulated(t *testing.T) {
	r := sampleReport()
	r.MigrationReadiness = &MigrationReadiness{KVv1Mounts: 1, KVv2Mounts: 2, KVTopLevelSecrets: 42, DynamicMounts: []string{"database/(database)"}}
	var buf bytes.Buffer
	if err := WriteMarkdown(&buf, r); err != nil {
		t.Fatalf("WriteMarkdown: %v", err)
	}
	out := buf.String()
	if !strings.Contains(out, "KV v1 mounts: 1") || !strings.Contains(out, "KV v2 mounts: 2") || !strings.Contains(out, "42") {
		t.Errorf("expected migration readiness counts in output:\n%s", out)
	}
	if !strings.Contains(out, "database/(database)") {
		t.Error("expected the dynamic mount to be listed as not importable")
	}
}

func TestWriteHTML_EscapesHostileEvidence(t *testing.T) {
	r := sampleReport()
	r.Findings[0].Evidence = `<script>alert(1)</script>`
	var buf bytes.Buffer
	if err := WriteHTML(&buf, r); err != nil {
		t.Fatalf("WriteHTML: %v", err)
	}
	out := buf.String()
	if strings.Contains(out, "<script>alert(1)</script>") {
		t.Fatal("unescaped evidence would let a Vault-controlled string inject markup into the report")
	}
	if !strings.Contains(out, "&lt;script&gt;") {
		t.Error("expected the evidence to be HTML-escaped, not dropped")
	}
}

func TestWriteJSON_SchemaVersion(t *testing.T) {
	var buf bytes.Buffer
	if err := WriteJSON(&buf, sampleReport()); err != nil {
		t.Fatalf("WriteJSON: %v", err)
	}
	var decoded struct {
		SchemaVersion int    `json:"schema_version"`
		Score         int    `json:"score"`
		ScoreFormula  string `json:"score_formula"`
	}
	if err := json.Unmarshal(buf.Bytes(), &decoded); err != nil {
		t.Fatalf("decode: %v", err)
	}
	if decoded.SchemaVersion != SchemaVersion {
		t.Errorf("schema_version = %d, want %d", decoded.SchemaVersion, SchemaVersion)
	}
	if decoded.Score != 75 {
		t.Errorf("score = %d, want 75", decoded.Score)
	}
	if decoded.ScoreFormula == "" {
		t.Error("expected score_formula to be present in JSON")
	}
}

func TestReport_NoMarketingToneInFooter(t *testing.T) {
	// A cheap, machine-checkable proxy for "no marketing tone": the footer must not contain
	// exclamation points or superlatives a sales-y footer would use.
	r := sampleReport()
	for _, banned := range []string{"!", "amazing", "best-in-class", "revolutionary"} {
		if strings.Contains(strings.ToLower(r.Footer), banned) {
			t.Errorf("footer contains marketing-toned text %q: %q", banned, r.Footer)
		}
	}
}
