// Package apiclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package apiclient

import (
	"time"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ListProjectsParamsIncludeDeleted.
const (
	ListProjectsParamsIncludeDeletedFalse ListProjectsParamsIncludeDeleted = "false"
	ListProjectsParamsIncludeDeletedTrue  ListProjectsParamsIncludeDeleted = "true"
)

// Defines values for ListProjectEnvironmentsParamsIncludeDeleted.
const (
	ListProjectEnvironmentsParamsIncludeDeletedFalse ListProjectEnvironmentsParamsIncludeDeleted = "false"
	ListProjectEnvironmentsParamsIncludeDeletedTrue  ListProjectEnvironmentsParamsIncludeDeleted = "true"
)

// Defines values for ListSecretsParamsClassification.
const (
	Confidential ListSecretsParamsClassification = "confidential"
	Internal     ListSecretsParamsClassification = "internal"
	Public       ListSecretsParamsClassification = "public"
	Restricted   ListSecretsParamsClassification = "restricted"
	Unclassified ListSecretsParamsClassification = "unclassified"
)

// Environment A project environment (internal/storage/models.Environment). No `json:` tags on the model -- wire keys are the bare Go field names (ID, ProjectID, Name, CreatedAt, UpdatedAt), not snake_case. Unlike Permission/RoleWithPermissions above, ProjectID/CreatedAt/UpdatedAt do NOT case-insensitively match a snake_case tag (the underscore makes "project_id" a different string from "projectid"), so a generated client MUST use these exact capitalized property names to decode correctly.
type Environment struct {
	CreatedAt *time.Time `json:"CreatedAt,omitempty"`
	ID        *int       `json:"ID,omitempty"`
	Name      *string    `json:"Name,omitempty"`
	ProjectID *int       `json:"ProjectID,omitempty"`
	UpdatedAt *time.Time `json:"UpdatedAt,omitempty"`
}

// PATToken A personal access token (ADR-027/ADR-042). The raw secret is never returned except once, in the create response.
type PATToken struct {
	AllowedCidrs     *[]string  `json:"allowed_cidrs"`
	CreatedAt        *time.Time `json:"created_at,omitempty"`
	EnvironmentScope *int       `json:"environment_scope,omitempty"`
	ExpiresAt        *time.Time `json:"expires_at"`
	Id               *int       `json:"id,omitempty"`
	LastUsedAt       *time.Time `json:"last_used_at"`
	Name             *string    `json:"name,omitempty"`
	ProjectScope     *int       `json:"project_scope,omitempty"`
	Revoked          *bool      `json:"revoked,omitempty"`
	Scopes           *[]string  `json:"scopes"`
	TokenPrefix      *string    `json:"token_prefix,omitempty"`
}

// Secret A secret or folder node (internal/storage/models.SecretNode), metadata only -- never a value. No `json:` tags on the model -- wire keys are the bare Go field names (ID, ProjectID, ...), not snake_case (ADR-108 PR 4/5).
type Secret struct {
	AutoRotate     *bool      `json:"AutoRotate,omitempty"`
	Classification *string    `json:"Classification,omitempty"`
	CreatedAt      *time.Time `json:"CreatedAt,omitempty"`
	CreatedBy      *string    `json:"CreatedBy,omitempty"`
	Description    *string    `json:"Description,omitempty"`
	EnvironmentID  *int       `json:"EnvironmentID,omitempty"`
	Expiration     *time.Time `json:"Expiration"`
	ID             *int       `json:"ID,omitempty"`

	// IsSecret false = this node is a folder.
	IsSecret               *bool      `json:"IsSecret,omitempty"`
	IsShared               *bool      `json:"IsShared,omitempty"`
	LastRotatedAt          *time.Time `json:"LastRotatedAt"`
	MaxReads               *int       `json:"MaxReads"`
	Name                   *string    `json:"Name,omitempty"`
	OwnerID                *int       `json:"OwnerID,omitempty"`
	OwnerMachineIdentityID *int       `json:"OwnerMachineIdentityID,omitempty"`
	ParentID               *int       `json:"ParentID"`
	ProjectID              *int       `json:"ProjectID,omitempty"`
	ReadCount              *int       `json:"ReadCount,omitempty"`
	RotationBackend        *string    `json:"RotationBackend,omitempty"`
	RotationCharset        *string    `json:"RotationCharset,omitempty"`
	RotationLength         *int       `json:"RotationLength,omitempty"`
	RotationRef            *string    `json:"RotationRef,omitempty"`
	Status                 *string    `json:"Status,omitempty"`
	Type                   *string    `json:"Type,omitempty"`
	UpdatedAt              *time.Time `json:"UpdatedAt,omitempty"`
}

// SecretGetResult GET /api/v1/secrets/{id}'s response `data`: the bare Secret fields directly (metadata-only), OR, when include_value=true, `{secret, value}` instead. Declared as one flat schema combining both shapes' properties (rather than oneOf) since the CLI always knows in advance which branch a given request will get -- it controls include_value.
type SecretGetResult struct {
	Classification *string    `json:"Classification,omitempty"`
	CreatedAt      *time.Time `json:"CreatedAt,omitempty"`
	CreatedBy      *string    `json:"CreatedBy,omitempty"`
	Description    *string    `json:"Description,omitempty"`
	EnvironmentID  *int       `json:"EnvironmentID,omitempty"`
	Expiration     *time.Time `json:"Expiration"`
	ID             *int       `json:"ID,omitempty"`
	IsSecret       *bool      `json:"IsSecret,omitempty"`
	IsShared       *bool      `json:"IsShared,omitempty"`
	LastRotatedAt  *time.Time `json:"LastRotatedAt"`
	MaxReads       *int       `json:"MaxReads"`
	Name           *string    `json:"Name,omitempty"`
	OwnerID        *int       `json:"OwnerID,omitempty"`
	ParentID       *int       `json:"ParentID"`
	ProjectID      *int       `json:"ProjectID,omitempty"`
	ReadCount      *int       `json:"ReadCount,omitempty"`
	Status         *string    `json:"Status,omitempty"`
	Type           *string    `json:"Type,omitempty"`
	UpdatedAt      *time.Time `json:"UpdatedAt,omitempty"`

	// Secret A secret or folder node (internal/storage/models.SecretNode), metadata only -- never a value. No `json:` tags on the model -- wire keys are the bare Go field names (ID, ProjectID, ...), not snake_case (ADR-108 PR 4/5).
	Secret *Secret `json:"secret,omitempty"`

	// Value The decrypted value. Present only when include_value=true.
	Value *string `json:"value,omitempty"`
}

// SecretListEntry One row of GET /api/v1/secrets's data.secrets[] (internal/storage/models.SecretWithSharingInfo, which anonymously embeds *SecretNode -- Go's encoding/json promotes the embedded struct's fields onto this same object). Wire keys are a genuine MIX of case conventions: SecretNode's own fields are bare capitalized (ID, Name, IsShared, ...), while SecretWithSharingInfo's own fields are snake_case (project_name, is_shared, ...) -- IsShared and is_shared are both present as DIFFERENT keys on the same object, from the two different structs.
type SecretListEntry struct {
	Classification *string    `json:"Classification,omitempty"`
	CreatedAt      *time.Time `json:"CreatedAt,omitempty"`
	CreatedBy      *string    `json:"CreatedBy,omitempty"`
	Description    *string    `json:"Description,omitempty"`
	EnvironmentID  *int       `json:"EnvironmentID,omitempty"`
	Expiration     *time.Time `json:"Expiration"`
	ID             *int       `json:"ID,omitempty"`
	IsSecret       *bool      `json:"IsSecret,omitempty"`

	// IsShared From the embedded SecretNode. SecretWithSharingInfo's own is_shared field also exists on the wire, distinct from this one -- omitted here (oapi-codegen mangles snake_case to the same Go field name, IsShared, as this property, causing a real generation collision) since no CLI command reads it.
	IsShared        *bool      `json:"IsShared,omitempty"`
	MaxReads        *int       `json:"MaxReads"`
	Name            *string    `json:"Name,omitempty"`
	OwnerID         *int       `json:"OwnerID,omitempty"`
	ParentID        *int       `json:"ParentID"`
	ProjectID       *int       `json:"ProjectID,omitempty"`
	ReadCount       *int       `json:"ReadCount,omitempty"`
	Status          *string    `json:"Status,omitempty"`
	Type            *string    `json:"Type,omitempty"`
	UpdatedAt       *time.Time `json:"UpdatedAt,omitempty"`
	EnvironmentName *string    `json:"environment_name,omitempty"`
	IsOwnedByUser   *bool      `json:"is_owned_by_user,omitempty"`
	OwnerUsername   *string    `json:"owner_username,omitempty"`
	ProjectName     *string    `json:"project_name,omitempty"`
	ShareCount      *int       `json:"share_count,omitempty"`
	UserPermission  *string    `json:"user_permission,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Code    *int                    `json:"code,omitempty"`
	Details *map[string]interface{} `json:"details"`

	// Error Short error-type label, e.g. "NotFound", "BadRequest".
	Error   *string `json:"error,omitempty"`
	Message *string `json:"message,omitempty"`
	Success *bool   `json:"success,omitempty"`
}

// CreatePATJSONBody defines parameters for CreatePAT.
type CreatePATJSONBody struct {
	// AllowedCidrs Restrict the token to source IPs in these CIDRs. Omit/empty = no network restriction.
	AllowedCidrs *[]string `json:"allowed_cidrs,omitempty"`

	// EnvironmentScope ADR-042: confine the token to a single environment id; 0/omit = any environment. Env ids are globally unique, so this also pins the project.
	EnvironmentScope *int `json:"environment_scope,omitempty"`

	// ExpiresAt RFC3339; omit/null for non-expiring
	ExpiresAt *time.Time `json:"expires_at"`
	Name      string     `json:"name"`

	// ProjectScope ADR-042: confine the token to a single project id; 0/omit = any project the owner can reach.
	ProjectScope *int `json:"project_scope,omitempty"`

	// Scopes ADR-042 least-privilege allowlist (e.g. ["secrets.read"], supports "*" and "secrets.*"). Omit/empty = inherit the owner's full permissions. Only ever narrows below the owner.
	Scopes *[]string `json:"scopes,omitempty"`
}

// ListProjectsParams defines parameters for ListProjects.
type ListProjectsParams struct {
	// IncludeDeleted When 'true', also returns soft-deleted projects (each flagged via deleted/deleted_at) for the restore UI.
	IncludeDeleted *ListProjectsParamsIncludeDeleted `form:"include_deleted,omitempty" json:"include_deleted,omitempty"`
}

// ListProjectsParamsIncludeDeleted defines parameters for ListProjects.
type ListProjectsParamsIncludeDeleted string

// CreateProjectJSONBody defines parameters for CreateProject.
type CreateProjectJSONBody struct {
	Description *string `json:"description,omitempty"`

	// Environments Environment names to seed (default, if omitted: development, staging, production).
	Environments *[]string `json:"environments,omitempty"`
	Name         string    `json:"name"`
}

// ListProjectEnvironmentsParams defines parameters for ListProjectEnvironments.
type ListProjectEnvironmentsParams struct {
	// IncludeDeleted When 'true', also returns soft-deleted environments.
	IncludeDeleted *ListProjectEnvironmentsParamsIncludeDeleted `form:"include_deleted,omitempty" json:"include_deleted,omitempty"`
}

// ListProjectEnvironmentsParamsIncludeDeleted defines parameters for ListProjectEnvironments.
type ListProjectEnvironmentsParamsIncludeDeleted string

// CreateProjectEnvironmentJSONBody defines parameters for CreateProjectEnvironment.
type CreateProjectEnvironmentJSONBody struct {
	Name string `json:"name"`
}

// ListSecretsParams defines parameters for ListSecrets.
type ListSecretsParams struct {
	ProjectId     *int    `form:"project_id,omitempty" json:"project_id,omitempty"`
	EnvironmentId *int    `form:"environment_id,omitempty" json:"environment_id,omitempty"`
	Search        *string `form:"search,omitempty" json:"search,omitempty"`
	Type          *string `form:"type,omitempty" json:"type,omitempty"`

	// Classification Data-classification filter (A.5.12); 'unclassified' matches secrets with no label.
	Classification *ListSecretsParamsClassification `form:"classification,omitempty" json:"classification,omitempty"`

	// ExpiresBefore RFC3339 — return only secrets with a non-null expiration before this time (expired or expiring soon).
	ExpiresBefore  *time.Time `form:"expires_before,omitempty" json:"expires_before,omitempty"`
	Page           *int       `form:"page,omitempty" json:"page,omitempty"`
	PageSize       *int       `form:"page_size,omitempty" json:"page_size,omitempty"`
	ShowOwnedOnly  *bool      `form:"show_owned_only,omitempty" json:"show_owned_only,omitempty"`
	ShowSharedOnly *bool      `form:"show_shared_only,omitempty" json:"show_shared_only,omitempty"`
}

// ListSecretsParamsClassification defines parameters for ListSecrets.
type ListSecretsParamsClassification string

// CreateSecretJSONBody defines parameters for CreateSecret.
type CreateSecretJSONBody struct {
	// Classification Optional data-sensitivity label (A.5.12): public|internal|confidential|restricted.
	Classification *string `json:"classification,omitempty"`

	// Description Optional free-text note. Metadata only -- never the value. Fixed missing from this spec (ADR-108 PR 4) -- the real handler (secrets_crud.go's CreateSecret) has accepted this field since #1808, this spec just never documented it.
	Description   *string `json:"description,omitempty"`
	EnvironmentId int     `json:"environment_id"`

	// Expiration Optional RFC3339 expiration. Fixed missing from this spec (ADR-108 PR 4) -- same #1808 gap as description above.
	Expiration *time.Time         `json:"expiration,omitempty"`
	MaxReads   *int               `json:"max_reads"`
	Metadata   *map[string]string `json:"metadata,omitempty"`
	Name       string             `json:"name"`
	ProjectId  *int               `json:"project_id,omitempty"`
	Tags       *[]string          `json:"tags,omitempty"`
	Type       string             `json:"type"`
	Value      string             `json:"value"`
}

// GetSecretByNameParams defines parameters for GetSecretByName.
type GetSecretByNameParams struct {
	Name          string `form:"name" json:"name"`
	ProjectId     int    `form:"project_id" json:"project_id"`
	EnvironmentId int    `form:"environment_id" json:"environment_id"`
}

// GetSecretParams defines parameters for GetSecret.
type GetSecretParams struct {
	// IncludeValue When `true`, response `data` becomes `{secret, value}` with the decrypted value.
	IncludeValue *bool `form:"include_value,omitempty" json:"include_value,omitempty"`
}

// UpdateSecretJSONBody defines parameters for UpdateSecret.
type UpdateSecretJSONBody struct {
	ClearExpiration *bool      `json:"clear_expiration,omitempty"`
	Expiration      *time.Time `json:"expiration,omitempty"`
	MaxReads        *int       `json:"max_reads"`
	Value           *string    `json:"value,omitempty"`
}

// CreatePATJSONRequestBody defines body for CreatePAT for application/json ContentType.
type CreatePATJSONRequestBody CreatePATJSONBody

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody CreateProjectJSONBody

// CreateProjectEnvironmentJSONRequestBody defines body for CreateProjectEnvironment for application/json ContentType.
type CreateProjectEnvironmentJSONRequestBody CreateProjectEnvironmentJSONBody

// CreateSecretJSONRequestBody defines body for CreateSecret for application/json ContentType.
type CreateSecretJSONRequestBody CreateSecretJSONBody

// UpdateSecretJSONRequestBody defines body for UpdateSecret for application/json ContentType.
type UpdateSecretJSONRequestBody UpdateSecretJSONBody
