// Package apiclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package apiclient

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for AccessReviewDecisionPrincipalType.
const (
	AccessReviewDecisionPrincipalTypeGroup AccessReviewDecisionPrincipalType = "group"
	AccessReviewDecisionPrincipalTypeUser  AccessReviewDecisionPrincipalType = "user"
)

// Defines values for AccessReviewDecisionSource.
const (
	DirectShare AccessReviewDecisionSource = "direct_share"
	GroupShare  AccessReviewDecisionSource = "group_share"
	Role        AccessReviewDecisionSource = "role"
)

// Defines values for BreakGlassActivationState.
const (
	BreakGlassActivationStateActive  BreakGlassActivationState = "active"
	BreakGlassActivationStateExpired BreakGlassActivationState = "expired"
	BreakGlassActivationStateRevoked BreakGlassActivationState = "revoked"
)

// Defines values for DynamicSecretConfigBackendType.
const (
	AwsSts     DynamicSecretConfigBackendType = "aws-sts"
	Azure      DynamicSecretConfigBackendType = "azure"
	Gcp        DynamicSecretConfigBackendType = "gcp"
	Kubernetes DynamicSecretConfigBackendType = "kubernetes"
	Mongodb    DynamicSecretConfigBackendType = "mongodb"
	Mysql      DynamicSecretConfigBackendType = "mysql"
	Postgres   DynamicSecretConfigBackendType = "postgres"
	Redis      DynamicSecretConfigBackendType = "redis"
)

// Defines values for DynamicSecretLeaseStatus.
const (
	DynamicSecretLeaseStatusActive       DynamicSecretLeaseStatus = "active"
	DynamicSecretLeaseStatusExpired      DynamicSecretLeaseStatus = "expired"
	DynamicSecretLeaseStatusRevokeFailed DynamicSecretLeaseStatus = "revoke_failed"
	DynamicSecretLeaseStatusRevoked      DynamicSecretLeaseStatus = "revoked"
)

// Defines values for MachineIdentityState.
const (
	MachineIdentityStateActive    MachineIdentityState = "active"
	MachineIdentityStatePending   MachineIdentityState = "pending"
	MachineIdentityStateRevoked   MachineIdentityState = "revoked"
	MachineIdentityStateSuspended MachineIdentityState = "suspended"
)

// Defines values for PermissionMatrixRowScope.
const (
	PermissionMatrixRowScopeEnvironment PermissionMatrixRowScope = "environment"
	PermissionMatrixRowScopeGlobal      PermissionMatrixRowScope = "global"
	PermissionMatrixRowScopeProject     PermissionMatrixRowScope = "project"
)

// Defines values for ProjectInvitationState.
const (
	ProjectInvitationStateAccepted ProjectInvitationState = "accepted"
	ProjectInvitationStateExpired  ProjectInvitationState = "expired"
	ProjectInvitationStatePending  ProjectInvitationState = "pending"
	ProjectInvitationStateRevoked  ProjectInvitationState = "revoked"
)

// Defines values for ProvisionSetupResultChannel.
const (
	Log       ProvisionSetupResultChannel = "log"
	OutOfBand ProvisionSetupResultChannel = "out_of_band"
	Smtp      ProvisionSetupResultChannel = "smtp"
)

// Defines values for RotationPlanSecretStatus.
const (
	DueSoon RotationPlanSecretStatus = "due_soon"
	Overdue RotationPlanSecretStatus = "overdue"
)

// Defines values for RotationPolicyScope.
const (
	RotationPolicyScopeEnvironment RotationPolicyScope = "environment"
	RotationPolicyScopeProject     RotationPolicyScope = "project"
)

// Defines values for ListAuditLogsParamsActorType.
const (
	ListAuditLogsParamsActorTypeMachineIdentity ListAuditLogsParamsActorType = "machine_identity"
	ListAuditLogsParamsActorTypeSystem          ListAuditLogsParamsActorType = "system"
	ListAuditLogsParamsActorTypeUser            ListAuditLogsParamsActorType = "user"
)

// Defines values for MigrateAuditChainEncodingParamsDryRun.
const (
	MigrateAuditChainEncodingParamsDryRunFalse MigrateAuditChainEncodingParamsDryRun = "false"
	MigrateAuditChainEncodingParamsDryRunTrue  MigrateAuditChainEncodingParamsDryRun = "true"
)

// Defines values for SearchAuditLogsParamsSuccess.
const (
	SearchAuditLogsParamsSuccessFalse SearchAuditLogsParamsSuccess = "false"
	SearchAuditLogsParamsSuccessTrue  SearchAuditLogsParamsSuccess = "true"
)

// Defines values for CreateDynamicSecretConfigJSONBodyClassification.
const (
	CreateDynamicSecretConfigJSONBodyClassificationConfidential CreateDynamicSecretConfigJSONBodyClassification = "confidential"
	CreateDynamicSecretConfigJSONBodyClassificationEmpty        CreateDynamicSecretConfigJSONBodyClassification = ""
	CreateDynamicSecretConfigJSONBodyClassificationInternal     CreateDynamicSecretConfigJSONBodyClassification = "internal"
	CreateDynamicSecretConfigJSONBodyClassificationPublic       CreateDynamicSecretConfigJSONBodyClassification = "public"
	CreateDynamicSecretConfigJSONBodyClassificationRestricted   CreateDynamicSecretConfigJSONBodyClassification = "restricted"
)

// Defines values for ClassifyDynamicSecretConfigJSONBodyClassification.
const (
	ClassifyDynamicSecretConfigJSONBodyClassificationConfidential ClassifyDynamicSecretConfigJSONBodyClassification = "confidential"
	ClassifyDynamicSecretConfigJSONBodyClassificationEmpty        ClassifyDynamicSecretConfigJSONBodyClassification = ""
	ClassifyDynamicSecretConfigJSONBodyClassificationInternal     ClassifyDynamicSecretConfigJSONBodyClassification = "internal"
	ClassifyDynamicSecretConfigJSONBodyClassificationPublic       ClassifyDynamicSecretConfigJSONBodyClassification = "public"
	ClassifyDynamicSecretConfigJSONBodyClassificationRestricted   ClassifyDynamicSecretConfigJSONBodyClassification = "restricted"
)

// Defines values for ListProjectsParamsIncludeDeleted.
const (
	ListProjectsParamsIncludeDeletedFalse ListProjectsParamsIncludeDeleted = "false"
	ListProjectsParamsIncludeDeletedTrue  ListProjectsParamsIncludeDeleted = "true"
)

// Defines values for ResolveAccessRequestJSONBodyAction.
const (
	ResolveAccessRequestJSONBodyActionApprove ResolveAccessRequestJSONBodyAction = "approve"
	ResolveAccessRequestJSONBodyActionReject  ResolveAccessRequestJSONBodyAction = "reject"
)

// Defines values for DecideAccessReviewCampaignItemJSONBodyAction.
const (
	DecideAccessReviewCampaignItemJSONBodyActionAttest DecideAccessReviewCampaignItemJSONBodyAction = "attest"
	DecideAccessReviewCampaignItemJSONBodyActionRevoke DecideAccessReviewCampaignItemJSONBodyAction = "revoke"
)

// Defines values for ListProjectEnvironmentsParamsIncludeDeleted.
const (
	ListProjectEnvironmentsParamsIncludeDeletedFalse ListProjectEnvironmentsParamsIncludeDeleted = "false"
	ListProjectEnvironmentsParamsIncludeDeletedTrue  ListProjectEnvironmentsParamsIncludeDeleted = "true"
)

// Defines values for TransitionMachineIdentityJSONBodyAction.
const (
	TransitionMachineIdentityJSONBodyActionActivate TransitionMachineIdentityJSONBodyAction = "activate"
	TransitionMachineIdentityJSONBodyActionRevoke   TransitionMachineIdentityJSONBodyAction = "revoke"
	TransitionMachineIdentityJSONBodyActionSuspend  TransitionMachineIdentityJSONBodyAction = "suspend"
)

// Defines values for GetPermissionMatrixParamsFormat.
const (
	Csv GetPermissionMatrixParamsFormat = "csv"
)

// Defines values for CreateRotationPolicyJSONBodyScope.
const (
	CreateRotationPolicyJSONBodyScopeEnvironment CreateRotationPolicyJSONBodyScope = "environment"
	CreateRotationPolicyJSONBodyScopeProject     CreateRotationPolicyJSONBodyScope = "project"
)

// Defines values for ResolveSecretAccessRequestJSONBodyAction.
const (
	ResolveSecretAccessRequestJSONBodyActionApprove ResolveSecretAccessRequestJSONBodyAction = "approve"
	ResolveSecretAccessRequestJSONBodyActionReject  ResolveSecretAccessRequestJSONBodyAction = "reject"
)

// Defines values for ListUsersParamsFilter.
const (
	Inactive ListUsersParamsFilter = "inactive"
)

// AccessReviewDecision Identifies one access-review entry for a recertification decision (attest or revoke). Mirrors an entry from GET .../access-review.
type AccessReviewDecision struct {
	// EnvironmentId Environment scope of a role grant (0 = whole project).
	EnvironmentId *uint32 `json:"environment_id,omitempty"`

	// PrincipalId The user or group ID the grant is for.
	PrincipalId *uint32 `json:"principal_id,omitempty"`

	// PrincipalType For a role grant, whether the principal is a user or a group.
	PrincipalType *AccessReviewDecisionPrincipalType `json:"principal_type,omitempty"`

	// RoleId Required when source=role.
	RoleId *uint32 `json:"role_id,omitempty"`

	// SecretId Required when source=direct_share or group_share.
	SecretId *uint32 `json:"secret_id,omitempty"`

	// Source Which mechanism conferred the grant.
	Source AccessReviewDecisionSource `json:"source"`
}

// AccessReviewDecisionPrincipalType For a role grant, whether the principal is a user or a group.
type AccessReviewDecisionPrincipalType string

// AccessReviewDecisionSource Which mechanism conferred the grant.
type AccessReviewDecisionSource string

// BreakGlassActivation One emergency-access self-grant (ADR-108 PR 1 addition).
type BreakGlassActivation struct {
	CreatedAt     *string                    `json:"created_at,omitempty"`
	ExpiresAt     *string                    `json:"expires_at,omitempty"`
	Id            *uint32                    `json:"id,omitempty"`
	Justification *string                    `json:"justification,omitempty"`
	RoleName      *string                    `json:"role_name,omitempty"`
	State         *BreakGlassActivationState `json:"state,omitempty"`
	UserId        *uint32                    `json:"user_id,omitempty"`
}

// BreakGlassActivationState defines model for BreakGlassActivation.State.
type BreakGlassActivationState string

// DeploymentRotationPlan The install-wide roll-up of every project's rotation plan (ADR-108 PR 1 addition, ADR-053) -- a roll-up of per-project plans, most pressing first.
type DeploymentRotationPlan struct {
	DueSoonCount     *int            `json:"due_soon_count,omitempty"`
	OverdueCount     *int            `json:"overdue_count,omitempty"`
	Projects         *[]RotationPlan `json:"projects,omitempty"`
	ProjectsScanned  *int            `json:"projects_scanned,omitempty"`
	ProjectsWithWork *int            `json:"projects_with_work,omitempty"`
	TotalSecrets     *int            `json:"total_secrets,omitempty"`
}

// DynamicSecretConfig A registered dynamic-secret target config (ADR-108 PR 1 addition).
type DynamicSecretConfig struct {
	BackendType       *DynamicSecretConfigBackendType `json:"backend_type,omitempty"`
	Classification    *string                         `json:"classification,omitempty"`
	DefaultTtlSeconds *int                            `json:"default_ttl_seconds,omitempty"`
	EnvironmentId     *uint32                         `json:"environment_id,omitempty"`
	Id                *uint32                         `json:"id,omitempty"`
	MaxTtlSeconds     *int                            `json:"max_ttl_seconds,omitempty"`
	Name              *string                         `json:"name,omitempty"`
	ProjectId         *uint32                         `json:"project_id,omitempty"`
}

// DynamicSecretConfigBackendType defines model for DynamicSecretConfig.BackendType.
type DynamicSecretConfigBackendType string

// DynamicSecretIssuedLease A freshly-issued dynamic-secret credential, shown once (ADR-108 PR 1 addition). username/password are populated for DB/cache backends; fields carries arbitrary key/value pairs for cloud-IAM backends (AWS STS, GCP, Azure, Kubernetes) instead.
type DynamicSecretIssuedLease struct {
	ExpiresAt *string            `json:"expires_at,omitempty"`
	Fields    *map[string]string `json:"fields,omitempty"`
	LeaseId   *string            `json:"lease_id,omitempty"`
	Password  *string            `json:"password,omitempty"`
	Username  *string            `json:"username,omitempty"`
}

// DynamicSecretLease A dynamic-secret lease summary (ADR-108 PR 1 addition).
type DynamicSecretLease struct {
	ExpiresAt *string                   `json:"expires_at,omitempty"`
	IssuedAt  *string                   `json:"issued_at,omitempty"`
	LeaseId   *string                   `json:"lease_id,omitempty"`
	RoleName  *string                   `json:"role_name,omitempty"`
	Status    *DynamicSecretLeaseStatus `json:"status,omitempty"`
}

// DynamicSecretLeaseStatus defines model for DynamicSecretLease.Status.
type DynamicSecretLeaseStatus string

// Environment A project environment (internal/storage/models.Environment). No `json:` tags on the model -- wire keys are the bare Go field names (ID, ProjectID, Name, CreatedAt, UpdatedAt), not snake_case. Unlike Permission/RoleWithPermissions above, ProjectID/CreatedAt/UpdatedAt do NOT case-insensitively match a snake_case tag (the underscore makes "project_id" a different string from "projectid"), so a generated client MUST use these exact capitalized property names to decode correctly.
type Environment struct {
	CreatedAt *time.Time `json:"CreatedAt,omitempty"`
	ID        *int       `json:"ID,omitempty"`
	Name      *string    `json:"Name,omitempty"`
	ProjectID *int       `json:"ProjectID,omitempty"`
	UpdatedAt *time.Time `json:"UpdatedAt,omitempty"`
}

// Group A group (server/http/handlers/groups_handler.go's groupToAPIResponse).
type Group struct {
	Description *string `json:"description,omitempty"`
	Id          *int    `json:"id,omitempty"`
	Name        *string `json:"name,omitempty"`
}

// GroupRoleGrant One role a group holds, with its time-bound expiry if any (internal/core/storage.GroupRoleGrant).
type GroupRoleGrant struct {
	Description *string    `json:"description,omitempty"`
	ExpiresAt   *time.Time `json:"expires_at"`
	Id          *int       `json:"id,omitempty"`
	Name        *string    `json:"name,omitempty"`
}

// MachineAuditReport Deployment-wide machine identity audit report (GET /machine-identities/audit).
type MachineAuditReport struct {
	GeneratedAt  *time.Time         `json:"generated_at,omitempty"`
	Machines     *[]MachineAuditRow `json:"machines,omitempty"`
	RevokedCount *int               `json:"revoked_count,omitempty"`
	StaleCount   *int               `json:"stale_count,omitempty"`
	TotalCount   *int               `json:"total_count,omitempty"`
}

// MachineAuditRow defines model for MachineAuditRow.
type MachineAuditRow struct {
	CreatedAt       *time.Time `json:"created_at,omitempty"`
	CredentialCount *int       `json:"credential_count,omitempty"`
	Description     *string    `json:"description,omitempty"`
	IsRevoked       *bool      `json:"is_revoked,omitempty"`
	IsStale         *bool      `json:"is_stale,omitempty"`
	LastUsedAt      *time.Time `json:"last_used_at,omitempty"`
	MachineId       *int       `json:"machine_id,omitempty"`
	Name            *string    `json:"name,omitempty"`
}

// MachineIdentity A project-scoped machine identity (ADR-023).
type MachineIdentity struct {
	Classification             *string               `json:"classification,omitempty"`
	CreatedAt                  *time.Time            `json:"created_at,omitempty"`
	CreatedBy                  *int                  `json:"created_by,omitempty"`
	CreatedByMachineIdentityId *int                  `json:"created_by_machine_identity_id,omitempty"`
	Description                *string               `json:"description,omitempty"`
	Id                         *int                  `json:"id,omitempty"`
	IdentityType               *string               `json:"identity_type,omitempty"`
	LastSeenAt                 *time.Time            `json:"last_seen_at"`
	Name                       *string               `json:"name,omitempty"`
	ProjectId                  *int                  `json:"project_id,omitempty"`
	RevokedAt                  *time.Time            `json:"revoked_at"`
	State                      *MachineIdentityState `json:"state,omitempty"`
	UpdatedAt                  *time.Time            `json:"updated_at,omitempty"`
}

// MachineIdentityState defines model for MachineIdentity.State.
type MachineIdentityState string

// MachineToken Machine identity token metadata (never the raw secret, except once at issuance).
type MachineToken struct {
	ExpiresAt  *time.Time `json:"expires_at"`
	Id         *int       `json:"id,omitempty"`
	LastUsedAt *time.Time `json:"last_used_at"`
	Name       *string    `json:"name,omitempty"`
	Prefix     *string    `json:"prefix,omitempty"`
	Revoked    *bool      `json:"revoked,omitempty"`
}

// MachineTokenHygieneRow A deployment-wide machine-token hygiene entry (GET /machine-token-hygiene) -- never includes the token secret.
type MachineTokenHygieneRow struct {
	Expired           *bool   `json:"expired,omitempty"`
	Id                *int    `json:"id,omitempty"`
	LastUsedAt        *string `json:"last_used_at,omitempty"`
	MachineIdentityId *int    `json:"machine_identity_id,omitempty"`
	Name              *string `json:"name,omitempty"`
	Stale             *bool   `json:"stale,omitempty"`
	TokenPrefix       *string `json:"token_prefix,omitempty"`
}

// OIDCBinding An OIDC federation binding (ADR-031) mapping an external (issuer, subject) to a machine identity.
type OIDCBinding struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Id        *int       `json:"id,omitempty"`
	Issuer    *string    `json:"issuer,omitempty"`
	Subject   *string    `json:"subject,omitempty"`
}

// PATHygieneRow A deployment-wide PAT hygiene entry (GET /pat-hygiene) -- never includes the token secret.
type PATHygieneRow struct {
	Expired     *bool   `json:"expired,omitempty"`
	ExpiresAt   *string `json:"expires_at,omitempty"`
	Id          *int    `json:"id,omitempty"`
	LastUsedAt  *string `json:"last_used_at,omitempty"`
	Name        *string `json:"name,omitempty"`
	Stale       *bool   `json:"stale,omitempty"`
	TokenPrefix *string `json:"token_prefix,omitempty"`
	UserId      *int    `json:"user_id,omitempty"`
}

// PATToken A personal access token (ADR-027/ADR-042). The raw secret is never returned except once, in the create response.
type PATToken struct {
	AllowedCidrs     *[]string  `json:"allowed_cidrs"`
	CreatedAt        *time.Time `json:"created_at,omitempty"`
	EnvironmentScope *int       `json:"environment_scope,omitempty"`
	ExpiresAt        *time.Time `json:"expires_at"`
	Id               *int       `json:"id,omitempty"`
	LastUsedAt       *time.Time `json:"last_used_at"`
	Name             *string    `json:"name,omitempty"`
	ProjectScope     *int       `json:"project_scope,omitempty"`
	Revoked          *bool      `json:"revoked,omitempty"`
	Scopes           *[]string  `json:"scopes"`
	TokenPrefix      *string    `json:"token_prefix,omitempty"`
}

// Permission A permission. internal/storage/models.Permission carries no `json:` tags, so the wire keys are the bare (capitalized) Go field names, not the snake_case this file uses elsewhere -- documented as such rather than as an idealized snake_case shape it does not actually have. Single-word field names still decode correctly into a snake_case-tagged Go client: encoding/json's Unmarshal falls back to a case-insensitive match ("ID" ~ "id") when no exact tag match exists.
type Permission struct {
	Action      *string `json:"Action,omitempty"`
	Description *string `json:"Description,omitempty"`
	ID          *int    `json:"ID,omitempty"`
	Name        *string `json:"Name,omitempty"`
	Resource    *string `json:"Resource,omitempty"`
}

// PermissionMatrixRow One (user, role, permission, scope) tuple (internal/core.PermissionMatrixRow), GET /api/v1/rbac/permission-matrix.
type PermissionMatrixRow struct {
	Action          *string                   `json:"action,omitempty"`
	Email           *string                   `json:"email,omitempty"`
	EnvironmentId   *int                      `json:"environment_id,omitempty"`
	EnvironmentName *string                   `json:"environment_name,omitempty"`
	ExpiresAt       *time.Time                `json:"expires_at"`
	PermissionName  *string                   `json:"permission_name,omitempty"`
	ProjectId       *int                      `json:"project_id,omitempty"`
	ProjectName     *string                   `json:"project_name,omitempty"`
	Resource        *string                   `json:"resource,omitempty"`
	RoleId          *int                      `json:"role_id,omitempty"`
	RoleName        *string                   `json:"role_name,omitempty"`
	Scope           *PermissionMatrixRowScope `json:"scope,omitempty"`
	UserId          *int                      `json:"user_id,omitempty"`
	Username        *string                   `json:"username,omitempty"`
}

// PermissionMatrixRowScope defines model for PermissionMatrixRow.Scope.
type PermissionMatrixRowScope string

// ProjectInvitation A project invitation (ADR-024, internal/storage/models.ProjectInvitation). No `json:` tags on the model -- wire keys are the bare Go field names (ID, ProjectID, Email, ...), not snake_case. As with Environment above, the multi-word field names here do not case-insensitively match a snake_case tag, so a generated client must use these exact property names.
type ProjectInvitation struct {
	AcceptedAt                 *time.Time              `json:"AcceptedAt"`
	CreatedAt                  *time.Time              `json:"CreatedAt,omitempty"`
	Email                      *string                 `json:"Email,omitempty"`
	ExpiresAt                  *time.Time              `json:"ExpiresAt"`
	ID                         *int                    `json:"ID,omitempty"`
	InvitedBy                  *int                    `json:"InvitedBy,omitempty"`
	InvitedByMachineIdentityID *int                    `json:"InvitedByMachineIdentityID,omitempty"`
	ProjectID                  *int                    `json:"ProjectID,omitempty"`
	RevokedAt                  *time.Time              `json:"RevokedAt"`
	Role                       *string                 `json:"Role,omitempty"`
	State                      *ProjectInvitationState `json:"State,omitempty"`
	SystemRole                 *string                 `json:"SystemRole,omitempty"`
}

// ProjectInvitationState defines model for ProjectInvitation.State.
type ProjectInvitationState string

// ProvisionSetupResult Outcome of provisioning and delivering a setup/accept link (ADR-028, internal/core.ProvisionSetupResult).
type ProvisionSetupResult struct {
	Channel   *ProvisionSetupResultChannel `json:"channel,omitempty"`
	Delivered *bool                        `json:"delivered,omitempty"`
	Email     *string                      `json:"email,omitempty"`

	// LinkForAdmin Set only in out-of-band mode.
	LinkForAdmin *string `json:"link_for_admin,omitempty"`
}

// ProvisionSetupResultChannel defines model for ProvisionSetupResult.Channel.
type ProvisionSetupResultChannel string

// RBACAuditLogEntry One RBAC audit trail entry (GET /api/v1/audit/rbac-logs).
type RBACAuditLogEntry struct {
	Action        *string    `json:"action,omitempty"`
	ActorUserId   *int       `json:"actor_user_id"`
	CreatedAt     *time.Time `json:"created_at,omitempty"`
	Details       *string    `json:"details,omitempty"`
	EnvironmentId *int       `json:"environment_id"`
	GroupId       *int       `json:"group_id"`
	Id            *int       `json:"id,omitempty"`
	PermissionId  *int       `json:"permission_id"`
	ProjectId     *int       `json:"project_id"`
	RoleId        *int       `json:"role_id"`
	TargetUserId  *int       `json:"target_user_id"`
}

// RoleRef A minimal role reference (id, name only) -- GET /api/v1/users/{id}/roles's shape.
type RoleRef struct {
	Id   *int    `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

// RoleWithPermissions A role with its assigned permissions (internal/core.RoleWithPermissions, embeds models.Role). Same untagged-model caveat as Permission above: wire keys are the bare Go field names (ID, Name, Description, BypassesPermissionChecks, Permissions), not snake_case.
type RoleWithPermissions struct {
	BypassesPermissionChecks *bool         `json:"BypassesPermissionChecks,omitempty"`
	Description              *string       `json:"Description,omitempty"`
	ID                       *int          `json:"ID,omitempty"`
	Name                     *string       `json:"Name,omitempty"`
	Permissions              *[]Permission `json:"Permissions,omitempty"`
}

// RotationOrder A safe rotation sequence for a project's secret dependency graph (ADR-108 PR 1 addition, ADR-052): each secret is listed before anything that depends on it.
type RotationOrder struct {
	Order     *[]RotationOrderStep `json:"order,omitempty"`
	ProjectId *uint32              `json:"project_id,omitempty"`
}

// RotationOrderStep One secret in a project's safe rotation sequence (ADR-052).
type RotationOrderStep struct {
	SecretId   *uint32 `json:"secret_id,omitempty"`
	SecretName *string `json:"secret_name,omitempty"`
}

// RotationPlan A project's automated rotation plan (ADR-108 PR 1 addition, ADR-053).
type RotationPlan struct {
	DueSoonCount *int                `json:"due_soon_count,omitempty"`
	OverdueCount *int                `json:"overdue_count,omitempty"`
	ProjectId    *uint32             `json:"project_id,omitempty"`
	TotalSecrets *int                `json:"total_secrets,omitempty"`
	Waves        *[]RotationPlanWave `json:"waves,omitempty"`
}

// RotationPlanSecret One secret entry in a rotation-plan wave (ADR-108 PR 1 addition, ADR-053).
type RotationPlanSecret struct {
	AutoRotate  *bool                     `json:"auto_rotate,omitempty"`
	DaysOverdue *int                      `json:"days_overdue,omitempty"`
	Reasons     *[]string                 `json:"reasons,omitempty"`
	RiskBand    *string                   `json:"risk_band,omitempty"`
	SecretId    *uint32                   `json:"secret_id,omitempty"`
	SecretName  *string                   `json:"secret_name,omitempty"`
	Status      *RotationPlanSecretStatus `json:"status,omitempty"`
}

// RotationPlanSecretStatus defines model for RotationPlanSecret.Status.
type RotationPlanSecretStatus string

// RotationPlanWave A dependency-safe batch of secrets to rotate together (ADR-053).
type RotationPlanWave struct {
	Index   *int                  `json:"index,omitempty"`
	Secrets *[]RotationPlanSecret `json:"secrets,omitempty"`
}

// RotationPolicy A secret-rotation policy (ADR-108 PR 1 addition). Snake_case, matching this spec's usual convention and the model's real wire format: models.RotationPolicy (internal/storage/models/models.go) previously had no `json:` tags on most fields, so encoding/json's default marshaling emitted the bare Go field names verbatim (ID, Name, ProjectID, IntervalDays, ...) instead -- a PascalCase wire format silently decoded by any snake_case-tagged consumer (Go's case-insensitive JSON fallback matches "ID"~"id" but not "ProjectID"~"project_id", an extra underscore is not a case difference) as the zero value for every multi-word field. Fixed at the source (the model itself now carries these exact tags) rather than documented here as a PascalCase exception -- see the model's own doc comment for the full writeup, and docs/cli-split-inventory.md §7 PR 1's closure note for how this was found.
type RotationPolicy struct {
	AlertDaysBefore *int                 `json:"alert_days_before,omitempty"`
	CreatedBy       *string              `json:"created_by,omitempty"`
	Description     *string              `json:"description,omitempty"`
	EnvironmentId   *uint32              `json:"environment_id"`
	Id              *uint32              `json:"id,omitempty"`
	IntervalDays    *int                 `json:"interval_days,omitempty"`
	IsActive        *bool                `json:"is_active,omitempty"`
	Name            *string              `json:"name,omitempty"`
	NotifyOnBreach  *bool                `json:"notify_on_breach,omitempty"`
	ProjectId       *uint32              `json:"project_id"`
	Scope           *RotationPolicyScope `json:"scope,omitempty"`
}

// RotationPolicyScope defines model for RotationPolicy.Scope.
type RotationPolicyScope string

// RotationPolicyEvaluation One policy-covered secret's rotation posture, as returned by GET /api/v1/rotation-policies/evaluate (ADR-108 PR 1 addition).
type RotationPolicyEvaluation struct {
	DaysOverdue   *int    `json:"days_overdue,omitempty"`
	IsApproaching *bool   `json:"is_approaching,omitempty"`
	IsOverdue     *bool   `json:"is_overdue,omitempty"`
	PolicyName    *string `json:"policy_name,omitempty"`
	ProjectId     *uint32 `json:"project_id,omitempty"`
	SecretId      *uint32 `json:"secret_id,omitempty"`
	SecretName    *string `json:"secret_name,omitempty"`
}

// UserSummary A user as returned in list/membership contexts (userToAPIResponse, server/http/handlers/users_handler.go). project_count/active_project_count are attached only by GET /api/v1/users (listUsers), not by GET /api/v1/groups/{id}/members.
type UserSummary struct {
	AccountState       *string    `json:"account_state,omitempty"`
	Active             *bool      `json:"active,omitempty"`
	ActiveProjectCount *int       `json:"active_project_count,omitempty"`
	CreatedAt          *time.Time `json:"created_at,omitempty"`
	DeletedAt          *time.Time `json:"deleted_at"`
	DisplayName        *string    `json:"display_name,omitempty"`
	Email              *string    `json:"email,omitempty"`
	ExternalId         *string    `json:"external_id,omitempty"`
	Id                 *int       `json:"id,omitempty"`
	LastLoginAt        *time.Time `json:"last_login_at"`
	ProjectCount       *int       `json:"project_count,omitempty"`
	UpdatedAt          *time.Time `json:"updated_at,omitempty"`
	Username           *string    `json:"username,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Code    *int                    `json:"code,omitempty"`
	Details *map[string]interface{} `json:"details"`

	// Error Short error-type label, e.g. "NotFound", "BadRequest".
	Error   *string `json:"error,omitempty"`
	Message *string `json:"message,omitempty"`
	Success *bool   `json:"success,omitempty"`
}

// BulkApproveAccessRequestsJSONBody defines parameters for BulkApproveAccessRequests.
type BulkApproveAccessRequestsJSONBody struct {
	RequestIds []int `json:"request_ids"`
}

// BulkRejectAccessRequestsJSONBody defines parameters for BulkRejectAccessRequests.
type BulkRejectAccessRequestsJSONBody struct {
	Reason     string `json:"reason"`
	RequestIds []int  `json:"request_ids"`
}

// UpdateAnomalyConfigJSONBody defines parameters for UpdateAnomalyConfig.
type UpdateAnomalyConfigJSONBody struct {
	LookbackDays     *int     `json:"lookback_days,omitempty"`
	MlEnabled        *bool    `json:"ml_enabled,omitempty"`
	MlNumTrees       *int     `json:"ml_num_trees,omitempty"`
	MlSampleSize     *int     `json:"ml_sample_size,omitempty"`
	MlThreshold      *float32 `json:"ml_threshold,omitempty"`
	OffHoursEnabled  *bool    `json:"off_hours_enabled,omitempty"`
	OffHoursEnd      *int     `json:"off_hours_end,omitempty"`
	OffHoursStart    *int     `json:"off_hours_start,omitempty"`
	OffHoursTimezone *string  `json:"off_hours_timezone,omitempty"`
	QuarantineHours  *int     `json:"quarantine_hours,omitempty"`
}

// CreateAlertEscalationPolicyJSONBody defines parameters for CreateAlertEscalationPolicy.
type CreateAlertEscalationPolicyJSONBody struct {
	// ChannelIds Comma-separated NotificationChannel IDs.
	ChannelIds           *string `json:"channel_ids,omitempty"`
	Enabled              *bool   `json:"enabled,omitempty"`
	EscalateAfterMinutes *int    `json:"escalate_after_minutes,omitempty"`

	// MinSeverity low | medium | high | critical
	MinSeverity *string `json:"min_severity,omitempty"`
	Name        string  `json:"name"`
}

// ListAnomalyAlertsParams defines parameters for ListAnomalyAlerts.
type ListAnomalyAlertsParams struct {
	// Acknowledged Filter by acknowledged state; omit to return all.
	Acknowledged *bool `form:"acknowledged,omitempty" json:"acknowledged,omitempty"`

	// Unacknowledged Legacy alias (CLI) — true returns only unacknowledged alerts.
	Unacknowledged *bool `form:"unacknowledged,omitempty" json:"unacknowledged,omitempty"`
}

// ExportAuditLogsParams defines parameters for ExportAuditLogs.
type ExportAuditLogsParams struct {
	// AfterId Cursor — pass the last returned event id to fetch the next page.
	AfterId *int `form:"after_id,omitempty" json:"after_id,omitempty"`

	// Since RFC3339 lower bound on event time.
	Since *time.Time `form:"since,omitempty" json:"since,omitempty"`
	Limit *int       `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListAuditLogsParams defines parameters for ListAuditLogs.
type ListAuditLogsParams struct {
	// Action Filter by event type/action.
	Action *string `form:"action,omitempty" json:"action,omitempty"`

	// UserId Filter by acting user ID.
	UserId *int `form:"user_id,omitempty" json:"user_id,omitempty"`

	// ProjectId Filter by project ID.
	ProjectId *int `form:"project_id,omitempty" json:"project_id,omitempty"`

	// ActorType Segment human vs machine activity (ADR-023).
	ActorType *ListAuditLogsParamsActorType `form:"actor_type,omitempty" json:"actor_type,omitempty"`

	// StartTime RFC3339 lower bound (inclusive).
	StartTime *time.Time `form:"start_time,omitempty" json:"start_time,omitempty"`

	// EndTime RFC3339 upper bound (inclusive).
	EndTime  *time.Time `form:"end_time,omitempty" json:"end_time,omitempty"`
	Page     *int       `form:"page,omitempty" json:"page,omitempty"`
	PageSize *int       `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// ListAuditLogsParamsActorType defines parameters for ListAuditLogs.
type ListAuditLogsParamsActorType string

// MigrateAuditChainEncodingParams defines parameters for MigrateAuditChainEncoding.
type MigrateAuditChainEncodingParams struct {
	// DryRun false applies the migration for real; true (default) only previews.
	DryRun *MigrateAuditChainEncodingParamsDryRun `form:"dry_run,omitempty" json:"dry_run,omitempty"`
}

// MigrateAuditChainEncodingParamsDryRun defines parameters for MigrateAuditChainEncoding.
type MigrateAuditChainEncodingParamsDryRun string

// ListRBACAuditLogsParams defines parameters for ListRBACAuditLogs.
type ListRBACAuditLogsParams struct {
	Page     *int `form:"page,omitempty" json:"page,omitempty"`
	PageSize *int `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// SearchAuditLogsParams defines parameters for SearchAuditLogs.
type SearchAuditLogsParams struct {
	// Actor Partial username match on the acting principal.
	Actor *string `form:"actor,omitempty" json:"actor,omitempty"`

	// UserId Exact numeric user ID.
	UserId *int `form:"user_id,omitempty" json:"user_id,omitempty"`

	// ProjectId Exact project ID.
	ProjectId *int `form:"project_id,omitempty" json:"project_id,omitempty"`

	// Action Exact event_type (e.g. secret.read).
	Action *string `form:"action,omitempty" json:"action,omitempty"`

	// ResourceType Resource kind prefix (e.g. secret).
	ResourceType *string `form:"resource_type,omitempty" json:"resource_type,omitempty"`

	// ResourceId Exact secret_node_id.
	ResourceId *int `form:"resource_id,omitempty" json:"resource_id,omitempty"`

	// Ip Exact originating IP address.
	Ip *string `form:"ip,omitempty" json:"ip,omitempty"`

	// Success Filter by operation success/failure.
	Success *SearchAuditLogsParamsSuccess `form:"success,omitempty" json:"success,omitempty"`

	// Since RFC3339 start of time range (inclusive).
	Since *time.Time `form:"since,omitempty" json:"since,omitempty"`

	// Until RFC3339 end of time range (inclusive).
	Until *time.Time `form:"until,omitempty" json:"until,omitempty"`

	// Limit Maximum results.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Pagination offset.
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// SearchAuditLogsParamsSuccess defines parameters for SearchAuditLogs.
type SearchAuditLogsParamsSuccess string

// MfaStepUpJSONBody defines parameters for MfaStepUp.
type MfaStepUpJSONBody struct {
	// Code TOTP code or a recovery code
	Code string `json:"code"`
}

// UpdateAuthProfileJSONBody defines parameters for UpdateAuthProfile.
type UpdateAuthProfileJSONBody struct {
	DisplayName *string              `json:"display_name,omitempty"`
	Email       *openapi_types.Email `json:"email,omitempty"`
}

// CreatePATJSONBody defines parameters for CreatePAT.
type CreatePATJSONBody struct {
	// AllowedCidrs Restrict the token to source IPs in these CIDRs. Omit/empty = no network restriction.
	AllowedCidrs *[]string `json:"allowed_cidrs,omitempty"`

	// EnvironmentScope ADR-042: confine the token to a single environment id; 0/omit = any environment. Env ids are globally unique, so this also pins the project.
	EnvironmentScope *int `json:"environment_scope,omitempty"`

	// ExpiresAt RFC3339; omit/null for non-expiring
	ExpiresAt *time.Time `json:"expires_at"`
	Name      string     `json:"name"`

	// ProjectScope ADR-042: confine the token to a single project id; 0/omit = any project the owner can reach.
	ProjectScope *int `json:"project_scope,omitempty"`

	// Scopes ADR-042 least-privilege allowlist (e.g. ["secrets.read"], supports "*" and "secrets.*"). Omit/empty = inherit the owner's full permissions. Only ever narrows below the owner.
	Scopes *[]string `json:"scopes,omitempty"`
}

// ListDynamicSecretConfigsParams defines parameters for ListDynamicSecretConfigs.
type ListDynamicSecretConfigsParams struct {
	ProjectId     *int `form:"project_id,omitempty" json:"project_id,omitempty"`
	EnvironmentId *int `form:"environment_id,omitempty" json:"environment_id,omitempty"`
}

// CreateDynamicSecretConfigJSONBody defines parameters for CreateDynamicSecretConfig.
type CreateDynamicSecretConfigJSONBody struct {
	// AdminDsn Plaintext admin DSN; encrypted at rest, never echoed back
	AdminDsn          string                                           `json:"admin_dsn"`
	BackendType       string                                           `json:"backend_type"`
	Classification    *CreateDynamicSecretConfigJSONBodyClassification `json:"classification,omitempty"`
	CreationTemplate  string                                           `json:"creation_template"`
	DefaultTtlSeconds *int                                             `json:"default_ttl_seconds,omitempty"`
	EnvironmentId     int                                              `json:"environment_id"`
	MaxActiveLeases   *int                                             `json:"max_active_leases,omitempty"`
	MaxTtlSeconds     *int                                             `json:"max_ttl_seconds,omitempty"`
	Name              string                                           `json:"name"`
	ProjectId         int                                              `json:"project_id"`
}

// CreateDynamicSecretConfigJSONBodyClassification defines parameters for CreateDynamicSecretConfig.
type CreateDynamicSecretConfigJSONBodyClassification string

// ClassifyDynamicSecretConfigJSONBody defines parameters for ClassifyDynamicSecretConfig.
type ClassifyDynamicSecretConfigJSONBody struct {
	Classification *ClassifyDynamicSecretConfigJSONBodyClassification `json:"classification,omitempty"`
}

// ClassifyDynamicSecretConfigJSONBodyClassification defines parameters for ClassifyDynamicSecretConfig.
type ClassifyDynamicSecretConfigJSONBodyClassification string

// IssueDynamicSecretLeaseJSONBody defines parameters for IssueDynamicSecretLease.
type IssueDynamicSecretLeaseJSONBody struct {
	TtlSeconds *int `json:"ttl_seconds,omitempty"`
}

// RenewDynamicSecretLeaseJSONBody defines parameters for RenewDynamicSecretLease.
type RenewDynamicSecretLeaseJSONBody struct {
	TtlSeconds *int `json:"ttl_seconds,omitempty"`
}

// CreateGroupJSONBody defines parameters for CreateGroup.
type CreateGroupJSONBody struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// UpdateGroupJSONBody defines parameters for UpdateGroup.
type UpdateGroupJSONBody struct {
	Description *string `json:"description,omitempty"`
	Name        *string `json:"name,omitempty"`
}

// AddGroupMemberJSONBody defines parameters for AddGroupMember.
type AddGroupMemberJSONBody struct {
	// ProjectId 0 = global membership (default); non-zero = scoped to that project only.
	ProjectId *int `json:"project_id,omitempty"`
	UserId    int  `json:"user_id"`
}

// RemoveGroupMemberParams defines parameters for RemoveGroupMember.
type RemoveGroupMemberParams struct {
	// ProjectId Scope to the same project the membership was added with (0/omit = global membership). Fixed missing from this spec (ADR-108 PR 3) -- the real handler (groups_members.go's RemoveGroupMember) has always read this query param; every other caller sent it, this spec just never documented it.
	ProjectId *int `form:"project_id,omitempty" json:"project_id,omitempty"`
}

// AssignRoleToGroupJSONBody defines parameters for AssignRoleToGroup.
type AssignRoleToGroupJSONBody struct {
	// EnvironmentId Scope (0 = global).
	EnvironmentId *int `json:"environment_id,omitempty"`

	// ExpiresAt RFC3339; omit or null for a non-expiring grant. JIT access — the assignment is automatically revoked when the timestamp is reached.
	ExpiresAt *time.Time `json:"expires_at"`

	// ProjectId Scope (0 = global).
	ProjectId *int `json:"project_id,omitempty"`
	RoleId    int  `json:"role_id"`
}

// RemoveRoleFromGroupParams defines parameters for RemoveRoleFromGroup.
type RemoveRoleFromGroupParams struct {
	// ProjectId Scope (0 = global).
	ProjectId *int `form:"project_id,omitempty" json:"project_id,omitempty"`

	// EnvironmentId Scope (0 = global).
	EnvironmentId *int `form:"environment_id,omitempty" json:"environment_id,omitempty"`
}

// MachineTokenHygieneParams defines parameters for MachineTokenHygiene.
type MachineTokenHygieneParams struct {
	// Days Staleness window in days (default server-side: 90, cap 3650).
	Days *int `form:"days,omitempty" json:"days,omitempty"`
}

// CreateNotificationChannelJSONBody defines parameters for CreateNotificationChannel.
type CreateNotificationChannelJSONBody struct {
	Email   *string `json:"email,omitempty"`
	Enabled *bool   `json:"enabled,omitempty"`

	// Events Comma-separated event types; empty = all.
	Events *string `json:"events,omitempty"`
	Name   string  `json:"name"`

	// Type webhook | slack | teams | email
	Type string  `json:"type"`
	Url  *string `json:"url,omitempty"`
}

// UpdateNotificationChannelJSONBody defines parameters for UpdateNotificationChannel.
type UpdateNotificationChannelJSONBody struct {
	Email   *string `json:"email,omitempty"`
	Enabled *bool   `json:"enabled,omitempty"`
	Events  *string `json:"events,omitempty"`
	Url     *string `json:"url,omitempty"`
}

// PatHygieneParams defines parameters for PatHygiene.
type PatHygieneParams struct {
	// Days Staleness window in days (default server-side: 90, cap 3650).
	Days *int `form:"days,omitempty" json:"days,omitempty"`
}

// ListProjectsParams defines parameters for ListProjects.
type ListProjectsParams struct {
	// IncludeDeleted When 'true', also returns soft-deleted projects (each flagged via deleted/deleted_at) for the restore UI.
	IncludeDeleted *ListProjectsParamsIncludeDeleted `form:"include_deleted,omitempty" json:"include_deleted,omitempty"`
}

// ListProjectsParamsIncludeDeleted defines parameters for ListProjects.
type ListProjectsParamsIncludeDeleted string

// CreateProjectJSONBody defines parameters for CreateProject.
type CreateProjectJSONBody struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// CreateAccessRequestJSONBody defines parameters for CreateAccessRequest.
type CreateAccessRequestJSONBody struct {
	Reason *string `json:"reason,omitempty"`

	// SuggestedRole Project role the requester would like
	SuggestedRole *string `json:"suggested_role,omitempty"`
}

// ResolveAccessRequestJSONBody defines parameters for ResolveAccessRequest.
type ResolveAccessRequestJSONBody struct {
	Action ResolveAccessRequestJSONBodyAction `json:"action"`

	// GrantTtl Optional on approve — time-bound (just-in-time) the granted role; a Go duration (e.g. 4h, 30m). Empty/absent = permanent. The grant stops authorizing once the TTL elapses and is swept by the JIT expiry scheduler.
	GrantTtl *string `json:"grant_ttl,omitempty"`

	// GrantedRole Role to grant on approve
	GrantedRole *string `json:"granted_role,omitempty"`

	// Reason Reason on reject
	Reason *string `json:"reason,omitempty"`
}

// ResolveAccessRequestJSONBodyAction defines parameters for ResolveAccessRequest.
type ResolveAccessRequestJSONBodyAction string

// OpenAccessReviewCampaignJSONBody defines parameters for OpenAccessReviewCampaign.
type OpenAccessReviewCampaignJSONBody struct {
	// Name Campaign label, e.g. "Q4 2026 access recertification"
	Name *string `json:"name,omitempty"`
}

// CloseAccessReviewCampaignJSONBody defines parameters for CloseAccessReviewCampaign.
type CloseAccessReviewCampaignJSONBody struct {
	// Force Close even if items remain pending
	Force *bool `json:"force,omitempty"`
}

// DecideAccessReviewCampaignItemJSONBody defines parameters for DecideAccessReviewCampaignItem.
type DecideAccessReviewCampaignItemJSONBody struct {
	Action DecideAccessReviewCampaignItemJSONBodyAction `json:"action"`

	// Reason Optional reviewer note
	Reason *string `json:"reason,omitempty"`
}

// DecideAccessReviewCampaignItemJSONBodyAction defines parameters for DecideAccessReviewCampaignItem.
type DecideAccessReviewCampaignItemJSONBodyAction string

// ActivateBreakGlassJSONBody defines parameters for ActivateBreakGlass.
type ActivateBreakGlassJSONBody struct {
	// Justification Written reason (required)
	Justification string `json:"justification"`

	// Ttl Optional grant-lifetime override, a Go duration (e.g. 2h); capped at the server max
	Ttl *string `json:"ttl,omitempty"`
}

// ListProjectEnvironmentsParams defines parameters for ListProjectEnvironments.
type ListProjectEnvironmentsParams struct {
	// IncludeDeleted When 'true', also returns soft-deleted environments.
	IncludeDeleted *ListProjectEnvironmentsParamsIncludeDeleted `form:"include_deleted,omitempty" json:"include_deleted,omitempty"`
}

// ListProjectEnvironmentsParamsIncludeDeleted defines parameters for ListProjectEnvironments.
type ListProjectEnvironmentsParamsIncludeDeleted string

// CreateProjectEnvironmentJSONBody defines parameters for CreateProjectEnvironment.
type CreateProjectEnvironmentJSONBody struct {
	Name string `json:"name"`
}

// CreateProjectInvitationJSONBody defines parameters for CreateProjectInvitation.
type CreateProjectInvitationJSONBody struct {
	Email openapi_types.Email `json:"email"`

	// Role Project role to assign on accept
	Role string `json:"role"`
}

// CreateMachineIdentityJSONBody defines parameters for CreateMachineIdentity.
type CreateMachineIdentityJSONBody struct {
	// Classification Data classification: public | internal | confidential | restricted
	Classification *string `json:"classification,omitempty"`
	Description    *string `json:"description,omitempty"`
	IdentityType   *string `json:"identity_type,omitempty"`
	Name           string  `json:"name"`
}

// TransitionMachineIdentityJSONBody defines parameters for TransitionMachineIdentity.
type TransitionMachineIdentityJSONBody struct {
	Action TransitionMachineIdentityJSONBodyAction `json:"action"`
}

// TransitionMachineIdentityJSONBodyAction defines parameters for TransitionMachineIdentity.
type TransitionMachineIdentityJSONBodyAction string

// CreateOIDCBindingJSONBody defines parameters for CreateOIDCBinding.
type CreateOIDCBindingJSONBody struct {
	// Issuer The token's iss claim
	Issuer string `json:"issuer"`

	// Subject The token's sub claim
	Subject string `json:"subject"`
}

// IssueMachineTokenJSONBody defines parameters for IssueMachineToken.
type IssueMachineTokenJSONBody struct {
	// Classification Data classification: public | internal | confidential | restricted
	Classification *string `json:"classification,omitempty"`

	// ExpiresInDays Optional; omit or 0 for no expiry
	ExpiresInDays *int   `json:"expires_in_days,omitempty"`
	Name          string `json:"name"`
}

// GetPermissionMatrixParams defines parameters for GetPermissionMatrix.
type GetPermissionMatrixParams struct {
	// ProjectId Filter to one project (0/omit = every project, including global grants).
	ProjectId *int `form:"project_id,omitempty" json:"project_id,omitempty"`

	// Format When 'csv', return text/csv instead of the JSON envelope.
	Format *GetPermissionMatrixParamsFormat `form:"format,omitempty" json:"format,omitempty"`
}

// GetPermissionMatrixParamsFormat defines parameters for GetPermissionMatrix.
type GetPermissionMatrixParamsFormat string

// CreateRejectionReasonTemplateJSONBody defines parameters for CreateRejectionReasonTemplate.
type CreateRejectionReasonTemplateJSONBody struct {
	Name   string `json:"name"`
	Reason string `json:"reason"`
}

// CreateRoleJSONBody defines parameters for CreateRole.
type CreateRoleJSONBody struct {
	Description string `json:"description"`
	Name        string `json:"name"`

	// Permissions Permission names.
	Permissions []string `json:"permissions"`
}

// AssignPermissionToRoleJSONBody defines parameters for AssignPermissionToRole.
type AssignPermissionToRoleJSONBody struct {
	PermissionId int `json:"permission_id"`
}

// ListRotationPoliciesParams defines parameters for ListRotationPolicies.
type ListRotationPoliciesParams struct {
	ProjectId     *int `form:"project_id,omitempty" json:"project_id,omitempty"`
	EnvironmentId *int `form:"environment_id,omitempty" json:"environment_id,omitempty"`
}

// CreateRotationPolicyJSONBody defines parameters for CreateRotationPolicy.
type CreateRotationPolicyJSONBody struct {
	AlertDaysBefore *int                              `json:"alert_days_before,omitempty"`
	Description     *string                           `json:"description,omitempty"`
	EnvironmentId   *int                              `json:"environment_id"`
	IntervalDays    int                               `json:"interval_days"`
	Name            string                            `json:"name"`
	NotifyOnBreach  *bool                             `json:"notify_on_breach,omitempty"`
	ProjectId       *int                              `json:"project_id"`
	Scope           CreateRotationPolicyJSONBodyScope `json:"scope"`
}

// CreateRotationPolicyJSONBodyScope defines parameters for CreateRotationPolicy.
type CreateRotationPolicyJSONBodyScope string

// EvaluateRotationPoliciesParams defines parameters for EvaluateRotationPolicies.
type EvaluateRotationPoliciesParams struct {
	ProjectId *int `form:"project_id,omitempty" json:"project_id,omitempty"`
}

// UpdateRotationPolicyJSONBody defines parameters for UpdateRotationPolicy.
type UpdateRotationPolicyJSONBody struct {
	AlertDaysBefore *int    `json:"alert_days_before,omitempty"`
	Description     *string `json:"description,omitempty"`
	IntervalDays    int     `json:"interval_days"`
	IsActive        *bool   `json:"is_active,omitempty"`
	Name            string  `json:"name"`
	NotifyOnBreach  *bool   `json:"notify_on_breach,omitempty"`
}

// CreateSecretAccessRequestJSONBody defines parameters for CreateSecretAccessRequest.
type CreateSecretAccessRequestJSONBody struct {
	Reason   string `json:"reason"`
	SecretId int    `json:"secret_id"`
}

// ResolveSecretAccessRequestJSONBody defines parameters for ResolveSecretAccessRequest.
type ResolveSecretAccessRequestJSONBody struct {
	Action ResolveSecretAccessRequestJSONBodyAction `json:"action"`

	// Reason Reason on reject
	Reason *string `json:"reason,omitempty"`
}

// ResolveSecretAccessRequestJSONBodyAction defines parameters for ResolveSecretAccessRequest.
type ResolveSecretAccessRequestJSONBodyAction string

// GetSecretByNameParams defines parameters for GetSecretByName.
type GetSecretByNameParams struct {
	Name          string `form:"name" json:"name"`
	ProjectId     int    `form:"project_id" json:"project_id"`
	EnvironmentId int    `form:"environment_id" json:"environment_id"`
}

// RemoveUserRoleJSONBody defines parameters for RemoveUserRole.
type RemoveUserRoleJSONBody struct {
	// EnvironmentId Scope (0 = global).
	EnvironmentId *int `json:"environment_id,omitempty"`

	// ProjectId Scope (0 = global).
	ProjectId *int `json:"project_id,omitempty"`
	RoleId    int  `json:"role_id"`
	UserId    int  `json:"user_id"`
}

// AssignUserRoleJSONBody defines parameters for AssignUserRole.
type AssignUserRoleJSONBody struct {
	// EnvironmentId Scope (0 = global).
	EnvironmentId *int `json:"environment_id,omitempty"`

	// ExpiresAt RFC3339; omit or null for a non-expiring grant. JIT access — the assignment is automatically revoked when the timestamp is reached.
	ExpiresAt *time.Time `json:"expires_at"`

	// ProjectId Scope (0 = global).
	ProjectId *int `json:"project_id,omitempty"`
	RoleId    int  `json:"role_id"`
	UserId    int  `json:"user_id"`
}

// ListUsersParams defines parameters for ListUsers.
type ListUsersParams struct {
	Page           *int    `form:"page,omitempty" json:"page,omitempty"`
	PageSize       *int    `form:"page_size,omitempty" json:"page_size,omitempty"`
	Search         *string `form:"search,omitempty" json:"search,omitempty"`
	Username       *string `form:"username,omitempty" json:"username,omitempty"`
	Email          *string `form:"email,omitempty" json:"email,omitempty"`
	IsActive       *bool   `form:"is_active,omitempty" json:"is_active,omitempty"`
	IncludeDeleted *bool   `form:"include_deleted,omitempty" json:"include_deleted,omitempty"`

	// Filter Set to `inactive` for users with no login in the last 30 days.
	Filter *ListUsersParamsFilter `form:"filter,omitempty" json:"filter,omitempty"`
}

// ListUsersParamsFilter defines parameters for ListUsers.
type ListUsersParamsFilter string

// CreateUserJSONBody defines parameters for CreateUser.
type CreateUserJSONBody struct {
	// DeliverSetupLink Provision via account-setup link instead of an admin-set password.
	DeliverSetupLink *bool               `json:"deliver_setup_link,omitempty"`
	DisplayName      string              `json:"display_name"`
	Email            openapi_types.Email `json:"email"`

	// GenerateOneTimePassword Server-generated one-time password, returned once. Mutually exclusive with deliver_setup_link.
	GenerateOneTimePassword *bool `json:"generate_one_time_password,omitempty"`
	IsActive                *bool `json:"is_active,omitempty"`

	// Password Required unless deliver_setup_link or generate_one_time_password is set.
	Password *string `json:"password,omitempty"`

	// ProjectAssignments Project-scoped role assignments applied atomically (admin-set-password path only).
	ProjectAssignments *[]struct {
		ProjectId *int    `json:"project_id,omitempty"`
		Role      *string `json:"role,omitempty"`
	} `json:"project_assignments,omitempty"`

	// Role Optional system role override (admin-set-password path only).
	Role     *string `json:"role,omitempty"`
	Username string  `json:"username"`
}

// UpdateUserJSONBody defines parameters for UpdateUser.
type UpdateUserJSONBody struct {
	Active      *bool                `json:"active,omitempty"`
	DisplayName *string              `json:"display_name,omitempty"`
	Email       *openapi_types.Email `json:"email,omitempty"`
	Username    *string              `json:"username,omitempty"`
}

// UpdateUserRolesJSONBody defines parameters for UpdateUserRoles.
type UpdateUserRolesJSONBody struct {
	// EnvironmentId Scope (0 = global).
	EnvironmentId *int `json:"environment_id,omitempty"`

	// ProjectId Scope (0 = global).
	ProjectId *int   `json:"project_id,omitempty"`
	RoleIds   *[]int `json:"role_ids,omitempty"`
}

// AuthLoginJSONBody defines parameters for AuthLogin.
type AuthLoginJSONBody struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// BulkApproveAccessRequestsJSONRequestBody defines body for BulkApproveAccessRequests for application/json ContentType.
type BulkApproveAccessRequestsJSONRequestBody BulkApproveAccessRequestsJSONBody

// BulkRejectAccessRequestsJSONRequestBody defines body for BulkRejectAccessRequests for application/json ContentType.
type BulkRejectAccessRequestsJSONRequestBody BulkRejectAccessRequestsJSONBody

// UpdateAnomalyConfigJSONRequestBody defines body for UpdateAnomalyConfig for application/json ContentType.
type UpdateAnomalyConfigJSONRequestBody UpdateAnomalyConfigJSONBody

// CreateAlertEscalationPolicyJSONRequestBody defines body for CreateAlertEscalationPolicy for application/json ContentType.
type CreateAlertEscalationPolicyJSONRequestBody CreateAlertEscalationPolicyJSONBody

// MfaStepUpJSONRequestBody defines body for MfaStepUp for application/json ContentType.
type MfaStepUpJSONRequestBody MfaStepUpJSONBody

// UpdateAuthProfileJSONRequestBody defines body for UpdateAuthProfile for application/json ContentType.
type UpdateAuthProfileJSONRequestBody UpdateAuthProfileJSONBody

// CreatePATJSONRequestBody defines body for CreatePAT for application/json ContentType.
type CreatePATJSONRequestBody CreatePATJSONBody

// CreateDynamicSecretConfigJSONRequestBody defines body for CreateDynamicSecretConfig for application/json ContentType.
type CreateDynamicSecretConfigJSONRequestBody CreateDynamicSecretConfigJSONBody

// ClassifyDynamicSecretConfigJSONRequestBody defines body for ClassifyDynamicSecretConfig for application/json ContentType.
type ClassifyDynamicSecretConfigJSONRequestBody ClassifyDynamicSecretConfigJSONBody

// IssueDynamicSecretLeaseJSONRequestBody defines body for IssueDynamicSecretLease for application/json ContentType.
type IssueDynamicSecretLeaseJSONRequestBody IssueDynamicSecretLeaseJSONBody

// RenewDynamicSecretLeaseJSONRequestBody defines body for RenewDynamicSecretLease for application/json ContentType.
type RenewDynamicSecretLeaseJSONRequestBody RenewDynamicSecretLeaseJSONBody

// CreateGroupJSONRequestBody defines body for CreateGroup for application/json ContentType.
type CreateGroupJSONRequestBody CreateGroupJSONBody

// UpdateGroupJSONRequestBody defines body for UpdateGroup for application/json ContentType.
type UpdateGroupJSONRequestBody UpdateGroupJSONBody

// AddGroupMemberJSONRequestBody defines body for AddGroupMember for application/json ContentType.
type AddGroupMemberJSONRequestBody AddGroupMemberJSONBody

// AssignRoleToGroupJSONRequestBody defines body for AssignRoleToGroup for application/json ContentType.
type AssignRoleToGroupJSONRequestBody AssignRoleToGroupJSONBody

// CreateNotificationChannelJSONRequestBody defines body for CreateNotificationChannel for application/json ContentType.
type CreateNotificationChannelJSONRequestBody CreateNotificationChannelJSONBody

// UpdateNotificationChannelJSONRequestBody defines body for UpdateNotificationChannel for application/json ContentType.
type UpdateNotificationChannelJSONRequestBody UpdateNotificationChannelJSONBody

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody CreateProjectJSONBody

// CreateAccessRequestJSONRequestBody defines body for CreateAccessRequest for application/json ContentType.
type CreateAccessRequestJSONRequestBody CreateAccessRequestJSONBody

// ResolveAccessRequestJSONRequestBody defines body for ResolveAccessRequest for application/json ContentType.
type ResolveAccessRequestJSONRequestBody ResolveAccessRequestJSONBody

// AttestProjectAccessReviewJSONRequestBody defines body for AttestProjectAccessReview for application/json ContentType.
type AttestProjectAccessReviewJSONRequestBody = AccessReviewDecision

// OpenAccessReviewCampaignJSONRequestBody defines body for OpenAccessReviewCampaign for application/json ContentType.
type OpenAccessReviewCampaignJSONRequestBody OpenAccessReviewCampaignJSONBody

// CloseAccessReviewCampaignJSONRequestBody defines body for CloseAccessReviewCampaign for application/json ContentType.
type CloseAccessReviewCampaignJSONRequestBody CloseAccessReviewCampaignJSONBody

// DecideAccessReviewCampaignItemJSONRequestBody defines body for DecideAccessReviewCampaignItem for application/json ContentType.
type DecideAccessReviewCampaignItemJSONRequestBody DecideAccessReviewCampaignItemJSONBody

// RevokeProjectAccessReviewJSONRequestBody defines body for RevokeProjectAccessReview for application/json ContentType.
type RevokeProjectAccessReviewJSONRequestBody = AccessReviewDecision

// ActivateBreakGlassJSONRequestBody defines body for ActivateBreakGlass for application/json ContentType.
type ActivateBreakGlassJSONRequestBody ActivateBreakGlassJSONBody

// CreateProjectEnvironmentJSONRequestBody defines body for CreateProjectEnvironment for application/json ContentType.
type CreateProjectEnvironmentJSONRequestBody CreateProjectEnvironmentJSONBody

// CreateProjectInvitationJSONRequestBody defines body for CreateProjectInvitation for application/json ContentType.
type CreateProjectInvitationJSONRequestBody CreateProjectInvitationJSONBody

// CreateMachineIdentityJSONRequestBody defines body for CreateMachineIdentity for application/json ContentType.
type CreateMachineIdentityJSONRequestBody CreateMachineIdentityJSONBody

// TransitionMachineIdentityJSONRequestBody defines body for TransitionMachineIdentity for application/json ContentType.
type TransitionMachineIdentityJSONRequestBody TransitionMachineIdentityJSONBody

// CreateOIDCBindingJSONRequestBody defines body for CreateOIDCBinding for application/json ContentType.
type CreateOIDCBindingJSONRequestBody CreateOIDCBindingJSONBody

// IssueMachineTokenJSONRequestBody defines body for IssueMachineToken for application/json ContentType.
type IssueMachineTokenJSONRequestBody IssueMachineTokenJSONBody

// CreateRejectionReasonTemplateJSONRequestBody defines body for CreateRejectionReasonTemplate for application/json ContentType.
type CreateRejectionReasonTemplateJSONRequestBody CreateRejectionReasonTemplateJSONBody

// CreateRoleJSONRequestBody defines body for CreateRole for application/json ContentType.
type CreateRoleJSONRequestBody CreateRoleJSONBody

// AssignPermissionToRoleJSONRequestBody defines body for AssignPermissionToRole for application/json ContentType.
type AssignPermissionToRoleJSONRequestBody AssignPermissionToRoleJSONBody

// CreateRotationPolicyJSONRequestBody defines body for CreateRotationPolicy for application/json ContentType.
type CreateRotationPolicyJSONRequestBody CreateRotationPolicyJSONBody

// UpdateRotationPolicyJSONRequestBody defines body for UpdateRotationPolicy for application/json ContentType.
type UpdateRotationPolicyJSONRequestBody UpdateRotationPolicyJSONBody

// CreateSecretAccessRequestJSONRequestBody defines body for CreateSecretAccessRequest for application/json ContentType.
type CreateSecretAccessRequestJSONRequestBody CreateSecretAccessRequestJSONBody

// ResolveSecretAccessRequestJSONRequestBody defines body for ResolveSecretAccessRequest for application/json ContentType.
type ResolveSecretAccessRequestJSONRequestBody ResolveSecretAccessRequestJSONBody

// RemoveUserRoleJSONRequestBody defines body for RemoveUserRole for application/json ContentType.
type RemoveUserRoleJSONRequestBody RemoveUserRoleJSONBody

// AssignUserRoleJSONRequestBody defines body for AssignUserRole for application/json ContentType.
type AssignUserRoleJSONRequestBody AssignUserRoleJSONBody

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody CreateUserJSONBody

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody UpdateUserJSONBody

// UpdateUserRolesJSONRequestBody defines body for UpdateUserRoles for application/json ContentType.
type UpdateUserRolesJSONRequestBody UpdateUserRolesJSONBody

// AuthLoginJSONRequestBody defines body for AuthLogin for application/json ContentType.
type AuthLoginJSONRequestBody AuthLoginJSONBody
