// Package apiclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package apiclient

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for BreakGlassActivationState.
const (
	BreakGlassActivationStateActive  BreakGlassActivationState = "active"
	BreakGlassActivationStateExpired BreakGlassActivationState = "expired"
	BreakGlassActivationStateRevoked BreakGlassActivationState = "revoked"
)

// Defines values for DynamicSecretConfigBackendType.
const (
	AwsSts     DynamicSecretConfigBackendType = "aws-sts"
	Azure      DynamicSecretConfigBackendType = "azure"
	Gcp        DynamicSecretConfigBackendType = "gcp"
	Kubernetes DynamicSecretConfigBackendType = "kubernetes"
	Mongodb    DynamicSecretConfigBackendType = "mongodb"
	Mysql      DynamicSecretConfigBackendType = "mysql"
	Postgres   DynamicSecretConfigBackendType = "postgres"
	Redis      DynamicSecretConfigBackendType = "redis"
)

// Defines values for DynamicSecretLeaseStatus.
const (
	DynamicSecretLeaseStatusActive       DynamicSecretLeaseStatus = "active"
	DynamicSecretLeaseStatusExpired      DynamicSecretLeaseStatus = "expired"
	DynamicSecretLeaseStatusRevokeFailed DynamicSecretLeaseStatus = "revoke_failed"
	DynamicSecretLeaseStatusRevoked      DynamicSecretLeaseStatus = "revoked"
)

// Defines values for MachineIdentityState.
const (
	Active    MachineIdentityState = "active"
	Pending   MachineIdentityState = "pending"
	Revoked   MachineIdentityState = "revoked"
	Suspended MachineIdentityState = "suspended"
)

// Defines values for RotationPlanSecretStatus.
const (
	DueSoon RotationPlanSecretStatus = "due_soon"
	Overdue RotationPlanSecretStatus = "overdue"
)

// Defines values for RotationPolicyScope.
const (
	RotationPolicyScopeEnvironment RotationPolicyScope = "environment"
	RotationPolicyScopeProject     RotationPolicyScope = "project"
)

// Defines values for CreateDynamicSecretConfigJSONBodyClassification.
const (
	CreateDynamicSecretConfigJSONBodyClassificationConfidential CreateDynamicSecretConfigJSONBodyClassification = "confidential"
	CreateDynamicSecretConfigJSONBodyClassificationEmpty        CreateDynamicSecretConfigJSONBodyClassification = ""
	CreateDynamicSecretConfigJSONBodyClassificationInternal     CreateDynamicSecretConfigJSONBodyClassification = "internal"
	CreateDynamicSecretConfigJSONBodyClassificationPublic       CreateDynamicSecretConfigJSONBodyClassification = "public"
	CreateDynamicSecretConfigJSONBodyClassificationRestricted   CreateDynamicSecretConfigJSONBodyClassification = "restricted"
)

// Defines values for ClassifyDynamicSecretConfigJSONBodyClassification.
const (
	ClassifyDynamicSecretConfigJSONBodyClassificationConfidential ClassifyDynamicSecretConfigJSONBodyClassification = "confidential"
	ClassifyDynamicSecretConfigJSONBodyClassificationEmpty        ClassifyDynamicSecretConfigJSONBodyClassification = ""
	ClassifyDynamicSecretConfigJSONBodyClassificationInternal     ClassifyDynamicSecretConfigJSONBodyClassification = "internal"
	ClassifyDynamicSecretConfigJSONBodyClassificationPublic       ClassifyDynamicSecretConfigJSONBodyClassification = "public"
	ClassifyDynamicSecretConfigJSONBodyClassificationRestricted   ClassifyDynamicSecretConfigJSONBodyClassification = "restricted"
)

// Defines values for ListProjectsParamsIncludeDeleted.
const (
	False ListProjectsParamsIncludeDeleted = "false"
	True  ListProjectsParamsIncludeDeleted = "true"
)

// Defines values for TransitionMachineIdentityJSONBodyAction.
const (
	Activate TransitionMachineIdentityJSONBodyAction = "activate"
	Revoke   TransitionMachineIdentityJSONBodyAction = "revoke"
	Suspend  TransitionMachineIdentityJSONBodyAction = "suspend"
)

// Defines values for CreateRotationPolicyJSONBodyScope.
const (
	CreateRotationPolicyJSONBodyScopeEnvironment CreateRotationPolicyJSONBodyScope = "environment"
	CreateRotationPolicyJSONBodyScopeProject     CreateRotationPolicyJSONBodyScope = "project"
)

// BreakGlassActivation One emergency-access self-grant (ADR-108 PR 1 addition).
type BreakGlassActivation struct {
	CreatedAt     *string                    `json:"created_at,omitempty"`
	ExpiresAt     *string                    `json:"expires_at,omitempty"`
	Id            *uint32                    `json:"id,omitempty"`
	Justification *string                    `json:"justification,omitempty"`
	RoleName      *string                    `json:"role_name,omitempty"`
	State         *BreakGlassActivationState `json:"state,omitempty"`
	UserId        *uint32                    `json:"user_id,omitempty"`
}

// BreakGlassActivationState defines model for BreakGlassActivation.State.
type BreakGlassActivationState string

// DeploymentRotationPlan The install-wide roll-up of every project's rotation plan (ADR-108 PR 1 addition, ADR-053) -- a roll-up of per-project plans, most pressing first.
type DeploymentRotationPlan struct {
	DueSoonCount     *int            `json:"due_soon_count,omitempty"`
	OverdueCount     *int            `json:"overdue_count,omitempty"`
	Projects         *[]RotationPlan `json:"projects,omitempty"`
	ProjectsScanned  *int            `json:"projects_scanned,omitempty"`
	ProjectsWithWork *int            `json:"projects_with_work,omitempty"`
	TotalSecrets     *int            `json:"total_secrets,omitempty"`
}

// DynamicSecretConfig A registered dynamic-secret target config (ADR-108 PR 1 addition).
type DynamicSecretConfig struct {
	BackendType       *DynamicSecretConfigBackendType `json:"backend_type,omitempty"`
	Classification    *string                         `json:"classification,omitempty"`
	DefaultTtlSeconds *int                            `json:"default_ttl_seconds,omitempty"`
	EnvironmentId     *uint32                         `json:"environment_id,omitempty"`
	Id                *uint32                         `json:"id,omitempty"`
	MaxTtlSeconds     *int                            `json:"max_ttl_seconds,omitempty"`
	Name              *string                         `json:"name,omitempty"`
	ProjectId         *uint32                         `json:"project_id,omitempty"`
}

// DynamicSecretConfigBackendType defines model for DynamicSecretConfig.BackendType.
type DynamicSecretConfigBackendType string

// DynamicSecretIssuedLease A freshly-issued dynamic-secret credential, shown once (ADR-108 PR 1 addition). username/password are populated for DB/cache backends; fields carries arbitrary key/value pairs for cloud-IAM backends (AWS STS, GCP, Azure, Kubernetes) instead.
type DynamicSecretIssuedLease struct {
	ExpiresAt *string            `json:"expires_at,omitempty"`
	Fields    *map[string]string `json:"fields,omitempty"`
	LeaseId   *string            `json:"lease_id,omitempty"`
	Password  *string            `json:"password,omitempty"`
	Username  *string            `json:"username,omitempty"`
}

// DynamicSecretLease A dynamic-secret lease summary (ADR-108 PR 1 addition).
type DynamicSecretLease struct {
	ExpiresAt *string                   `json:"expires_at,omitempty"`
	IssuedAt  *string                   `json:"issued_at,omitempty"`
	LeaseId   *string                   `json:"lease_id,omitempty"`
	RoleName  *string                   `json:"role_name,omitempty"`
	Status    *DynamicSecretLeaseStatus `json:"status,omitempty"`
}

// DynamicSecretLeaseStatus defines model for DynamicSecretLease.Status.
type DynamicSecretLeaseStatus string

// MachineAuditReport Deployment-wide machine identity audit report (GET /machine-identities/audit).
type MachineAuditReport struct {
	GeneratedAt  *time.Time         `json:"generated_at,omitempty"`
	Machines     *[]MachineAuditRow `json:"machines,omitempty"`
	RevokedCount *int               `json:"revoked_count,omitempty"`
	StaleCount   *int               `json:"stale_count,omitempty"`
	TotalCount   *int               `json:"total_count,omitempty"`
}

// MachineAuditRow defines model for MachineAuditRow.
type MachineAuditRow struct {
	CreatedAt       *time.Time `json:"created_at,omitempty"`
	CredentialCount *int       `json:"credential_count,omitempty"`
	Description     *string    `json:"description,omitempty"`
	IsRevoked       *bool      `json:"is_revoked,omitempty"`
	IsStale         *bool      `json:"is_stale,omitempty"`
	LastUsedAt      *time.Time `json:"last_used_at,omitempty"`
	MachineId       *int       `json:"machine_id,omitempty"`
	Name            *string    `json:"name,omitempty"`
}

// MachineIdentity A project-scoped machine identity (ADR-023).
type MachineIdentity struct {
	Classification             *string               `json:"classification,omitempty"`
	CreatedAt                  *time.Time            `json:"created_at,omitempty"`
	CreatedBy                  *int                  `json:"created_by,omitempty"`
	CreatedByMachineIdentityId *int                  `json:"created_by_machine_identity_id,omitempty"`
	Description                *string               `json:"description,omitempty"`
	Id                         *int                  `json:"id,omitempty"`
	IdentityType               *string               `json:"identity_type,omitempty"`
	LastSeenAt                 *time.Time            `json:"last_seen_at"`
	Name                       *string               `json:"name,omitempty"`
	ProjectId                  *int                  `json:"project_id,omitempty"`
	RevokedAt                  *time.Time            `json:"revoked_at"`
	State                      *MachineIdentityState `json:"state,omitempty"`
	UpdatedAt                  *time.Time            `json:"updated_at,omitempty"`
}

// MachineIdentityState defines model for MachineIdentity.State.
type MachineIdentityState string

// MachineToken Machine identity token metadata (never the raw secret, except once at issuance).
type MachineToken struct {
	ExpiresAt  *time.Time `json:"expires_at"`
	Id         *int       `json:"id,omitempty"`
	LastUsedAt *time.Time `json:"last_used_at"`
	Name       *string    `json:"name,omitempty"`
	Prefix     *string    `json:"prefix,omitempty"`
	Revoked    *bool      `json:"revoked,omitempty"`
}

// MachineTokenHygieneRow A deployment-wide machine-token hygiene entry (GET /machine-token-hygiene) -- never includes the token secret.
type MachineTokenHygieneRow struct {
	Expired           *bool   `json:"expired,omitempty"`
	Id                *int    `json:"id,omitempty"`
	LastUsedAt        *string `json:"last_used_at,omitempty"`
	MachineIdentityId *int    `json:"machine_identity_id,omitempty"`
	Name              *string `json:"name,omitempty"`
	Stale             *bool   `json:"stale,omitempty"`
	TokenPrefix       *string `json:"token_prefix,omitempty"`
}

// OIDCBinding An OIDC federation binding (ADR-031) mapping an external (issuer, subject) to a machine identity.
type OIDCBinding struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Id        *int       `json:"id,omitempty"`
	Issuer    *string    `json:"issuer,omitempty"`
	Subject   *string    `json:"subject,omitempty"`
}

// PATHygieneRow A deployment-wide PAT hygiene entry (GET /pat-hygiene) -- never includes the token secret.
type PATHygieneRow struct {
	Expired     *bool   `json:"expired,omitempty"`
	ExpiresAt   *string `json:"expires_at,omitempty"`
	Id          *int    `json:"id,omitempty"`
	LastUsedAt  *string `json:"last_used_at,omitempty"`
	Name        *string `json:"name,omitempty"`
	Stale       *bool   `json:"stale,omitempty"`
	TokenPrefix *string `json:"token_prefix,omitempty"`
	UserId      *int    `json:"user_id,omitempty"`
}

// PATToken A personal access token (ADR-027/ADR-042). The raw secret is never returned except once, in the create response.
type PATToken struct {
	AllowedCidrs     *[]string  `json:"allowed_cidrs"`
	CreatedAt        *time.Time `json:"created_at,omitempty"`
	EnvironmentScope *int       `json:"environment_scope,omitempty"`
	ExpiresAt        *time.Time `json:"expires_at"`
	Id               *int       `json:"id,omitempty"`
	LastUsedAt       *time.Time `json:"last_used_at"`
	Name             *string    `json:"name,omitempty"`
	ProjectScope     *int       `json:"project_scope,omitempty"`
	Revoked          *bool      `json:"revoked,omitempty"`
	Scopes           *[]string  `json:"scopes"`
	TokenPrefix      *string    `json:"token_prefix,omitempty"`
}

// RotationOrder A safe rotation sequence for a project's secret dependency graph (ADR-108 PR 1 addition, ADR-052): each secret is listed before anything that depends on it.
type RotationOrder struct {
	Order     *[]RotationOrderStep `json:"order,omitempty"`
	ProjectId *uint32              `json:"project_id,omitempty"`
}

// RotationOrderStep One secret in a project's safe rotation sequence (ADR-052).
type RotationOrderStep struct {
	SecretId   *uint32 `json:"secret_id,omitempty"`
	SecretName *string `json:"secret_name,omitempty"`
}

// RotationPlan A project's automated rotation plan (ADR-108 PR 1 addition, ADR-053).
type RotationPlan struct {
	DueSoonCount *int                `json:"due_soon_count,omitempty"`
	OverdueCount *int                `json:"overdue_count,omitempty"`
	ProjectId    *uint32             `json:"project_id,omitempty"`
	TotalSecrets *int                `json:"total_secrets,omitempty"`
	Waves        *[]RotationPlanWave `json:"waves,omitempty"`
}

// RotationPlanSecret One secret entry in a rotation-plan wave (ADR-108 PR 1 addition, ADR-053).
type RotationPlanSecret struct {
	AutoRotate  *bool                     `json:"auto_rotate,omitempty"`
	DaysOverdue *int                      `json:"days_overdue,omitempty"`
	Reasons     *[]string                 `json:"reasons,omitempty"`
	RiskBand    *string                   `json:"risk_band,omitempty"`
	SecretId    *uint32                   `json:"secret_id,omitempty"`
	SecretName  *string                   `json:"secret_name,omitempty"`
	Status      *RotationPlanSecretStatus `json:"status,omitempty"`
}

// RotationPlanSecretStatus defines model for RotationPlanSecret.Status.
type RotationPlanSecretStatus string

// RotationPlanWave A dependency-safe batch of secrets to rotate together (ADR-053).
type RotationPlanWave struct {
	Index   *int                  `json:"index,omitempty"`
	Secrets *[]RotationPlanSecret `json:"secrets,omitempty"`
}

// RotationPolicy A secret-rotation policy (ADR-108 PR 1 addition). Snake_case, matching this spec's usual convention and the model's real wire format: models.RotationPolicy (internal/storage/models/models.go) previously had no `json:` tags on most fields, so encoding/json's default marshaling emitted the bare Go field names verbatim (ID, Name, ProjectID, IntervalDays, ...) instead -- a PascalCase wire format silently decoded by any snake_case-tagged consumer (Go's case-insensitive JSON fallback matches "ID"~"id" but not "ProjectID"~"project_id", an extra underscore is not a case difference) as the zero value for every multi-word field. Fixed at the source (the model itself now carries these exact tags) rather than documented here as a PascalCase exception -- see the model's own doc comment for the full writeup, and docs/cli-split-inventory.md §7 PR 1's closure note for how this was found.
type RotationPolicy struct {
	AlertDaysBefore *int                 `json:"alert_days_before,omitempty"`
	CreatedBy       *string              `json:"created_by,omitempty"`
	Description     *string              `json:"description,omitempty"`
	EnvironmentId   *uint32              `json:"environment_id"`
	Id              *uint32              `json:"id,omitempty"`
	IntervalDays    *int                 `json:"interval_days,omitempty"`
	IsActive        *bool                `json:"is_active,omitempty"`
	Name            *string              `json:"name,omitempty"`
	NotifyOnBreach  *bool                `json:"notify_on_breach,omitempty"`
	ProjectId       *uint32              `json:"project_id"`
	Scope           *RotationPolicyScope `json:"scope,omitempty"`
}

// RotationPolicyScope defines model for RotationPolicy.Scope.
type RotationPolicyScope string

// RotationPolicyEvaluation One policy-covered secret's rotation posture, as returned by GET /api/v1/rotation-policies/evaluate (ADR-108 PR 1 addition).
type RotationPolicyEvaluation struct {
	DaysOverdue   *int    `json:"days_overdue,omitempty"`
	IsApproaching *bool   `json:"is_approaching,omitempty"`
	IsOverdue     *bool   `json:"is_overdue,omitempty"`
	PolicyName    *string `json:"policy_name,omitempty"`
	ProjectId     *uint32 `json:"project_id,omitempty"`
	SecretId      *uint32 `json:"secret_id,omitempty"`
	SecretName    *string `json:"secret_name,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Code    *int                    `json:"code,omitempty"`
	Details *map[string]interface{} `json:"details"`

	// Error Short error-type label, e.g. "NotFound", "BadRequest".
	Error   *string `json:"error,omitempty"`
	Message *string `json:"message,omitempty"`
	Success *bool   `json:"success,omitempty"`
}

// MfaStepUpJSONBody defines parameters for MfaStepUp.
type MfaStepUpJSONBody struct {
	// Code TOTP code or a recovery code
	Code string `json:"code"`
}

// UpdateAuthProfileJSONBody defines parameters for UpdateAuthProfile.
type UpdateAuthProfileJSONBody struct {
	DisplayName *string              `json:"display_name,omitempty"`
	Email       *openapi_types.Email `json:"email,omitempty"`
}

// CreatePATJSONBody defines parameters for CreatePAT.
type CreatePATJSONBody struct {
	// AllowedCidrs Restrict the token to source IPs in these CIDRs. Omit/empty = no network restriction.
	AllowedCidrs *[]string `json:"allowed_cidrs,omitempty"`

	// EnvironmentScope ADR-042: confine the token to a single environment id; 0/omit = any environment. Env ids are globally unique, so this also pins the project.
	EnvironmentScope *int `json:"environment_scope,omitempty"`

	// ExpiresAt RFC3339; omit/null for non-expiring
	ExpiresAt *time.Time `json:"expires_at"`
	Name      string     `json:"name"`

	// ProjectScope ADR-042: confine the token to a single project id; 0/omit = any project the owner can reach.
	ProjectScope *int `json:"project_scope,omitempty"`

	// Scopes ADR-042 least-privilege allowlist (e.g. ["secrets.read"], supports "*" and "secrets.*"). Omit/empty = inherit the owner's full permissions. Only ever narrows below the owner.
	Scopes *[]string `json:"scopes,omitempty"`
}

// ListDynamicSecretConfigsParams defines parameters for ListDynamicSecretConfigs.
type ListDynamicSecretConfigsParams struct {
	ProjectId     *int `form:"project_id,omitempty" json:"project_id,omitempty"`
	EnvironmentId *int `form:"environment_id,omitempty" json:"environment_id,omitempty"`
}

// CreateDynamicSecretConfigJSONBody defines parameters for CreateDynamicSecretConfig.
type CreateDynamicSecretConfigJSONBody struct {
	// AdminDsn Plaintext admin DSN; encrypted at rest, never echoed back
	AdminDsn          string                                           `json:"admin_dsn"`
	BackendType       string                                           `json:"backend_type"`
	Classification    *CreateDynamicSecretConfigJSONBodyClassification `json:"classification,omitempty"`
	CreationTemplate  string                                           `json:"creation_template"`
	DefaultTtlSeconds *int                                             `json:"default_ttl_seconds,omitempty"`
	EnvironmentId     int                                              `json:"environment_id"`
	MaxActiveLeases   *int                                             `json:"max_active_leases,omitempty"`
	MaxTtlSeconds     *int                                             `json:"max_ttl_seconds,omitempty"`
	Name              string                                           `json:"name"`
	ProjectId         int                                              `json:"project_id"`
}

// CreateDynamicSecretConfigJSONBodyClassification defines parameters for CreateDynamicSecretConfig.
type CreateDynamicSecretConfigJSONBodyClassification string

// ClassifyDynamicSecretConfigJSONBody defines parameters for ClassifyDynamicSecretConfig.
type ClassifyDynamicSecretConfigJSONBody struct {
	Classification *ClassifyDynamicSecretConfigJSONBodyClassification `json:"classification,omitempty"`
}

// ClassifyDynamicSecretConfigJSONBodyClassification defines parameters for ClassifyDynamicSecretConfig.
type ClassifyDynamicSecretConfigJSONBodyClassification string

// IssueDynamicSecretLeaseJSONBody defines parameters for IssueDynamicSecretLease.
type IssueDynamicSecretLeaseJSONBody struct {
	TtlSeconds *int `json:"ttl_seconds,omitempty"`
}

// RenewDynamicSecretLeaseJSONBody defines parameters for RenewDynamicSecretLease.
type RenewDynamicSecretLeaseJSONBody struct {
	TtlSeconds *int `json:"ttl_seconds,omitempty"`
}

// MachineTokenHygieneParams defines parameters for MachineTokenHygiene.
type MachineTokenHygieneParams struct {
	// Days Staleness window in days (default server-side: 90, cap 3650).
	Days *int `form:"days,omitempty" json:"days,omitempty"`
}

// PatHygieneParams defines parameters for PatHygiene.
type PatHygieneParams struct {
	// Days Staleness window in days (default server-side: 90, cap 3650).
	Days *int `form:"days,omitempty" json:"days,omitempty"`
}

// ListProjectsParams defines parameters for ListProjects.
type ListProjectsParams struct {
	// IncludeDeleted When 'true', also returns soft-deleted projects (each flagged via deleted/deleted_at) for the restore UI.
	IncludeDeleted *ListProjectsParamsIncludeDeleted `form:"include_deleted,omitempty" json:"include_deleted,omitempty"`
}

// ListProjectsParamsIncludeDeleted defines parameters for ListProjects.
type ListProjectsParamsIncludeDeleted string

// CreateProjectJSONBody defines parameters for CreateProject.
type CreateProjectJSONBody struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// ActivateBreakGlassJSONBody defines parameters for ActivateBreakGlass.
type ActivateBreakGlassJSONBody struct {
	// Justification Written reason (required)
	Justification string `json:"justification"`

	// Ttl Optional grant-lifetime override, a Go duration (e.g. 2h); capped at the server max
	Ttl *string `json:"ttl,omitempty"`
}

// CreateMachineIdentityJSONBody defines parameters for CreateMachineIdentity.
type CreateMachineIdentityJSONBody struct {
	// Classification Data classification: public | internal | confidential | restricted
	Classification *string `json:"classification,omitempty"`
	Description    *string `json:"description,omitempty"`
	IdentityType   *string `json:"identity_type,omitempty"`
	Name           string  `json:"name"`
}

// TransitionMachineIdentityJSONBody defines parameters for TransitionMachineIdentity.
type TransitionMachineIdentityJSONBody struct {
	Action TransitionMachineIdentityJSONBodyAction `json:"action"`
}

// TransitionMachineIdentityJSONBodyAction defines parameters for TransitionMachineIdentity.
type TransitionMachineIdentityJSONBodyAction string

// CreateOIDCBindingJSONBody defines parameters for CreateOIDCBinding.
type CreateOIDCBindingJSONBody struct {
	// Issuer The token's iss claim
	Issuer string `json:"issuer"`

	// Subject The token's sub claim
	Subject string `json:"subject"`
}

// IssueMachineTokenJSONBody defines parameters for IssueMachineToken.
type IssueMachineTokenJSONBody struct {
	// Classification Data classification: public | internal | confidential | restricted
	Classification *string `json:"classification,omitempty"`

	// ExpiresInDays Optional; omit or 0 for no expiry
	ExpiresInDays *int   `json:"expires_in_days,omitempty"`
	Name          string `json:"name"`
}

// ListRotationPoliciesParams defines parameters for ListRotationPolicies.
type ListRotationPoliciesParams struct {
	ProjectId     *int `form:"project_id,omitempty" json:"project_id,omitempty"`
	EnvironmentId *int `form:"environment_id,omitempty" json:"environment_id,omitempty"`
}

// CreateRotationPolicyJSONBody defines parameters for CreateRotationPolicy.
type CreateRotationPolicyJSONBody struct {
	AlertDaysBefore *int                              `json:"alert_days_before,omitempty"`
	Description     *string                           `json:"description,omitempty"`
	EnvironmentId   *int                              `json:"environment_id"`
	IntervalDays    int                               `json:"interval_days"`
	Name            string                            `json:"name"`
	NotifyOnBreach  *bool                             `json:"notify_on_breach,omitempty"`
	ProjectId       *int                              `json:"project_id"`
	Scope           CreateRotationPolicyJSONBodyScope `json:"scope"`
}

// CreateRotationPolicyJSONBodyScope defines parameters for CreateRotationPolicy.
type CreateRotationPolicyJSONBodyScope string

// EvaluateRotationPoliciesParams defines parameters for EvaluateRotationPolicies.
type EvaluateRotationPoliciesParams struct {
	ProjectId *int `form:"project_id,omitempty" json:"project_id,omitempty"`
}

// UpdateRotationPolicyJSONBody defines parameters for UpdateRotationPolicy.
type UpdateRotationPolicyJSONBody struct {
	AlertDaysBefore *int    `json:"alert_days_before,omitempty"`
	Description     *string `json:"description,omitempty"`
	IntervalDays    int     `json:"interval_days"`
	IsActive        *bool   `json:"is_active,omitempty"`
	Name            string  `json:"name"`
	NotifyOnBreach  *bool   `json:"notify_on_breach,omitempty"`
}

// AuthLoginJSONBody defines parameters for AuthLogin.
type AuthLoginJSONBody struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// MfaStepUpJSONRequestBody defines body for MfaStepUp for application/json ContentType.
type MfaStepUpJSONRequestBody MfaStepUpJSONBody

// UpdateAuthProfileJSONRequestBody defines body for UpdateAuthProfile for application/json ContentType.
type UpdateAuthProfileJSONRequestBody UpdateAuthProfileJSONBody

// CreatePATJSONRequestBody defines body for CreatePAT for application/json ContentType.
type CreatePATJSONRequestBody CreatePATJSONBody

// CreateDynamicSecretConfigJSONRequestBody defines body for CreateDynamicSecretConfig for application/json ContentType.
type CreateDynamicSecretConfigJSONRequestBody CreateDynamicSecretConfigJSONBody

// ClassifyDynamicSecretConfigJSONRequestBody defines body for ClassifyDynamicSecretConfig for application/json ContentType.
type ClassifyDynamicSecretConfigJSONRequestBody ClassifyDynamicSecretConfigJSONBody

// IssueDynamicSecretLeaseJSONRequestBody defines body for IssueDynamicSecretLease for application/json ContentType.
type IssueDynamicSecretLeaseJSONRequestBody IssueDynamicSecretLeaseJSONBody

// RenewDynamicSecretLeaseJSONRequestBody defines body for RenewDynamicSecretLease for application/json ContentType.
type RenewDynamicSecretLeaseJSONRequestBody RenewDynamicSecretLeaseJSONBody

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody CreateProjectJSONBody

// ActivateBreakGlassJSONRequestBody defines body for ActivateBreakGlass for application/json ContentType.
type ActivateBreakGlassJSONRequestBody ActivateBreakGlassJSONBody

// CreateMachineIdentityJSONRequestBody defines body for CreateMachineIdentity for application/json ContentType.
type CreateMachineIdentityJSONRequestBody CreateMachineIdentityJSONBody

// TransitionMachineIdentityJSONRequestBody defines body for TransitionMachineIdentity for application/json ContentType.
type TransitionMachineIdentityJSONRequestBody TransitionMachineIdentityJSONBody

// CreateOIDCBindingJSONRequestBody defines body for CreateOIDCBinding for application/json ContentType.
type CreateOIDCBindingJSONRequestBody CreateOIDCBindingJSONBody

// IssueMachineTokenJSONRequestBody defines body for IssueMachineToken for application/json ContentType.
type IssueMachineTokenJSONRequestBody IssueMachineTokenJSONBody

// CreateRotationPolicyJSONRequestBody defines body for CreateRotationPolicy for application/json ContentType.
type CreateRotationPolicyJSONRequestBody CreateRotationPolicyJSONBody

// UpdateRotationPolicyJSONRequestBody defines body for UpdateRotationPolicy for application/json ContentType.
type UpdateRotationPolicyJSONRequestBody UpdateRotationPolicyJSONBody

// AuthLoginJSONRequestBody defines body for AuthLogin for application/json ContentType.
type AuthLoginJSONRequestBody AuthLoginJSONBody
