package admin

// init_secure.go -- SECURE-DEFAULT-1: the files the secure-baseline config
// (configs/keyorix.yaml.tpl) references, generated by `admin init` in the run
// that writes that config, so `admin validate --posture` reports zero
// deviations on a fresh install (ADR-112 §4) and the server boots on it.
//
// Only in that run: an existing config is never touched and nothing is
// generated for it (ADR-112: no silent change for existing installs). A file
// that already exists at a referenced path is kept, never overwritten. Nothing
// secret is printed: the token and the private key go to 0600 files only.

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/base64"
	"encoding/pem"
	"errors"
	"fmt"
	"io/fs"
	"math/big"
	"net"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/keyorixhq/keyorix/internal/config"
	"github.com/keyorixhq/keyorix/internal/securefiles"
)

// selfSignedCertValidity: one year and a month, the longest leaf lifetime
// browsers accept (398 days). init prints the expiry date.
const selfSignedCertValidity = 397 * 24 * time.Hour

// metricsTokenBytes of randomness, base64url-encoded (43 characters).
const metricsTokenBytes = 32

// hostnameLabel matches a hostname usable as a DNS SAN.
var hostnameLabel = regexp.MustCompile(`^[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?(\.[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?)*$`)

// generateSecureBaselineFiles creates the TLS certificate/key and the metrics
// token the freshly written config names, skipping any that already exist.
func generateSecureBaselineFiles(cfg *config.Config) error {
	type tlsPair struct{ cert, key string }
	var pairs []tlsPair
	seenPair := map[tlsPair]bool{}
	tokens := map[string]bool{}
	var tokenPaths []string
	for _, inst := range []config.ServerInstanceConfig{cfg.Server.HTTP, cfg.Server.GRPC} {
		if inst.TLS.Enabled && inst.TLS.CertFile != "" && inst.TLS.KeyFile != "" {
			p := tlsPair{inst.TLS.CertFile, inst.TLS.KeyFile}
			if !seenPair[p] {
				seenPair[p] = true
				pairs = append(pairs, p)
			}
		}
		if inst.MetricsTokenFile != "" && !tokens[inst.MetricsTokenFile] {
			tokens[inst.MetricsTokenFile] = true
			tokenPaths = append(tokenPaths, inst.MetricsTokenFile)
		}
	}

	for _, p := range pairs {
		if err := ensureSelfSignedCert(p.cert, p.key); err != nil {
			return err
		}
	}
	for _, p := range tokenPaths {
		if err := ensureMetricsToken(p); err != nil {
			return err
		}
	}
	return nil
}

func fileExists(path string) (bool, error) {
	_, err := os.Lstat(path)
	switch {
	case err == nil:
		return true, nil
	case errors.Is(err, fs.ErrNotExist):
		return false, nil
	default:
		return false, err
	}
}

// ensureSelfSignedCert writes a self-signed ECDSA P-256 server certificate
// for localhost, 127.0.0.1, ::1 and this host's name, unless both files exist.
// One of the two existing without the other is an error: pairing an operator's
// certificate with a generated key (or the reverse) can never work.
func ensureSelfSignedCert(certPath, keyPath string) error {
	certExists, err := fileExists(certPath)
	if err != nil {
		return fmt.Errorf("check %s: %w", certPath, err)
	}
	keyExists, err := fileExists(keyPath)
	if err != nil {
		return fmt.Errorf("check %s: %w", keyPath, err)
	}
	switch {
	case certExists && keyExists:
		fmt.Printf("TLS certificate: keeping the existing %s and %s\n", certPath, keyPath)
		return nil
	case certExists != keyExists:
		return fmt.Errorf("TLS: only one of %s and %s exists; provide both, or remove the other so admin init can generate a matching pair", certPath, keyPath)
	}

	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return fmt.Errorf("generate TLS key: %w", err)
	}
	serial, err := rand.Int(rand.Reader, new(big.Int).Lsh(big.NewInt(1), 128))
	if err != nil {
		return fmt.Errorf("generate certificate serial: %w", err)
	}
	dnsNames := []string{"localhost"}
	if h, herr := os.Hostname(); herr == nil && h != "" && h != "localhost" && hostnameLabel.MatchString(h) {
		dnsNames = append(dnsNames, strings.ToLower(h))
	}
	now := time.Now()
	tmpl := &x509.Certificate{
		SerialNumber:          serial,
		Subject:               pkix.Name{CommonName: "keyorix-server (self-signed by admin init)"},
		NotBefore:             now.Add(-5 * time.Minute),
		NotAfter:              now.Add(selfSignedCertValidity),
		KeyUsage:              x509.KeyUsageDigitalSignature,
		ExtKeyUsage:           []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
		BasicConstraintsValid: true,
		DNSNames:              dnsNames,
		IPAddresses:           []net.IP{net.IPv4(127, 0, 0, 1), net.IPv6loopback},
	}
	der, err := x509.CreateCertificate(rand.Reader, tmpl, tmpl, &key.PublicKey, key)
	if err != nil {
		return fmt.Errorf("create TLS certificate: %w", err)
	}
	keyDER, err := x509.MarshalPKCS8PrivateKey(key)
	if err != nil {
		return fmt.Errorf("encode TLS key: %w", err)
	}

	// Key first: a crash between the two writes leaves a key without a
	// certificate, which the next run reports instead of silently pairing.
	if err := createPrivateFile(keyPath, pem.EncodeToMemory(&pem.Block{Type: "PRIVATE KEY", Bytes: keyDER})); err != nil {
		return fmt.Errorf("write TLS key: %w", err)
	}
	if err := createPrivateFile(certPath, pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: der})); err != nil {
		return fmt.Errorf("write TLS certificate: %w", err)
	}

	absCert, err := filepath.Abs(certPath)
	if err != nil {
		absCert = certPath
	}
	fmt.Printf("TLS certificate: generated a self-signed certificate %s (key %s, both 0600)\n", certPath, keyPath)
	fmt.Printf("   valid until %s for %s, 127.0.0.1, ::1\n", tmpl.NotAfter.UTC().Format("2006-01-02"), strings.Join(dnsNames, ", "))
	fmt.Println("   Trust it in the keyorix CLI with ONE of:")
	fmt.Printf("     keyorix config set ca_file %s\n", absCert)
	fmt.Printf("     export KEYORIX_CA_FILE=%s\n", absCert)
	fmt.Println("   Replace it with a CA-issued certificate (same paths) for production.")
	return nil
}

// ensureMetricsToken writes a random /metrics bearer token unless the file
// exists. The token is never printed.
func ensureMetricsToken(path string) error {
	exists, err := fileExists(path)
	if err != nil {
		return fmt.Errorf("check %s: %w", path, err)
	}
	if exists {
		fmt.Printf("Metrics token: keeping the existing %s\n", path)
		return nil
	}
	raw := make([]byte, metricsTokenBytes)
	if _, err := rand.Read(raw); err != nil {
		return fmt.Errorf("generate metrics token: %w", err)
	}
	if err := createPrivateFile(path, []byte(base64.RawURLEncoding.EncodeToString(raw)+"\n")); err != nil {
		return fmt.Errorf("write metrics token: %w", err)
	}
	fmt.Printf("Metrics token: generated %s (0600, not printed). Scrape /metrics with \"Authorization: Bearer <contents of that file>\".\n", path)
	return nil
}

// createPrivateFile creates path (relative to the working directory, like
// every path in the generated config) at 0600 inside a 0700 directory. It never
// overwrites: O_EXCL plus a per-component no-symlink walk.
func createPrivateFile(path string, data []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return err
	}
	return securefiles.SecureCreateFileSync(".", path, data, 0o600)
}
