apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kxsync.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kxsync.labels" . | nindent 4 }}
data:
  k8s-sync.yaml: |
    keyorix_url: {{ required "keyorix.url is required" .Values.keyorix.url | quote }}
    interval: {{ .Values.keyorix.interval | default "5m" | quote }}
    health_port: {{ .Values.healthPort | default 8080 }}
    mappings:
    {{- if .Values.mappings }}
      {{- toYaml .Values.mappings | nindent 6 }}
    {{- else }}
      []
    {{- end }}
