// cli_migration_doc_test.go -- generates docs/cli-migration.md directly from
// commandCensus (internal/cli/command_census_test.go), the same source of truth
// docs/cli-split-inventory-census.md is generated from, so the migration table
// cannot drift from the census by construction: every commandCensus entry produces
// exactly one row, and TestCLIMigrationDoc fails the build if the committed doc
// doesn't match what commandCensus currently says (a census row added, removed, or
// reclassified without regenerating this doc is a failing build, not a silent gap).
//
// Regenerate with:
//
//	KEYORIX_CLI_MIGRATION_REGEN=1 go test ./internal/cli/ -run TestCLIMigrationDoc
package cli

import (
	"fmt"
	"os"
	"regexp"
	"sort"
	"strings"
	"testing"
)

// migrationBacktickRe extracts a single backtick-quoted command path from a note,
// e.g. "superseded by `login`" -> "login". Used only for censusDropped entries whose
// note names a SPECIFIC replacement command (a rename in disguise -- `connect` ->
// `login`, `connect status` -> `status`) as opposed to a genuine removal with no
// direct successor (e.g. "config set-remote": "superseded by the single credstore
// mechanism", which names a MECHANISM, not a command, and has no backtick span).
var migrationBacktickRe = regexp.MustCompile("`([a-z][a-z0-9_-]*(?: [a-z][a-z0-9-]*)*)`")

// migrationDestination renders the new-CLI/keyorix-server admin destination for one
// census entry. oldPath is the leaf's old-CLI command path (e.g. "system audit").
func migrationDestination(oldPath string, e censusEntry) string {
	switch e.status {
	case censusMoved:
		return fmt.Sprintf("`keyorix %s`", oldPath)
	case censusMovedAdmin:
		// The old CLI's "system" group has no counterpart in keyorix-server admin's own
		// tree -- its commands land as flat admin subcommands ("system audit" -> admin's
		// own "audit"). "encryption ..." keeps its path unchanged: admin has its own
		// "encryption" subgroup with the same shape. These are the only two prefixes
		// commandCensus's censusMovedAdmin entries use (see command_census_test.go's own
		// list) -- if a future entry uses a third, this mapping silently mis-derives its
		// destination, which is exactly what cli/cmd's and server/admin's own
		// quickstart_commands_test.go guards catch downstream (a generated destination
		// that isn't a real command fails there, not silently here).
		newPath := strings.TrimPrefix(oldPath, "system ")
		return fmt.Sprintf("`keyorix-server admin %s`", newPath)
	case censusMovedOut:
		return fmt.Sprintf("moved out (separate tool) -- %s", firstNonEmpty(e.note, e.ref))
	case censusDropped:
		if m := migrationBacktickRe.FindStringSubmatch(e.note); m != nil {
			return fmt.Sprintf("removed; use `keyorix %s` instead", m[1])
		}
		return fmt.Sprintf("removed -- %s", firstNonEmpty(e.note, e.ref))
	case censusGap:
		return "not yet available -- open gap, see docs/cli-split-inventory.md §9"
	default:
		return "unknown"
	}
}

func firstNonEmpty(vals ...string) string {
	for _, v := range vals {
		if v != "" {
			return v
		}
	}
	return "(no reason recorded)"
}

// TestCLIMigrationDoc is the guard described in this file's header.
func TestCLIMigrationDoc(t *testing.T) {
	want := renderMigrationDoc()

	path := "../../docs/cli-migration.md"
	got, err := os.ReadFile(path) // #nosec G304 -- fixed relative path
	if os.Getenv("KEYORIX_CLI_MIGRATION_REGEN") == "1" {
		if werr := os.WriteFile(path, []byte(want), 0o600); werr != nil { // #nosec G306 -- dev-only regen tool, not a runtime path
			t.Fatalf("writing %s: %v", path, werr)
		}
		t.Logf("regenerated %s (%d commands)", path, len(commandCensus))
		return
	}
	if err != nil {
		t.Fatalf("reading %s: %v (run KEYORIX_CLI_MIGRATION_REGEN=1 go test ./internal/cli/ -run TestCLIMigrationDoc to create it)", path, err)
	}
	if string(got) != want {
		t.Errorf("docs/cli-migration.md is out of date with commandCensus -- run "+
			"`KEYORIX_CLI_MIGRATION_REGEN=1 go test ./internal/cli/ -run TestCLIMigrationDoc` "+
			"and commit the result (%d bytes committed, %d bytes generated)", len(got), len(want))
	}
}

func renderMigrationDoc() string {
	paths := make([]string, 0, len(commandCensus))
	for p := range commandCensus {
		paths = append(paths, p)
	}
	sort.Strings(paths)

	var b strings.Builder
	b.WriteString("# CLI migration: old command -> new command\n\n")
	b.WriteString("<!-- generated by: KEYORIX_CLI_MIGRATION_REGEN=1 go test ./internal/cli/ -run TestCLIMigrationDoc -->\n")
	b.WriteString("<!-- do not hand-edit; edit internal/cli/command_census_test.go's commandCensus map instead -->\n\n")
	b.WriteString("Every command the old, thick CLI (`internal/cli`, no longer a release asset as of the " +
		"Phase 5 switch -- see `make keyorix-legacy` for the rollback build) supported, and where it " +
		"lives now: the new thin CLI (`keyorix ...`), a host-side `keyorix-server admin ...` command, a " +
		"separate tool, or removed outright. Generated directly from the same `commandCensus` map that " +
		"[`docs/cli-split-inventory-census.md`](cli-split-inventory-census.md) is generated from, so this " +
		"table cannot drift from that census -- `internal/cli/cli_migration_doc_test.go`'s " +
		"`TestCLIMigrationDoc` fails the build otherwise.\n\n")
	fmt.Fprintf(&b, "%d old-CLI commands.\n\n", len(paths))
	b.WriteString("| Old command | New | Reference | Note |\n")
	b.WriteString("|---|---|---|---|\n")
	for _, p := range paths {
		e := commandCensus[p]
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s |\n", p, migrationDestination(p, e), e.ref, e.note)
	}
	return b.String()
}
