// inventory_regen_test.go regenerates inventory_registry_generated_test.go from
// the LIVE route/method set. It never runs as part of a normal `go test` pass —
// only when explicitly invoked with REGEN_INVENTORY=1, so a new mutating
// route/method landing on main can't silently make itself "known": the ratchet
// test (inventory_ratchet_test.go) fails until a human runs this AND commits the
// diff, which a PR reviewer sees.
package faultops

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"testing"
)

const generatedRegistryPath = "inventory_registry_generated_test.go"

func TestRegenerateInventoryRegistry(t *testing.T) {
	if os.Getenv("REGEN_INVENTORY") == "" {
		t.Skip("set REGEN_INVENTORY=1 to regenerate " + generatedRegistryPath)
	}
	keys := liveOperationKeys(t)

	var buf bytes.Buffer
	buf.WriteString("// Code generated by TestRegenerateInventoryRegistry (REGEN_INVENTORY=1); DO NOT EDIT.\n")
	buf.WriteString("// This is the closed set of mutating operations inventory_ratchet_test.go checks\n")
	buf.WriteString("// the live server against. A new key here with no matching entry in\n")
	buf.WriteString("// inventory_overrides_test.go defaults to StatusPending (an honest, tracked gap,\n")
	buf.WriteString("// not a silent one) — see inventory_overrides_test.go to promote it.\n")
	buf.WriteString("package faultops\n\n")
	fmt.Fprintf(&buf, "var knownOperations = map[string]bool{\n")
	for _, k := range keys {
		fmt.Fprintf(&buf, "\t%q: true,\n", k)
	}
	buf.WriteString("}\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		t.Fatalf("gofmt generated registry: %v", err)
	}
	if err := os.WriteFile(generatedRegistryPath, formatted, 0o644); err != nil {
		t.Fatalf("writing %s: %v", generatedRegistryPath, err)
	}
	t.Logf("wrote %d known operation keys to %s", len(keys), generatedRegistryPath)
}
