// generated_code_test.go — #1541: scripts/ci-test-legs.sh's C5 exclusion
// table marks this package PERMANENT with the reason "auto-generated
// protobuf code (DO NOT EDIT), no tests to write." That claim was asserted
// in a comment, not verified — every OTHER C5 exemption (TEMPORARY's 30-day
// freshness check, the leg-completeness assertion) is a machine-checked
// invariant.
//
// #1541 itself proposed a weaker property: confirm server/proto/pb has zero
// *_test.go files. That's a proxy, not the actual claim — a hand-written
// *non-test* file (a custom marshaler, a wrapper, exactly the example the
// issue itself gives) would slip through a "zero test files" check
// entirely while genuinely breaking the PERMANENT exemption's premise. The
// property this file actually asserts is the real claim: every .go file in
// this package (other than this one) carries a real
// "Code generated by ... DO NOT EDIT." header — i.e. it IS generated code,
// not just untested code. This is strictly stronger: it would catch a
// hand-written non-test file the zero-test-files check would miss, and it
// subsumes the zero-test-files check too (a hand-written *_test.go file
// wouldn't carry the header either, so it fails this check the same way).
//
// This file's own existence is the direct consequence of closing this
// gap correctly: server/proto/pb no longer has zero *_test.go files (this
// IS one), which is expected and correct, not a regression — the whole
// point was that "zero test files" was never the right signal to protect in
// the first place. See scripts/ci-test-legs.sh's exclusion_entries() comment
// (this same commit) for why the PERMANENT/never-run-in-CI exclusion for
// this package was removed once it gained a real, meaningful test to run.
package pb

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// generatedCodeHeaderMarkers are the exact header lines Go's own protoc
// plugins emit — see keyorix.pb.go ("Code generated by protoc-gen-go. DO NOT
// EDIT.") and keyorix_grpc.pb.go ("Code generated by protoc-gen-go-grpc. DO
// NOT EDIT."). A future third plugin would emit its own "Code generated by
// X. DO NOT EDIT." line — checking for the "Code generated by" prefix (not
// the exact two strings on record today) covers that without needing an
// update here, matching the standard Go tooling convention
// (https://go.dev/s/generatedcode) that gofmt/goimports/govet themselves
// recognize by this same prefix.
const generatedCodeHeaderPrefix = "// Code generated by"

// TestEveryFileIsGenerated is #1541's guard: every .go file in this package
// other than this test file itself must carry a real
// "// Code generated by ... DO NOT EDIT." header on one of its first few
// lines (Go's own generated-code convention places it as the first line,
// but this checks a small window in case a build-tag or copyright line ever
// precedes it). A hand-written file added to this package — test or not —
// fails this immediately, forcing the PERMANENT CI exclusion back into
// review exactly as #1541 asked, rather than silently continuing to exclude
// a package that now has real, uncovered logic.
func TestEveryFileIsGenerated(t *testing.T) {
	entries, err := os.ReadDir(".")
	if err != nil {
		t.Fatalf("reading server/proto/pb: %v", err)
	}

	const headerScanLines = 5
	var missing []string
	var checked int
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, ".go") || name == "generated_code_test.go" {
			continue
		}
		checked++
		b, err := os.ReadFile(filepath.Join(".", name))
		if err != nil {
			t.Fatalf("reading %s: %v", name, err)
		}
		lines := strings.SplitN(string(b), "\n", headerScanLines+1)
		if len(lines) > headerScanLines {
			lines = lines[:headerScanLines]
		}
		found := false
		for _, line := range lines {
			if strings.HasPrefix(line, generatedCodeHeaderPrefix) {
				found = true
				break
			}
		}
		if !found {
			missing = append(missing, name)
		}
	}

	if checked == 0 {
		t.Fatal("found zero non-test .go files in server/proto/pb — the directory listing broke, or every " +
			"generated file was deleted; fix the test before trusting it either way")
	}
	if len(missing) > 0 {
		t.Errorf("%d file(s) in server/proto/pb have no \"Code generated by ... DO NOT EDIT.\" header in their "+
			"first %d lines, so this package is no longer provably all-generated: %v\n"+
			"This breaks the premise scripts/ci-test-legs.sh's PERMANENT exclusion for server/proto/pb$ rests on "+
			"(\"auto-generated protobuf code, no tests to write\"). Either regenerate the file so it carries the "+
			"standard protoc-plugin header, move any genuinely hand-written logic to a different package, or — if "+
			"hand-written code in this package is now intentional — remove the PERMANENT exclusion in "+
			"scripts/ci-test-legs.sh and let this package run in CI like any other.",
			len(missing), headerScanLines, missing)
	}
}
