# keyorix_template.yaml
# Default configuration template for Keyorix.
#
# ============================================================================
# SECURE BASELINE (ADR-112 §4, SECURE-DEFAULT-1): `keyorix-server admin
# validate --posture` reports zero deviations on this file as written by
# `keyorix-server admin init`. In the same run, init generates the files it
# references (and never prints their contents):
#   certs/server.crt, certs/server.key  self-signed TLS certificate (0600)
#   secrets/metrics_token              random /metrics bearer token (0600)
# Replace the self-signed certificate with a CA-issued one for production
# (same paths, or change cert_file/key_file). Copying this file by hand
# without those files makes the server refuse to start (fail closed).
#
# For a throwaway local demo, `keyorix-server admin init --dev` writes a
# relaxed development-only variant instead (no TLS, no rate limit, no metrics
# token), labelled as such at the top of the file.
# ============================================================================
#
# IMPORTANT: Never store API keys or credentials directly in this file.
# Use environment variables instead:
#   KEYORIX_API_KEY        - API key for client authentication
#   KEYORIX_REMOTE_API_KEY - API key for remote storage backend

locale:
  # Primary language for the application interface
  # Supported languages: en (English), ru (Russian), es (Spanish), fr (French), de (German)
  language: "en"
  
  # Fallback language when translations are missing in the primary language
  # Should be one of the supported languages, typically "en" for maximum compatibility
  fallback_language: "en"

server:
  http:
    # Enable HTTP server
    enabled: true
    port: "8080"
    tls:
      # TLS on the HTTP listener. admin init generated a self-signed certificate
      # at these paths; point them at a CA-issued certificate for production. To
      # terminate TLS at a reverse proxy instead, see docs/SELF_HOSTING.md.
      enabled: true
      cert_file: "certs/server.crt"     # Path to TLS certificate
      key_file: "certs/server.key"      # Path to TLS key
      # Optional TLS 1.2 cipher suite allowlist, by name (e.g.
      # "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"). Empty/unset keeps the built-in secure
      # AEAD-only default. Only modern AEAD suites are accepted (RC4/3DES/CBC-mode
      # suites are rejected at startup); TLS 1.3 negotiates its own suites and is
      # unaffected by this list.
      allowed_ciphers: []
    ratelimit:
      # Per-principal API rate limiting. Same values as server/config/production.yaml;
      # 10/20 throttled an ordinary CLI session (QUICK_START, scripts/smoke.sh) with 429s.
      enabled: true
      requests_per_second: 50
      burst: 100
    # GET /metrics requires "Authorization: Bearer <token>", the token being this
    # file's contents (generated by admin init, 0600, never printed). An unreadable
    # file refuses to start. metrics_token: "<value>" sets it inline instead.
    metrics_token_file: "secrets/metrics_token"

  grpc:
    # gRPC server — PARTIAL SURFACE, WORK IN PROGRESS. Prefer HTTP.
    #
    # gRPC is a data-plane interface (13 services, 86 RPCs): secrets, users, roles,
    # groups, projects, machine identities, leases, break-glass, and audit/compliance
    # reads. HTTP is the complete interface and the only feature-complete one.
    #
    # Governance and identity capabilities are HTTP-only today. Among them:
    # classification and description on secrets, MFA and step-up, SSO/SAML/SCIM,
    # WebAuthn, personal access tokens, access-review campaigns, access requests,
    # segregation of duties, legal hold, risk exceptions, secret templates, bulk
    # operations, ownership, access schedules, and retention override.
    #
    # This does NOT weaken enforcement. Authorization, audit, and the classification
    # read gate live in core and apply to every transport, so gRPC cannot bypass a
    # control that HTTP enforces. Secrets classified `restricted` are simply
    # unreadable over gRPC when step-up is required, because gRPC has no step-up —
    # that is fail-closed by design.
    #
    # The real limitation is that some controls cannot be *set* over gRPC, so an
    # object created here lands in the least-governed state available. If your
    # deployment has compliance requirements, provision over HTTP.
    #
    # Capability parity with HTTP is a planned project; the scope, the deliberate
    # HTTP-only exclusions, and the phasing are in
    # docs/adr-105-grpc-scope-and-parity.md.
    enabled: false
    port: "9090"
    tls:
      enabled: true
      cert_file: "certs/server.crt"
      key_file: "certs/server.key"
      # See server.http.tls.allowed_ciphers above — same semantics for gRPC.
      allowed_ciphers: []
    ratelimit:
      enabled: true
      requests_per_second: 25
      burst: 50
    metrics_token_file: "secrets/metrics_token"

storage:
  type: sqlite  # options: sqlite, postgres. For PostgreSQL change THIS line to "type: postgres" (the backend selector is storage.type, not a key under database:)

  database:
    # SQLite (default — zero infrastructure required)
    path: "keyorix.db"

    # PostgreSQL (recommended for production): set storage.type: postgres above, then
    # uncomment ONE of the options below (and drop "path" — it is SQLite-only).
    # Option A — full DSN:
    # dsn: "host=localhost user=keyorix dbname=keyorix port=5432 sslmode=require"
    # Option B — field by field:
    # host: localhost
    # port: "5432"
    # name: keyorix
    # user: keyorix
    # password: ""  # use KEYORIX_DB_PASSWORD environment variable instead
    # ssl_mode: require  # always use require or verify-full in production

    # Connection pool. Leave max_open_conns unset to get the measured default for
    # your storage.type: 8 for SQLite, 25 for Postgres (#2631; docs/CONFIGURATION.md
    # has the measurements). On Postgres keep (replicas x max_open_conns) below the
    # server's max_connections minus superuser_reserved_connections, or requests fail
    # with SQLSTATE 53300 "too many clients". The server warns at boot when a single
    # pool already exceeds it.
    # max_open_conns: 8
    # max_idle_conns defaults to the effective max_open_conns, so an opened
    # connection stays warm instead of being closed and re-opened (SESSION-PERF,
    # #2403 follow-up). Set it only to deliberately keep fewer idle.
    # max_idle_conns: 8
    conn_max_lifetime_minutes: 30

  encryption:
    # Enable envelope encryption
    enabled: true
    # DEK (Data Encryption Key), wrapped with a passphrase-derived KEK by
    # default. See key_provider (internal/config/config.go's KeyProviderConfig
    # doc comment, ADR-038/ADR-041) to source the KEK from a file, env var,
    # exec command, Shamir shares, a host TPM, or a cloud KMS instead of a
    # passphrase -- omitted here to keep the default behaviour unchanged.
    dek_path: "keys/dek.key"
    salt_path: "keys/kek.salt"

secrets:
  chunking:
    # Enable chunking large secrets into smaller parts
    enabled: true
    max_chunk_size_kb: 64
    max_chunks_per_secret: 10

  limits:
    # Maximum number of secrets per user
    max_secrets_per_user: 1000

security:
  # Check file permission safety on startup
  enable_file_permission_check: true
  auto_fix_file_permissions: true
  allow_unsafe_file_permissions: false
  # Require a second factor (TOTP or passkey) for interactive login (ADR-112: on by
  # default). The first admin login is confined to MFA enrolment until it enrols
  # (`keyorix mfa enroll` / `keyorix mfa activate`, or Profile -> Security in the web
  # UI). Tokens and machine credentials are unaffected.
  require_mfa: true
  # Refuse to start an enabled HTTP/gRPC listener without TLS, rather than serve
  # credentials/secrets in cleartext (#G36/#G37). Keep it on; if a TLS-terminating
  # proxy fronts the listener, see docs/SELF_HOSTING.md.
  require_transport_tls: true

password_policy:
  # Rules enforced when a user sets a new password (e.g. self-service change).
  # Omit this whole block to use the conservative built-in defaults (shown
  # below). Lab installs may relax these, e.g. min_length: 8 and the require_*
  # flags false.
  min_length: 16
  require_uppercase: true
  require_lowercase: true
  require_digit: true
  require_special: true
  reject_personal_info: true     # reject if it contains the user's username/email/display name
  reject_common_passwords: true  # reject passwords on the curated common-password denylist
  history_count: 5               # forbid reusing the last N passwords (0 = off)
  max_age_days: 0                # expire a password after N days (0 = never; login flags it)

soft_delete:
  # Soft-deletion is built in for users/projects/environments (DELETE sets
  # deleted_at; restore endpoints clear it). retention_days is the grace period
  # the purge scheduler below honours before a soft-deleted row is permanently
  # removed (default 30).
  enabled: true
  retention_days: 30

purge:
  # ADR-032 retention purge. When enabled, a background job permanently deletes
  # soft-deleted users/projects/environments whose deleted_at is older than
  # soft_delete.retention_days. This is IRREVERSIBLE — opt-in (default off).
  enabled: false
  # Run interval as a Go duration (e.g. "24h", "6h"). Default 24h.
  schedule: "24h"

audit:
  # Native SIEM push: forward every audit event to an external SIEM.
  # Audit events carry no plaintext secret values, so they are safe to ship.
  siem:
    enabled: false
    # provider: splunk | datadog | webhook
    provider: "splunk"
    # Full destination URL (e.g. a Splunk HEC collector endpoint).
    endpoint: ""
    # HEC token / DD-API-KEY / bearer token. Prefer the KEYORIX_SIEM_TOKEN env var.
    token: ""
    # Skip TLS verification for self-signed SIEM endpoints (not recommended).
    insecure_skip_verify: false

# Self-service emergency access ("break-glass"). OFF by default: until you enable
# it, `keyorix break-glass activate` is refused with "break-glass is not enabled".
# When on, a member of a project (a role scoped to that project) can grant
# themselves emergency_role there for a limited time, with a justification; every
# use is audited. See docs/CONFIGURATION.md#break_glass.
# break_glass:
#   enabled: true
#   emergency_role: "project_developer"
#   default_ttl: "4h"
#   max_ttl: "24h"

membership:
  # Project membership onboarding (ADR-022). validation_mode controls how a new
  # invite onboards into a project:
  #   open      - invite is active immediately (self-serve)
  #   allowlist - an admin steps the membership through each lifecycle state
  #   idp       - IdP-resolved users skip the early states; others start invited
  validation_mode: "allowlist"

session:
  # Short-lived session tokens with silent auto-refresh. Omit this whole block to
  # keep the backward-compatible behaviour: a 24h access window and no absolute
  # ceiling (a session can be refreshed indefinitely).
  #
  # access_ttl is how long an issued token is valid before the client must call
  # POST /auth/refresh (which rotates the token and starts a new window). The login
  # and refresh responses return `expires_at` so the client can refresh just before
  # it lapses.
  access_ttl: "24h"
  # absolute_ttl caps total session lifetime from login. Refreshing the access
  # window can never extend a session past it — once reached, refresh is refused
  # and the user must re-authenticate. Empty or "0" = no ceiling. The login/refresh
  # responses return `absolute_expires_at` when a ceiling is set.
  #
  # Recommended short-lived configuration (used by default here — #G37; set to ""
  # to restore the old unbounded-refresh behaviour):
  #   access_ttl: "30m"
  #   absolute_ttl: "12h"
  absolute_ttl: "12h"
