#!/usr/bin/env bash
# scripts/ci-test-legs.sh — single source of truth for which Go packages each
# CI test-suite matrix leg (.github/workflows/ci.yml) runs, and which packages
# are deliberately excluded from every leg, with a reason.
#
# G80 campaign, C5: before this file existed, the exclusion patterns lived
# only as bare `grep -v` flags in ci.yml with a comment pointing at
# `git log -S` for the reason -- exactly the shape that let server/http sit
# excluded, with no leg anywhere, for ~4 months, invisible to anyone not
# already reading that file's history. This file is sourced by BOTH the
# test-suite matrix step and the leg-completeness assertion job, so the two
# can never silently drift apart -- a package pinned to a leg here is pinned
# for both; a pattern excluded here is excluded for both.
#
# Not executable on its own: `source` this file, then call its functions.

# exclusion_entries: one per line, pipe-delimited:
#   <go-list-suffix-regex>|<kind>|<reason>|<issue>|<date-added:YYYY-MM-DD>
#
# kind is one of:
#   TEMPORARY -- a real gap meant to close. Subject to the 30-day freshness
#     check in ci.yml: an entry older than 30 days fails CI outright, so a
#     stale exclusion cannot simply sit forever unnoticed the way the
#     pre-C5 bare grep -v list did.
#   PERMANENT -- structurally correct forever (generated code with nothing
#     to test). No fix will ever "land" for this, so it is exempt from the
#     freshness check.
#   SHARDED -- NOT a coverage gap. The package runs, just via its own
#     dedicated matrix leg(s) below (server/http/handlers -> handlers-1..4)
#     rather than through root_base()'s catch-all. Excluded from root_base's
#     package list (so it isn't ALSO run there, doubling the work) but
#     included back into the completeness union via its dedicated leg(s).
#     Exempt from the freshness check for the same reason as PERMANENT: it
#     is not a gap to close.
#
# date-added is when an entry was captured in THIS structured, enforced
# table -- not necessarily when the underlying exclusion was first added to
# ci.yml. The three TEMPORARY entries below trace back to a bare `grep -v`
# added 2026-04-27 (commit 7ccb7dda) -- see their linked issues for that
# history -- but are dated here 2026-08-23, the day this ratchet was
# introduced (G80 C5). Back-dating them to 2026-04-27 would fail the
# freshness check on the PR that introduces the check itself, which is not
# the failure mode this check exists to catch (a NEW exclusion sitting
# unreviewed for 30+ days going forward); the ~4-month-old debt itself is
# not hidden -- it's on record in #1533/#1534/#1535 and in this comment.
#
# server/proto/pb$ PERMANENT entry REMOVED 2026-08-28 (#1541): its own
# justification ("auto-generated protobuf code, no tests to write") was
# asserted, not verified. server/proto/pb/generated_code_test.go now
# machine-checks the real claim -- every non-test .go file in that package
# carries a genuine "Code generated by ... DO NOT EDIT." header -- which is
# strictly stronger than #1541's own originally-proposed "zero *_test.go
# files" check (a hand-written non-test file, e.g. a custom marshaler, would
# slip through that weaker check while genuinely breaking the exemption's
# premise). Adding that test means the package no longer has "no tests to
# write" -- it has exactly one, and a meaningful one -- so the PERMANENT,
# never-run-in-CI exclusion no longer applies: the package now falls through
# to root_base()'s normal catch-all (root-4) like any other package, and its
# one real test runs there.
exclusion_entries() {
  cat <<'EOF'
server/http$|SHARDED|runs in its own dedicated http-1..6 matrix legs below (G80 C4, 2026-08-23) -- see #1535 for the ~4-month exclusion history this closes|#1535|2026-08-23
server/http/handlers$|SHARDED|runs in its own dedicated handlers-1..4 matrix legs below|n/a|2026-04-27
EOF
}

# coverage_floor_exclusions: SAME shape and discipline as exclusion_entries()
# above (pipe-delimited <pattern>|<kind>|<reason>|<issue>|<date-added>, kind
# TEMPORARY/PERMANENT, TEMPORARY subject to the same 30-day freshness check),
# but a DIFFERENT axis: exclusion_entries() controls whether a PACKAGE runs in
# any CI leg at all; this controls whether coverage.out LINES matching
# <pattern> (a package that DOES run) are filtered out of the coverage-FLOOR
# sum specifically ("Merge coverage profiles", ci.yml). A package excluded
# here still runs, still gets tested, still gets its own coverage.out lines --
# those lines are just not counted toward the floor. A package excluded via
# exclusion_entries() never reaches coverage.out in the first place, so an
# entry here for it would be inert -- the two tables are disjoint by
# construction, not by convention.
#
# server/proto/pb's *.pb.go PERMANENT entry replaces what was, before this
# table existed, only a bare `grep -v '\.pb\.go:'` in ci.yml with a prose
# comment restating the reasoning inline (added alongside #1541, G80 Wave 1,
# 2026-08-25) -- the exact "asserted, not machine-checked" shape #1541's own
# comment above criticizes scripts/ci-test-legs.sh for having FIXED, applied
# here to itself: the reasoning now lives in one enforced place instead of a
# comment nobody re-reads.
coverage_floor_exclusions() {
  cat <<'EOF'
\.pb\.go:|PERMANENT|generated protobuf/gRPC code (protoc-gen-go/protoc-gen-go-grpc), ~16.7k lines, ~0% covered by design -- its one real test (server/proto/pb/generated_code_test.go's TestEveryFileIsGenerated) checks file headers, not the generated marshal/unmarshal/gRPC logic itself; same principle gosec's own -exclude-generated flag already applies to this same package|#1541|2026-08-25
EOF
}

# coverage_floor_grep_patterns: just the regex column, for ci.yml's "Merge
# coverage profiles" step to build its `grep -v` args from -- so the pattern
# lives in exactly one place instead of the registry and the grep flag
# drifting apart.
coverage_floor_grep_patterns() {
  coverage_floor_exclusions | cut -d'|' -f1
}

# check_coverage_floor_exclusion_freshness: same discipline as
# check_exclusion_freshness below, applied to coverage_floor_exclusions
# instead of exclusion_entries.
check_coverage_floor_exclusion_freshness() {
  local today_epoch failed=0
  today_epoch=$(date -u -d "$(date -u +%Y-%m-%d)" +%s)
  while IFS='|' read -r pattern kind reason issue added; do
    [ "$kind" = "TEMPORARY" ] || continue
    local added_epoch age_days
    added_epoch=$(date -u -d "$added" +%s)
    age_days=$(( (today_epoch - added_epoch) / 86400 ))
    if [ "$age_days" -gt 30 ]; then
      echo "STALE COVERAGE-FLOOR EXCLUSION (${age_days}d > 30d budget): $pattern -- $reason ($issue, added $added)"
      failed=1
    fi
  done < <(coverage_floor_exclusions)
  return $failed
}

# exclusion_patterns: just the regex column, one per line -- the set of
# patterns root_base() excludes from the root/core legs entirely (every kind:
# a SHARDED package must not ALSO run via root_base's catch-all, even though
# it runs elsewhere).
exclusion_patterns() {
  exclusion_entries | cut -d'|' -f1
}

# never_run_patterns: exclusion_patterns filtered to kinds that mean "this
# package runs in NO leg, anywhere" (TEMPORARY, PERMANENT) -- excludes
# SHARDED, which does run, just not via root_base. This is the set the
# leg-completeness assertion subtracts from `go list ./...`.
never_run_patterns() {
  exclusion_entries | awk -F'|' '$2 != "SHARDED" { print $1 }'
}

# root_base: every package eligible for the root-N/core legs -- go list
# minus every exclusion pattern (all kinds; a SHARDED package must not
# double-run here even though it's covered elsewhere).
root_base() {
  local args=()
  while IFS= read -r pattern; do
    args+=(-e "$pattern")
  done < <(exclusion_patterns)
  go list ./... | grep -v "${args[@]}"
}

# Pinned "heavy" package lists for root-1/2/3 and core (bin-packed by
# measured per-package time -- see ci.yml's own comments for the
# measurement history). Keep these four lists in sync with root-4's
# implicit catch-all below: a package listed in one of these must not
# ALSO be pinned to another, and root-4 is defined as everything else.
root_1_pkgs() {
  cat <<'EOF'
github.com/keyorixhq/keyorix/internal/encryption
github.com/keyorixhq/keyorix/server/grpc/services
github.com/keyorixhq/keyorix/internal/cli/invite
github.com/keyorixhq/keyorix/internal/cli/group
github.com/keyorixhq/keyorix/internal/cli/run
github.com/keyorixhq/keyorix/internal/crypto
github.com/keyorixhq/keyorix/server/grpc
github.com/keyorixhq/keyorix/internal/testhelper
github.com/keyorixhq/keyorix/internal/cli/accessreview
github.com/keyorixhq/keyorix/internal/cli/anomalies
github.com/keyorixhq/keyorix/internal/cli/auth
github.com/keyorixhq/keyorix/internal/bundle
github.com/keyorixhq/keyorix/internal/rotation
github.com/keyorixhq/keyorix/internal/cli/license
github.com/keyorixhq/keyorix/internal/cli/config
github.com/keyorixhq/keyorix/cmd/validate-translations
github.com/keyorixhq/keyorix/internal/startup
github.com/keyorixhq/keyorix/internal/di
github.com/keyorixhq/keyorix/server/webui
EOF
}

root_2_pkgs() {
  cat <<'EOF'
github.com/keyorixhq/keyorix/internal/cli/user
github.com/keyorixhq/keyorix/internal/cli/encryption
github.com/keyorixhq/keyorix/internal/storage
github.com/keyorixhq/keyorix/internal/cli/share
github.com/keyorixhq/keyorix/server/grpc/interceptors
github.com/keyorixhq/keyorix/internal/cli/common
github.com/keyorixhq/keyorix/internal/cli/hygiene
github.com/keyorixhq/keyorix/internal/cli/sod
github.com/keyorixhq/keyorix/internal/cli/breakglass
github.com/keyorixhq/keyorix/internal/cli/audit
github.com/keyorixhq/keyorix/internal/saml
github.com/keyorixhq/keyorix/internal/i18n
github.com/keyorixhq/keyorix/internal/notary
github.com/keyorixhq/keyorix/internal/securefiles
github.com/keyorixhq/keyorix/internal/trust
github.com/keyorixhq/keyorix/internal/license
github.com/keyorixhq/keyorix/internal/cli/trust
github.com/keyorixhq/keyorix/internal/crypto/awskms
github.com/keyorixhq/keyorix/internal/utils/safeconv
EOF
}

root_3_pkgs() {
  cat <<'EOF'
github.com/keyorixhq/keyorix/server/tools
github.com/keyorixhq/keyorix/internal/cli/machine
github.com/keyorixhq/keyorix/server
github.com/keyorixhq/keyorix/internal/cli/rbac
github.com/keyorixhq/keyorix/internal/cli/project
github.com/keyorixhq/keyorix/internal/cli/status
github.com/keyorixhq/keyorix/internal/notifychan
github.com/keyorixhq/keyorix/internal/cli/risk
github.com/keyorixhq/keyorix/internal/cli/rotation
github.com/keyorixhq/keyorix/internal/cli/dynamic
github.com/keyorixhq/keyorix/internal/audit/siem
github.com/keyorixhq/keyorix/internal/mcp
github.com/keyorixhq/keyorix/internal/cli/bundle
github.com/keyorixhq/keyorix/server/validation
github.com/keyorixhq/keyorix/internal/connect
github.com/keyorixhq/keyorix/internal/config
github.com/keyorixhq/keyorix/internal/storage/models
github.com/keyorixhq/keyorix/internal/delivery
github.com/keyorixhq/keyorix/internal/core/storage
EOF
}

core_pkgs() {
  echo "github.com/keyorixhq/keyorix/internal/core"
}

# storage_store_pkgs: internal/storage/store gets its own pinned leg (added
# 2026-09-04) for the same reason internal/core did -- it grew large enough in
# root-4's catch-all to threaten that leg's timeout budget. Measured directly:
# a real CI run (main, commit b971ed36) had root-4's own `go test` step take
# 1363s against its 1800s timeout (76% of budget, ~437s headroom) -- well past
# the ~569s root-4 measured at when that budget was last calibrated (see the
# root-1/2/3/4 comment block below). Isolating internal/storage/store alone
# (go test -timeout 20m ./internal/storage/store/..., no -race, single local
# run) took 867.818s BY ITSELF, confirming it as the dominant contributor
# growing root-4 past its old baseline -- the package picked up a large batch
# of new *_cascade_sweep_test.go/*_error_sweep_test.go coverage files since
# root-4 was last measured. Same treatment as core: its own 1800s-timeout leg
# rather than tuned tight to the observed duration, so a healthy-but-slow run
# never trips it (see the "unused headroom costs nothing" reasoning in the
# root-1/2/3/4 comment block below, which applies identically here).
storage_store_pkgs() {
  echo "github.com/keyorixhq/keyorix/internal/storage/store"
}

# root_4_pkgs: the dynamic catch-all -- every root_base() package not pinned
# to root-1/2/3/core/storage-store above, so a newly added package always
# lands somewhere (root-4) rather than silently running nowhere.
root_4_pkgs() {
  local pinned
  pinned=$(cat <(root_1_pkgs) <(root_2_pkgs) <(root_3_pkgs) <(core_pkgs) <(storage_store_pkgs) | sort -u)
  comm -23 <(root_base | sort -u) <(echo "$pinned")
}

# handlers_pkg: the single package every handlers-1..4 leg shards by test
# name, not by package -- for leg-completeness purposes (which only cares
# about PACKAGE coverage) all four legs collectively cover exactly this one
# package.
handlers_pkg() {
  echo "github.com/keyorixhq/keyorix/server/http/handlers"
}

# http_pkg: the single package every http-1..6 leg shards by test name, not
# by package (G80 C4) -- same reasoning as handlers_pkg above, but see
# http_shard_N_tests() below for how the split is actually computed: unlike
# handlers_pkg (mod-N hash, no per-test timing data), server/http turned out
# to have real, measurable per-test outliers, so it's pinned by measured
# time instead -- see that comment block for the full story. 6 shards, not
# 4: measured 1904.015s local (-race, unsharded, single run -- see
# docs/g80-remediation-notes.md) with zero failures beyond the two
# already-fixed-on-main C1-scope fixtures, confirming server/http is healthy
# and slow, not deadlocked. 1904.015s * ~1.7 (local->runner factor) ~=
# 3237s runner-equivalent; 6 shards puts each at ~540s, ~30% of the 1800s
# per-leg timeout budget -- comfortably under the "roughly a third" target
# with real headroom, matching every other leg's generous-budget precedent
# (see the timeout-raise comment above).
http_pkg() {
  echo "github.com/keyorixhq/keyorix/server/http"
}

# http_shard_1..5_tests: pinned test-NAME lists for http-1..5 (not package
# lists -- server/http is one package), bin-packed by REAL measured per-test
# elapsed time, mirroring root-1/2/3's pinned-by-measured-package-time
# precedent one level down at test granularity instead of package
# granularity. Superseded the original mod-6-by-sorted-name-index split
# (2026-08-23, same mechanism handlers-1..4 still uses) once CI actually
# showed it landing unevenly: http-4 measured ~1180s against a ~953s
# 6-shard average (max/min spread 765s-1180s, ~54% top-to-bottom) --
# handlers' own "no per-test outliers, split evenly by hash" reasoning
# (see handlers_pkg's case-statement comment) turned out not to hold for
# server/http, so the fix is the same one root-1/2/3 already used for
# exactly this failure mode: measure, then pin the real weights instead of
# assuming they're uniform.
#
# Measured 2026-08-29 via `go test -race -json ./server/http` (a real,
# unsharded, -run-unrestricted run -- not extrapolated from the sharded
# CI numbers above): 440 of 461 top-level tests got a recorded per-test
# Elapsed time before the run hit an unrelated, pre-existing local-only
# failure (TestIsUserNotFound_RealBothBackends needs live infra this
# environment doesn't have -- see this repo's own catalogued local-only
# test gaps; not a product regression, and irrelevant to timing since it's
# the actual elapsed times of the 440 COMPLETED tests being bin-packed
# here, not a full-suite pass/fail result). The 21 tests with no recorded
# time aren't hand-added to any list below -- by construction (see
# http_shard_6_tests) they fall into the dynamic catch-all exactly like
# any newly-added test would, so their absence from this measurement can't
# silently drop them from CI the way root-4's catch-all already guards
# against for packages.
#
# Bin-packed with greedy LPT (longest-processing-time-first: sort
# descending, always add the next test to the currently-lightest bin) into
# 6 bins; the 5 heaviest-total bins became http_shard_1..5_tests below,
# pinned. Result: all 6 bins landed within 597.7s-598.9s of each other
# (<0.2% spread) on the SAME measurement basis where the old mod-6 split
# spread 765s-1180s (~54%) -- the imbalance was sharding artifact, not an
# inherent property of the workload.
http_shard_1_tests() {
  cat <<'EOF'
TestAccessRequestProxy_UpdateApprove_RejectsNonAdminApprover
TestAlertEscalation_Create_EmptyName_400
TestAlertEscalation_ListUnauthenticated_401
TestBulkApproveAccessRequests_WithIDs_Handler
TestBulkDeleteSecrets_NonExistentID
TestBulkDeleteSecrets_VerifyDeleted
TestBulkRotate_BySecretIDs
TestBulkRotate_Unauthenticated
TestByRefRead_CrossProjectDenied
TestCloneEnvironment_EmptySource
TestCloneEnvironment_SkipsExisting
TestCloneEnvironment_Unauthenticated
TestCookieAuth_LoginSetsCookiesAndDualModeWorks
TestDeleteProjectProxy_SystemWriteOnly_CannotDeleteProject
TestG80Exploit_CreateSetupTokenProxy_SystemWriteOnly_AccountTakeover
TestG80Phase0_StorageInterface_AllowedFieldRoundTrips
TestG80Sweep12_RevokeBreakGlassActivationProxy_RoleActuallyRemoved
TestGetCredentialTrends_Unauthenticated
TestGetGroupRolesRequiresRolesRead
TestGetPermissionMatrix_JSON
TestGetProjectHealth_NotFound
TestGetProjectStats_Unauthenticated
TestGetProjectStats_WithSecrets
TestHTTPServerIntegration
TestHTTPServerPerformance
TestInactivitySuspend_Unauthenticated
TestLogin_RemoteStorage_ProxiesMFACredentialCheck
TestMachineAuditReport_CSV_200
TestMachineAuditReport_ContainsCreatedMachine
TestMachineAuditReport_Unauthenticated_401
TestMachinePrivilegeCeiling_FullChain_SystemWriteToGlobalAdmin_NowBlocked
TestNoProxyCallsUnsafeSiblingWhenSafeExists
TestNoStore_GlobalDefaultCoversNonGroupedRoutes
TestNodeCredentialRoutes_PerActorCeilingsAreEnforced
TestNotificationChannelCreate_InvalidType
TestNotificationChannelCreate_StorageError
TestNotificationChannelCreate_WebhookMissingURL
TestNotificationChannelDelete_NotFound
TestPATCIDRAllowlist_DefaultConfig_RejectsSpoofedForwardedFor
TestPermissionBaseline_SecondUser
TestPermissionBaseline_Unauthenticated
TestQuotaReportRouteRequiresAuditRead
TestRejectionReasonTemplates_CreateBadJSON
TestRejectionReasonTemplates_CreateStorageError
TestRemoteStorageAccessActivity_RealServer
TestRemoteStorageAccessRequest_CreateGetList_RealServer
TestRemoteStorageAccessRequest_GetUnknown_RealServer
TestRemoteStorageAccessRequest_UpdateConditional_RealServer
TestRemoteStorageEnvironment_GetNotFound_RealServer
TestRemoteStorageGroup_CreateGetUpdateDeleteRestore_RealServer
TestRemoteStorageProject_DeleteIfEmpty_EmptyProjectSucceeds_RealServer
TestRemoteStorageRBACPermissionCatalog_GetPermission_UnknownID_RealServer
TestRemoteStorageSchedulerLock_AcquireRunRelease_RealServer
TestRemoteStorageSetupToken_CompleteSetupEndToEnd_RealServer
TestRemoteStorageSetupToken_CountSince_RealServer
TestRemoteStorageSoDPolicy_Delete_RealServer
TestRemoteStorageSoDPolicy_GetNotFound_RealServer
TestRemoteStorageWebAuthn_GetCredentialNotFound_RealServer
TestRemoteStorageWebAuthn_StaleCounterAdvanceRejectedAfterWinner_RealServer
TestRemoteStorage_GetRoleByName_RealServerRoundTrip
TestRemoteStorage_GetSecretByName_RealServerRoundTrip
TestRemoteStorage_UpdateRiskException_Unsupported
TestRotationByBackend_AuthenticatedEmpty
TestRotationDryRun_ChecksReturned
TestSecretSchedule_SetAndGet
TestSecretTemplateCreate_BadJSON_Returns400
TestSecretTemplateUpdate_BadJSON
TestSecretTemplateUpdate_InvalidID
TestSecretTemplateUpdate_StorageError
TestSecretVersionComments_Unauthenticated
TestSystemWriteCeiling_CreateOIDCBindingProxy_NodeCredential_StillBypassesAdminAuthority
TestSystemWriteCeiling_CreateSetupTokenProxy_DeniesWithoutUsersWrite
TestSystemWriteCeiling_DeleteOIDCBindingProxy_VerifiesOwnership
TestSystemWriteCeiling_DeleteSessionsForUserExceptProxy_RequiresUsersWriteAuthority
TestWebAuthnLogin_RemoteStorage_ProxiesMFAChallenge
EOF
}

http_shard_2_tests() {
  cat <<'EOF'
TestAccessRequestProxy_UpdateApprove_AllowsAdminApprover
TestAlertEscalation_Create_201
TestAlertEscalation_DeleteUnauthenticated_401
TestAlertEscalation_RunJob_Unauthenticated_401
TestBulkApproveAccessRequests_BadJSON_Handler
TestBulkApproveAccessRequests_EmptyIDs_Handler
TestBulkDeleteSecrets_InvalidProjectID
TestBulkDeleteSecrets_Success
TestBulkRejectAccessRequests_WithIDs_Handler
TestBulkRotate_WrongProject
TestG80Phase0_ClassifySecret_RejectedInConnectedMode
TestG80Phase0_SetSecretAutoRotate_RejectedInConnectedMode
TestG80Sweep05And06_SSOLoginState_CreateThenConsume
TestG80Sweep09_UpdateMachineIdentityCredentialProxy_OnlyClassificationApplies
TestGetCompliancePosture_TrendNoData_FirstCall
TestGetCredentialTrends_DefaultDays
TestGetProjectHealth_WithSecrets
TestGetProjectStats_ResponseShape
TestInactivitySuspend_NoInactiveUsers
TestInvitationProxy_CreateRejectsGlobalSystemRoleWithoutAuthority
TestListAnomalyAlertsRequiresSystemRead
TestLoginRateLimit_DefaultConfig_IgnoresSpoofedForwardedFor
TestMachinePrivilegeCeiling_CreateMachineIdentityProxy_RequiresRolesAssign
TestNoStore_CoversAuthAndTokenEndpoints
TestNoUnjustifiedRawStorageBypass
TestNotFound_NonHTMLAcceptReturnsJSON404
TestNotificationChannelGet_Found
TestNotificationChannelGet_NotFound
TestNotificationChannelGet_StorageError
TestNotificationChannelList_StorageError
TestOwnershipHistory_OneTransfer
TestOwnershipHistory_Unauthenticated
TestPATExpiryRoute_BulkRevokeExpiredPATs_NoneExpired_Returns204
TestPATExpiryRoute_ListExpiredPATs_Unauthenticated_Returns401
TestRemoteStorageConnectGrants_ListByConnector_RealServer
TestRemoteStorageCreateNotification_RealServer
TestRemoteStorageGroup_Membership_RealServer
TestRemoteStorageListSharesByOwner_RealServer
TestRemoteStorageMFAManagement_StoragePrimitives_RealServer
TestRemoteStorageMachineIdentities_OIDCBindingCreateGetListDelete_RealServer
TestRemoteStorageMembership_DuplicateActiveMembership_RealServer
TestRemoteStorageMembership_ListStaleInvited_RealServer
TestRemoteStorageRBACPermissionCatalog_GetRolePermissions_RealServer
TestRemoteStorageRBACRoleGrants_ReadsAndWrites_RealServer
TestRemoteStorageRBACRoleGrants_RemoveGlobalAdminRoleGuarded_SucceedsWithSurvivingAdmin_RealServer
TestRemoteStorageSchedulerLock_ConcurrentRaceIsSerialized_RealServer
TestRemoteStorageSchedulerLock_ContendedLockIsSkipped_RealServer
TestRemoteStorageSecretDependencies_ConcurrentRace_NoCycleAcrossTwoDownstreams
TestRemoteStorageSecretDependencies_Exclusive_DuplicateAndCycleRejected
TestRemoteStorage_PlaintextChannel_CreateSecret_RealServerRoundTrip
TestRemoteStorage_PlaintextChannel_CreateUser_RealServerRoundTrip
TestRestoreGroupRouteRequiresRolesAssign
TestRestoreProjectAndEnvironmentRoutesRequireRolesAssign
TestRoleExpiryCheck_RoleExpiringIn3Days
TestRotationByBackend_ResponseEnvelopeShape
TestRotationDryRun_NoPolicy
TestScopedRBACEnforcement
TestSecretSchedule_Delete
TestSecretTemplateApply_BadJSON
TestSecretTemplateApply_CallerOverridesPreserved
TestSecretTemplateCreate_Success
TestSecretTemplateDelete_InvalidID
TestSecretTemplateGet_StorageError
TestSecretTemplateList_Empty
TestSecretVersionComments_DeleteComment
TestServiceAccountRoutesRemoved
TestSystemInfoMetrics_PermissionTiers
TestSystemWriteCeiling_AssignRoleWithExpiryProxy_NodeCredential_DeniedAtGate
TestSystemWriteCeiling_RemoveGlobalAdminRoleGuardedProxy_NodeCredential_StillBypassesAuthorityCheck
TestSystemWriteCeiling_RevokeAllPersonalAccessTokensForUserProxy_NodeCredential_StillBypassesUsersWriteCheck
TestSystemWriteCeiling_RevokeMachineIdentityCredentialProxy_NodeCredential_DeniedAtGate
TestTokenExpiryCheck_CriticalPAT
EOF
}

http_shard_3_tests() {
  cat <<'EOF'
TestAlertEscalation_Delete_204
TestAlertEscalation_RunJob_200
TestAuthzParity_HTTPvsGRPC_ShareCreate
TestBulkDeleteSecrets_BadJSON
TestBulkRejectAccessRequests_BadJSON_Handler
TestDashboardStats_PermissionTiers
TestG80Sweep02_DeleteProjectIfEmptyProxy_AtomicGuard
TestG80Sweep03_CreateAccessReviewCampaignProxy_LifecycleFieldsNormalised
TestGetCompliancePosture_TrendDirection_AfterTwoCalls
TestGetCredentialTrends_InvalidDaysDefaultsTo30
TestGetPermissionMatrix_CSV
TestGetProjectStats_EmptyProject
TestImpersonation_BreakGlassBlocked
TestInactivitySuspend_InvalidBody_MissingInactiveDays
TestLogin_RemoteStorage_ProxiesPasswordCredentialCheck
TestMachineAuditReport_NeverUsedIsStale
TestMembershipProxy_CreateRejectsAdminRoleWithoutAuthority
TestNotificationChannelCreate_BadJSON
TestNotificationChannelCreate_EnabledDefaultsTrue
TestNotificationChannelCreate_Teams
TestNotificationChannelDelete
TestNotificationChannelList_Empty
TestOwnershipHistory_MultipleTransfers
TestOwnershipHistory_NonExistentSecret
TestPATCIDRAllowlist_TrustedProxy_HonorsForwardedFor
TestRecordHygieneSnapshot_ReturnsPoint
TestRejectionReasonTemplates_CreateEmptyName
TestRejectionReasonTemplates_CreateList
TestRejectionReasonTemplates_DeleteInvalidID
TestRejectionReasonTemplates_DeleteStorageError
TestRemoteStorageAccessRequest_ConcurrentUpdateRace_RealServer
TestRemoteStorageAccessReviewCampaign_CreateGetList_RealServer
TestRemoteStorageAccessReviewCampaign_GetNotFound_RealServer
TestRemoteStorageAccessReviewCampaign_ItemsRoundTrip_RealServer
TestRemoteStorageBreakGlass_GetList_RealServer
TestRemoteStorageDynamicSecrets_LeaseGetListCount_RealServer
TestRemoteStorageGetSecretIncludingDeleted_RealServer
TestRemoteStorageGroup_GetNotFound_RealServer
TestRemoteStorageLegalHold_CreateGetUpdate_RealServer
TestRemoteStorageMachineIdentities_CreateGetListUpdate_RealServer
TestRemoteStorageMachineIdentities_CredentialCreateGetHashListRevokeTouch_RealServer
TestRemoteStorageMembership_CreateGetList_RealServer
TestRemoteStorageMembership_GetNotFound_RealServer
TestRemoteStorageRBACPermissionCatalog_GetRolePermissions_UnknownRole_RealServer
TestRemoteStorageRBACRoleGrants_RemoveGlobalAdminRoleGuarded_RealServer
TestRemoteStorageRiskExceptions_GetNotFound_RealServer
TestRemoteStorageSSOState_CreateConsume_RealServer
TestRemoteStorageSetupToken_ConcurrentConsumeRace_RealServer
TestRemoteStorageSoDPolicy_CreateGetList_RealServer
TestRemoteStorageSoDPolicy_CreateValidation_RealServer
TestRemoteStorageWebAuthn_SessionCreateConsume_RealServer
TestRemoteStorage_FieldMismatchFix_CreateSecret_WireShapeAndValidation
TestRemoteStorage_FieldMismatchFix_UpdateUser_RealServerRoundTrip
TestRoleExpiryCheck_Idempotent
TestRotationByBackend_Unauthenticated
TestSecretSchedule_InvalidHours
TestSecretSchedule_Unauthenticated
TestSecretTemplateDelete_StorageError
TestSecretTemplateDelete_Success
TestSecretTemplateUpdate_InvalidClassification
TestSystemWriteCeiling_CreateMachineIdentityProxy_NodeCredential_AlsoForcesActiveState
TestSystemWriteCeiling_CreateOIDCBindingProxy_RequiresInstallWideAdminAuthority
TestSystemWriteCeiling_DeleteSessionsForUserExceptProxy_NodeCredential_StillBypassesUsersWriteCheck
TestSystemWriteCeiling_RemoveGlobalAdminRoleGuardedProxy_AllowsWithRolesAssign
TestSystemWriteCeiling_RemoveGlobalAdminRoleGuardedProxy_DeniesWithoutRolesAssign
TestSystemWriteCeiling_RevokeAllPersonalAccessTokensForUserProxy_RequiresUsersWriteAuthority
TestSystemWriteOnlyCeiling_RealServer
TestTokenExpiryCheck_Unauthenticated
EOF
}

http_shard_4_tests() {
  cat <<'EOF'
TestAccessRequestProxy_CreateRejectsNonPendingState
TestAlertEscalation_Create_Unauthenticated_401
TestAlertEscalation_UpdateUnauthenticated_401
TestAssetDirListing_Returns404NotListing
TestBulkApproveAccessRequests_Unauthenticated
TestBulkDeleteSecrets_Unauthenticated
TestBulkRejectAccessRequests_EmptyIDs_Handler
TestBulkRotate_ByProject
TestBulkRotate_EmptyIDs
TestComplianceDigestSendRouteRequiresAuditRead
TestDiffSecretVersions_InvalidVersion
TestDiffSecretVersions_ResponseShape
TestDiffSecretVersions_Unauthenticated
TestEmbeddedWebUI
TestEveryMutatingRouteDeniesReadOnly
TestG80Sweep07_ConsumeWebAuthnSessionProxy_SingleUseAndExpiry
TestG80Sweep10_DeleteProjectProxy_SystemWriteOnlyCannotDelete
TestG80Sweep11_RemoveGlobalAdminRoleGuardedProxy_AuthorityAndLastAdmin
TestG80_1530_MachineActorAttribution_NonNodeServiceIdentity
TestGetProjectHealth_EmptyProject
TestGetProjectHealth_LimitParam
TestGetProjectHealth_Unauthenticated
TestGetSecretValueByRef
TestImpersonationRoundTrip_CookieSwapAndRestore
TestInactivitySuspend_InvalidBody_NegativeDays
TestInactivitySuspend_RecentUserNotSuspended
TestInvitationProxy_CreateRejectsProjectAdminRoleWithoutAuthority
TestLoginRateLimit_TrustedProxy_HonorsForwardedFor
TestLogin_RemoteStorage_SessionUsableEndToEnd
TestMetricsEndpoint
TestNoStore_StaticAssetExceptionPreserved
TestNotificationChannelUpdate_BadJSON
TestNotificationChannelUpdate_NotFound
TestOpenAPISpec_GatedBySwaggerEnabled
TestOwnershipHistory_NoTransfers
TestPermissionBaseline_CSV
TestPrivescRoutesRequireWrite
TestRejectionReasonTemplates_Delete
TestRemoteStorageAccessRequest_Approvals_RealServer
TestRemoteStorageBreakGlass_RevokeThenRevokeAgainFails_RealServer
TestRemoteStorageCreateNotification_ClosesTheFailsOpenLoop
TestRemoteStorageCreateUserWithRoleGrants_RealServer
TestRemoteStorageDynamicSecrets_AdminDSNRoundTripsViaGet_RealServer
TestRemoteStorageDynamicSecrets_ListExpiredActiveLeases_RealServer
TestRemoteStorageEnvironment_DeleteBlockedByActiveSecret_RealServer
TestRemoteStorageEnvironment_DeleteRestore_RealServer
TestRemoteStorageInvitation_CreateGetList_RealServer
TestRemoteStorageInvitation_GetNotFound_RealServer
TestRemoteStorageInvitation_UpdateAlreadyResolved_RealServer
TestRemoteStorageLegalHold_AlreadyActive_RealServer
TestRemoteStorageListUsersInStateBefore_RealServer
TestRemoteStorageMachineIdentities_TransitionState_ConcurrentRaceIsSerialized_RealServer
TestRemoteStorageProject_DeleteIfEmpty_And_Force_RealServer
TestRemoteStorageRBACPermissionCatalog_GetPermission_RealServer
TestRemoteStorageRiskExceptions_Approve_DeniesNodeCredential
TestRemoteStorageSSOState_ConcurrentConsumeRace_RealServer
TestRemoteStorageSSOState_ConsumeUnknown_RealServer
TestRemoteStorageSetupToken_Expire_RealServer
TestRemoteStorageSetupToken_SupersedeProjectScoped_RealServer
TestRemoteStorage_DeleteUserAndDeleteSecret_204NoContent_RealServerRoundTrip
TestRemoteStorage_FieldMismatchFix_CreateUser_WireShapeAndValidation
TestRemoteStorage_GetUserByEmail_RealServerRoundTrip
TestRoleExpiryCheck_Unauthenticated
TestRotationDryRun_InvalidID
TestRotationDryRun_LimitedToken
TestSecretTemplateApply_EmptyRequest_GetsDefaults
TestSecretTemplateCreate_InvalidClassification_Returns400
TestSecretTemplateList_StorageError
TestSecretTemplateUpdate_Success
TestSharingHTTPIntegration
TestStaticAssets_RejectMutatingMethods
TestSystemWriteCeiling_AssignMachineRoleProxy_DeniesAdminTierGrant
TestSystemWriteCeiling_CreateMachineIdentityCredentialProxy_NodeCredential_StillBypassesPrivilegeCeiling
TestSystemWriteCeiling_CreateSetupTokenProxy_NodeCredential_StillBypassesAuthorityCheck
TestSystemWriteCeiling_UpdateMachineIdentityCredentialProxy_CannotResurrectRevoked
TestTokenExpiryCheck_ScopedPAT_Forbidden
TestUpdateUserRolesRequiresRolesAssign
TestVerifyCredentials_WrongPasswordNeverMintsSession
EOF
}

http_shard_5_tests() {
  cat <<'EOF'
TestAlertEscalation_GetByID_NotFound_404
TestAlertEscalation_List_200
TestAlertEscalation_Update_200
TestAuthzParity_HTTPvsGRPC_ShareList
TestBulkApproveAccessRequests_StorageError
TestBulkRejectAccessRequests_EmptyReason_Handler
TestBulkRejectAccessRequests_StorageError
TestCSRF_RequiredForCookieAuthenticatedMutations
TestCloneEnvironment_WithSecrets
TestDeleteProjectProxy_SystemWriteAndScopedSecretsDelete_Succeeds
TestDiffSecretVersions_SameVersion
TestG80Sweep04_CreateAccessReviewItemsProxy_DecisionStateStripped
TestG80Sweep13_RecordLoginAttemptProxy_ValidatesIPAndFutureTimestamp
TestG80Sweep14_CreateSetupTokenProxy_RequiresUsersWrite
TestGetCredentialTrends_Days90
TestGetPermissionMatrix_ProjectFilter
TestGetProjectStats_NotFound
TestInactivitySuspend_InsufficientPermissions
TestMachineAuditReport_JSON_200
TestMachinePrivilegeCeiling_CreateMachineIdentityCredentialProxy_RolesAssignHolder_Succeeds
TestNotificationChannelList_WithChannels
TestNotificationChannelUpdate_StorageError
TestNotificationChannels_Unauthenticated
TestPATExpiryRoute_ListExpiredPATs_EmptyList_Returns200
TestRefreshToken_EvictsOldTokenFromAuthCache
TestRejectionReasonTemplates_DeleteNotFound
TestRejectionReasonTemplates_ListStorageError
TestRemoteStorageAccessReviewCampaign_OpenAndLatestClosed_RealServer
TestRemoteStorageBreakGlass_ConcurrentRevokeRace_RealServer
TestRemoteStorageBreakGlass_GetNotFound_RealServer
TestRemoteStorageBreakGlass_RevokeActuallyRemovesTheRoleGrant
TestRemoteStorageCreateUserWithRoleGrants_ConcurrentDuplicateEmailRace_RealServer
TestRemoteStorageCreateUserWithRoleGrants_DuplicateEmail_RealServer
TestRemoteStorageEnvironment_ListGet_RealServer
TestRemoteStorageGroup_ListAndListPage_RealServer
TestRemoteStorageLegalHold_ConcurrentCreate_OnlyOneWins_RealServer
TestRemoteStorageMachineIdentities_GetNotFound_RealServer
TestRemoteStorageMachineIdentities_RoleGrantAssignRemoveListIDs_RealServer
TestRemoteStorageMachineIdentities_TransitionState_RealServer
TestRemoteStorageMembership_ListByUserAndCounts_RealServer
TestRemoteStorageProject_DeleteIfEmpty_ConcurrentRaceIsSerialized_RealServer
TestRemoteStorageProject_GetNotFound_RealServer
TestRemoteStorageSSOState_DifferentProvidersIsolated_RealServer
TestRemoteStorageSecretDependencies_GetNotFound_RealServer
TestRemoteStorageSetupToken_Supersede_RealServer
TestRemoteStorageWebAuthn_CredentialCRUD_RealServer
TestRemoteStorage_GetUserByUsername_RealServerRoundTrip
TestRemoteStorage_LoginLockoutWireFix_RealServerRoundTrip
TestRoleExpiryCheck_NoExpiringRoles
TestRoleExpiryCheck_RoleExpiringIn12Hours
TestRotationByBackend_WithPolicy
TestRotationDryRun_SecretNotFound
TestSecretTemplateApply_NotFound
TestSecretTemplateApply_StorageError
TestSecretTemplateCreate_EmptyName_Returns400
TestSecretTemplateCreate_StorageError
TestSecretTemplateDelete_NotFound
TestSecretTemplateGet_Found
TestSecretTemplateGet_NotFound
TestSecretTemplateUpdate_NotFound
TestSecretVersionComments_ListComments
TestSystemWriteCeiling_CreateMachineIdentityProxy_ForcesActiveState
TestSystemWriteCeiling_CreateSetupTokenProxy_AllowsWithUsersWrite
TestSystemWriteCeiling_CreateSetupTokenProxy_CreatedByIsAlwaysCaller
TestSystemWriteCeiling_RevokeAllPersonalAccessTokensForUserProxy_UsersWriteSucceeds
TestSystemWriteCeiling_TransitionMachineIdentityStateProxy_RejectsIllegalTransition
TestTokenExpiryCheck_ExpiringPAT
TestTokenExpiryCheck_NoExpiringTokens
EOF
}

# http_shard_6_tests: NOT a pinned list -- the dynamic catch-all, exactly
# root_4_pkgs's role one level down (test-name granularity instead of
# package granularity). Every test currently in server/http that ISN'T in
# shard 1-5's pinned lists above, computed via `go test -list` at CI-run
# time -- so a newly added test, or one of the 21 tests the 2026-08-29
# measurement run didn't reach (see above), always lands here automatically
# rather than needing a 6th list kept in sync by hand. This is the exact
# property that makes pinning by name safe here: nothing can silently drop
# out of CI the way server/http itself did for ~4 months pre-G80-C4 --
# every test not explicitly claimed by a pinned shard is still covered,
# just not load-balanced as precisely.
http_shard_6_tests() {
  local pinned all
  pinned=$(cat <(http_shard_1_tests) <(http_shard_2_tests) <(http_shard_3_tests) <(http_shard_4_tests) <(http_shard_5_tests) | sort -u)
  all=$(go test -list '^Test' "$(http_pkg)" | grep -v '^ok\b' | sort -u)
  comm -23 <(echo "$all") <(echo "$pinned")
}

# run_filter_for_http_shard: builds the `go test -run` regex for a given
# http-N leg from http_shard_N_tests() above -- same regex-join mechanism
# run_filter_for_shard below uses, just fed a name list computed by measured
# time instead of a mod-N split.
run_filter_for_http_shard() {
  local shard="$1" names
  case "$shard" in
    1) names=$(http_shard_1_tests) ;;
    2) names=$(http_shard_2_tests) ;;
    3) names=$(http_shard_3_tests) ;;
    4) names=$(http_shard_4_tests) ;;
    5) names=$(http_shard_5_tests) ;;
    6) names=$(http_shard_6_tests) ;;
    *) echo "run_filter_for_http_shard: unknown shard '$shard'" >&2; return 1 ;;
  esac
  printf '^(%s)$' "$(echo "$names" | sort -u | paste -sd '|')"
}

# pkgs_for_leg: package list for a given leg name, space/newline-separated.
# Matches the case statement the test-suite matrix step uses to pick $pkgs.
pkgs_for_leg() {
  case "$1" in
    root-1) root_1_pkgs ;;
    root-2) root_2_pkgs ;;
    root-3) root_3_pkgs ;;
    core) core_pkgs ;;
    root-4) root_4_pkgs ;;
    storage-store) storage_store_pkgs ;;
    handlers-1|handlers-2|handlers-3|handlers-4) handlers_pkg ;;
    http-1|http-2|http-3|http-4|http-5|http-6) http_pkg ;;
    *) echo "pkgs_for_leg: unknown leg '$1'" >&2; return 1 ;;
  esac
}

# all_leg_names: every matrix leg, in the same order ci.yml's matrix.include
# declares them. Kept here too so the completeness check enumerates exactly
# the legs that exist, not a hand-copied list that can drift from the matrix.
all_leg_names() {
  cat <<'EOF'
root-1
root-2
root-3
root-4
core
storage-store
handlers-1
handlers-2
handlers-3
handlers-4
http-1
http-2
http-3
http-4
http-5
http-6
EOF
}

# run_filter_for_shard: builds a `go test -run` regex selecting roughly 1/N
# of a single package's top-level tests, by (sorted test name index) mod N --
# the mechanism handlers-1..4 already uses. Shared here so any future
# by-test-name-sharded leg (not just handlers) reuses the identical, already-
# proven splitting logic instead of a second hand-copied implementation.
run_filter_for_shard() {
  local pkg="$1" shard="$2" n="$3"
  local names selected
  names=$(go test -list '^Test' "$pkg" | grep -v '^ok\b' | sort)
  selected=$(echo "$names" | awk -v n="$n" -v s="$shard" 'NR % n == (s - 1)')
  printf '^(%s)$' "$(echo "$selected" | paste -sd '|')"
}

# check_exclusion_freshness: fails (nonzero exit, one line per offender on
# stdout) if any TEMPORARY exclusion_entries row is more than 30 days old.
# PERMANENT/SHARDED rows are exempt -- there is no fix to land for either, so
# "how long has this sat here" is not a meaningful signal for them. This is
# deliberately a hard failure, not a warning: a warning is exactly what the
# pre-C5 bare `grep -v` list amounted to in practice (a comment nobody
# re-reads), which is how server/http sat excluded with no leg for ~4 months
# unnoticed.
check_exclusion_freshness() {
  local today_epoch failed=0
  today_epoch=$(date -u -d "$(date -u +%Y-%m-%d)" +%s)
  while IFS='|' read -r pattern kind reason issue added; do
    [ "$kind" = "TEMPORARY" ] || continue
    local added_epoch age_days
    added_epoch=$(date -u -d "$added" +%s)
    age_days=$(( (today_epoch - added_epoch) / 86400 ))
    if [ "$age_days" -gt 30 ]; then
      echo "STALE EXCLUSION (${age_days}d > 30d budget): $pattern -- $reason ($issue, added $added)"
      failed=1
    fi
  done < <(exclusion_entries)
  return $failed
}

# assert_leg_completeness: fails (nonzero exit, listing every offending
# package on stdout) if any package in `go list ./...` is covered by NEITHER
# the exclusion table (never_run_patterns -- TEMPORARY/PERMANENT only; a
# SHARDED package must still be covered by its own leg to pass) NOR any CI
# test-suite leg's package list. This is the guard against a package
# silently landing in zero legs, the exact failure mode that let
# server/http go untested for ~4 months with nothing red anywhere.
assert_leg_completeness() {
  local never_args=()
  while IFS= read -r p; do never_args+=(-e "$p"); done < <(never_run_patterns)
  local target actual missing
  target=$(go list ./... | grep -v "${never_args[@]}" | sort -u)
  actual=$(
    while IFS= read -r leg; do
      pkgs_for_leg "$leg"
    done < <(all_leg_names) | sort -u
  )
  missing=$(comm -23 <(echo "$target") <(echo "$actual"))
  if [ -n "$missing" ]; then
    echo "The following package(s) are covered by NO CI test-suite leg and are not in the exclusion table (scripts/ci-test-legs.sh):"
    echo "$missing"
    return 1
  fi
  echo "OK: every non-excluded package is covered by at least one CI test-suite leg."
  return 0
}
