// Command statemapgen regenerates docs/state-map/*.tsv from source. Never
// imported by the server binary -- a standalone generator, run manually
// (`go run ./cmd/statemapgen`) and verified by
// internal/statemap/completeness_test.go, which re-extracts the same data
// on every `go test ./...` and fails if the checked-in TSVs have drifted
// from the code (a new route/RPC/job/command, or DB table, added without
// regenerating).
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/keyorixhq/keyorix/internal/statemap"
)

func main() {
	repoRoot, err := os.Getwd()
	if err != nil {
		fatal(err)
	}
	// Allow running from anywhere inside the repo by walking up to go.mod.
	for {
		if _, err := os.Stat(filepath.Join(repoRoot, "go.mod")); err == nil {
			break
		}
		parent := filepath.Dir(repoRoot)
		if parent == repoRoot {
			fatal(fmt.Errorf("could not find repo root (go.mod) from %s", repoRoot))
		}
		repoRoot = parent
	}

	outDir := filepath.Join(repoRoot, "docs", "state-map")
	if err := os.MkdirAll(outDir, 0750); err != nil {
		fatal(err)
	}

	entries, err := statemap.AllEntries(repoRoot)
	if err != nil {
		fatal(err)
	}
	writeEntrypoints(filepath.Join(outDir, "entrypoints.tsv"), entries)

	tables, err := statemap.DBTables(repoRoot)
	if err != nil {
		fatal(err)
	}
	sites, err := statemap.FileWriteSites(repoRoot)
	if err != nil {
		fatal(err)
	}
	writeStores(filepath.Join(outDir, "stores.tsv"), tables, sites)

	fmt.Printf("wrote %d entry points, %d DB tables, %d file-write sites to %s\n", len(entries), len(tables), len(sites), outDir)
}

func writeEntrypoints(path string, entries []statemap.Entry) {
	var b strings.Builder
	b.WriteString("# Generated by cmd/statemapgen -- DO NOT HAND-EDIT. Re-run `go run ./cmd/statemapgen` after\n")
	b.WriteString("# adding/removing a route, RPC, scheduled job, or CLI command; internal/statemap/\n")
	b.WriteString("# completeness_test.go fails CI if this drifts from what the extractors find in code.\n")
	b.WriteString("# See internal/statemap/statemap.go's package doc for each extractor's named blind spots.\n")
	b.WriteString("#\n# kind\tid\tfile\tline\n")
	for _, e := range entries {
		fmt.Fprintf(&b, "%s\t%s\t%s\t%d\n", e.Kind, e.ID, e.File, e.Line)
	}
	must(os.WriteFile(path, []byte(b.String()), 0600)) // #nosec G306 -- generated docs artifact, not sensitive
}

func writeStores(path string, tables []statemap.DBTable, sites []statemap.FileWriteSite) {
	var b strings.Builder
	b.WriteString("# Generated by cmd/statemapgen -- DO NOT HAND-EDIT for the db_table/file_write rows below\n")
	b.WriteString("# (db_table rows are internal/storage/all_models.go's AllModels(), already drift-guarded by\n")
	b.WriteString("# TestAllModels_MatchesLiveMigratedTables; file_write rows are every os.WriteFile/os.Create/\n")
	b.WriteString("# securefiles.Secure* call site outside _test.go files). The memory/external rows below the\n")
	b.WriteString("# marker are hand-curated (AT0(a) requires them; there is no single registration point in\n")
	b.WriteString("# code to extract them from) -- see SESSION-AT's report for how each was identified.\n")
	b.WriteString("#\n# store\tkind\towner\n")
	for _, t := range tables {
		fmt.Fprintf(&b, "%s\tdb_table\tinternal/storage/models\n", t.Model)
	}
	for _, s := range sites {
		fmt.Fprintf(&b, "%s:%d (%s)\tfile_write\t%s\n", s.File, s.Line, s.Func, filepath.Dir(s.File))
	}
	b.WriteString("#\n# --- hand-curated: in-memory state that must agree with the DB, and external systems ---\n")
	for _, row := range curatedStores {
		fmt.Fprintf(&b, "%s\t%s\t%s\n", row[0], row[1], row[2])
	}
	must(os.WriteFile(path, []byte(b.String()), 0600)) // #nosec G306 -- generated docs artifact, not sensitive
}

// curatedStores is AT0(a)'s in-memory and external state, hand-identified
// (no single code registration point to extract this from mechanically).
// Each entry was confirmed by reading its owning package during this
// session, not guessed.
var curatedStores = [][3]string{
	{"session/permission token cache", "memory", "server/middleware (authcache)"},
	{"named locks (storage.WithNamedLock)", "memory+db", "internal/storage/store (Postgres advisory lock / SQLite mutex)"},
	{"scheduler lock lease", "db+memory", "internal/storage/models.SchedulerLockLease + server/main.go runScheduler"},
	{"config in-memory snapshot (hot reload)", "memory", "internal/config"},
	{"DEK/KEK in-process key material", "memory", "internal/encryption (KeyManager)"},
	{"dynamic-secret upstream credentials (DB users, cloud IAM)", "external", "internal/dynamic, internal/connect"},
	{"k8s secret sync target", "external", "internal/k8ssync"},
	{"SIEM / evidence sink delivery target", "external", "internal/evidencesink, internal/audit/siem"},
	{"notification channel delivery target (SMTP/ntfy/webhook)", "external", "internal/core (notification dispatch)"},
	{"audit hash-chain head (in-memory tip cache, if any)", "memory+db", "internal/audit, internal/core/audit*.go"},
	{"key files on disk (DEK, salt, checkpoint keys)", "file", "internal/encryption, internal/keyfiles"},
	{"config file, backup files, evidence exports", "file", "internal/config, internal/backupfmt, internal/core/evidence_export.go"},
}

func must(err error) {
	if err != nil {
		fatal(err)
	}
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "statemapgen:", err)
	os.Exit(1)
}
