// Command statemapgen regenerates docs/state-map/*.tsv from source. Never
// imported by the server binary -- a standalone generator, run manually
// (`go run ./cmd/statemapgen`) and verified by
// internal/statemap/completeness_test.go, which re-extracts the same data
// on every `go test ./...` and fails if the checked-in TSVs have drifted
// from the code (a new route/RPC/job/command, or DB table, added without
// regenerating), OR if any entrypoints.tsv row is missing a class, OR if a
// known-gap row was deleted, OR if the REVIEW-class count grew.
//
// Reads docs/state-map/class-overrides.tsv (kind\tid\tclass\treason) and
// applies every match ON TOP of Classify's freshly computed classes before
// writing -- a human triage decision survives regeneration; see
// internal/statemap/overrides.go's package doc for why this exists (the
// FIRST version of this generator recomputed and overwrote human
// classifications on every run, defeating the point of triaging a REVIEW
// row at all -- a coordinator review caught this).
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/keyorixhq/keyorix/internal/statemap"
)

func main() {
	repoRoot, err := findRepoRoot()
	if err != nil {
		fatal(err)
	}

	outDir := filepath.Join(repoRoot, "docs", "state-map")
	if err := os.MkdirAll(outDir, 0750); err != nil {
		fatal(err)
	}

	entries, err := statemap.AllEntries(repoRoot)
	if err != nil {
		fatal(err)
	}
	classified, err := statemap.Classify(repoRoot, entries)
	if err != nil {
		fatal(err)
	}
	overrides, err := statemap.LoadOverrides(filepath.Join(outDir, "class-overrides.tsv"))
	if err != nil {
		fatal(err)
	}
	classified = statemap.ApplyOverrides(classified, overrides)
	classified = append(classified, statemap.KnownGapRows()...)
	writeEntrypoints(filepath.Join(outDir, "entrypoints.tsv"), classified)

	tables, err := statemap.DBTables(repoRoot)
	if err != nil {
		fatal(err)
	}
	sites, err := statemap.FileWriteSites(repoRoot)
	if err != nil {
		fatal(err)
	}
	writeStores(filepath.Join(outDir, "stores.tsv"), tables, sites)

	reviewCount := 0
	for _, e := range classified {
		if e.Class == "REVIEW" {
			reviewCount++
		}
	}
	fmt.Printf("wrote %d entry points (+%d known-gap rows, %d REVIEW, %d override(s) applied), %d DB tables, %d file-write sites to %s\n",
		len(entries), len(statemap.KnownGapRows()), reviewCount, len(overrides), len(tables), len(sites), outDir)
}

// findRepoRoot walks up from the working directory to the file that
// actually identifies KEYORIX'S OWN root: go.work. This repo is a
// multi-module workspace (operator/ and the migrate/ Vault-import tool are
// each their own module with their own go.mod) -- stopping at the first
// go.mod found while walking up would incorrectly anchor on one of those
// NESTED modules' own go.mod if statemapgen were ever run from inside
// operator/ or migrate/, silently scanning the wrong tree. go.work exists
// exactly once, at the true root, by construction.
func findRepoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	start := dir
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.work")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("could not find repo root (go.work) from %s", start)
		}
		dir = parent
	}
}

func writeEntrypoints(path string, entries []statemap.Entry) {
	var b strings.Builder
	b.WriteString("# Generated by cmd/statemapgen -- entry-point rows are REGENERATED; class/reason on a row\n")
	b.WriteString("# with a matching entry in class-overrides.tsv is preserved across regeneration, everything\n")
	b.WriteString("# else is NOT hand-editable. Re-run `go run ./cmd/statemapgen` after adding/removing a route,\n")
	b.WriteString("# RPC, scheduled job, CLI command, or MCP tool; internal/statemap/completeness_test.go fails\n")
	b.WriteString("# CI if this drifts from what the extractors find in code, if any row's class column is\n")
	b.WriteString("# empty/invalid, if a known-gap row is missing, or if the REVIEW-class ratchet ceiling is\n")
	b.WriteString("# exceeded. See internal/statemap/statemap.go's and classify.go's package docs for each\n")
	b.WriteString("# extractor/classifier's named blind spots.\n")
	b.WriteString("#\n")
	b.WriteString("# Classes: A/S/B/C/D/F/R/X/L (see docs/atomicity-exempt.tsv's own class definitions --\n")
	b.WriteString("# reused, not redefined here) | none (single/no write, or read-only by design) |\n")
	b.WriteString("# REVIEW (this generator's 1-hop write-count scan found 2+ candidate write calls, or could\n")
	b.WriteString("# not resolve the handler at all / resolved it ambiguously -- needs a human to read the\n")
	b.WriteString("# reason and either downgrade to \"none\" (false positive) or assign a real class via\n")
	b.WriteString("# class-overrides.tsv, mirroring atomicity-exempt.tsv's TEMP-A precedent for \"flagged, not\n")
	b.WriteString("# yet triaged\") | gap (an entry-point CATEGORY this generator does not enumerate at all --\n")
	b.WriteString("# see internal/statemap.KnownGapRows for why, and whether it's covered elsewhere).\n")
	b.WriteString("#\n# kind\tid\tfile\tline\thandler\tclass\treason\n")
	for _, e := range entries {
		fmt.Fprintf(&b, "%s\t%s\t%s\t%d\t%s\t%s\t%s\n", e.Kind, e.ID, e.File, e.Line, tsvSafe(e.Handler), e.Class, tsvSafe(e.Reason))
	}
	must(os.WriteFile(path, []byte(b.String()), 0644)) // #nosec G306 -- generated docs artifact, not sensitive; world-readable like any other checked-in doc
}

// tsvSafe strips tabs/newlines from a field so a free-text reason can never
// desynchronize this TSV's column count.
func tsvSafe(s string) string {
	s = strings.ReplaceAll(s, "\t", " ")
	s = strings.ReplaceAll(s, "\n", " ")
	return s
}

func writeStores(path string, tables []statemap.DBTable, sites []statemap.FileWriteSite) {
	var b strings.Builder
	b.WriteString("# Generated by cmd/statemapgen -- DO NOT HAND-EDIT for the db_table/file_write rows below\n")
	b.WriteString("# (db_table rows are internal/storage/all_models.go's AllModels(), already drift-guarded by\n")
	b.WriteString("# TestAllModels_MatchesLiveMigratedTables; file_write rows are every os.WriteFile/os.Create/\n")
	b.WriteString("# os.OpenFile/securefiles.Secure* call site outside _test.go files, keyed by file+func with\n")
	b.WriteString("# a COUNT -- not a line number, so an unrelated edit above one of these sites doesn't churn\n")
	b.WriteString("# this file or conflict with an unrelated PR. BOTH kinds are drift-checked by\n")
	b.WriteString("# internal/statemap/completeness_test.go, not just db_table. The memory/external rows below\n")
	b.WriteString("# the marker are hand-curated (AT0(a) requires them; there is no single registration point in\n")
	b.WriteString("# code to extract them from, and this generator does NOT guard their presence/absence -- see\n")
	b.WriteString("# SESSION-AT's report for how each was identified) -- treat additions/removals there as a\n")
	b.WriteString("# manual review item, not something CI enforces.\n")
	b.WriteString("#\n# store\tkind\towner\tcount\n")
	for _, t := range tables {
		fmt.Fprintf(&b, "%s\tdb_table\tinternal/storage/models\t1\n", t.Model)
	}
	fileFuncOwner := map[string]string{}
	for _, s := range sites {
		key := s.File + "\t" + s.Func
		if _, ok := fileFuncOwner[key]; !ok {
			fileFuncOwner[key] = filepath.Dir(s.File)
		}
	}
	counts := statemap.AggregateFileWriteSites(sites)
	keys := make([]string, 0, len(counts))
	for k := range counts {
		keys = append(keys, k)
	}
	sortStrings(keys)
	for _, k := range keys {
		parts := strings.SplitN(k, "\t", 2)
		fmt.Fprintf(&b, "%s (%s)\tfile_write\t%s\t%d\n", parts[0], parts[1], fileFuncOwner[k], counts[k])
	}
	b.WriteString("#\n# --- hand-curated: in-memory state that must agree with the DB, and external systems ---\n")
	for _, row := range curatedStores {
		fmt.Fprintf(&b, "%s\t%s\t%s\t1\n", row[0], row[1], row[2])
	}
	must(os.WriteFile(path, []byte(b.String()), 0644)) // #nosec G306 -- generated docs artifact, not sensitive; world-readable like any other checked-in doc
}

func sortStrings(s []string) {
	for i := 1; i < len(s); i++ {
		for j := i; j > 0 && s[j-1] > s[j]; j-- {
			s[j-1], s[j] = s[j], s[j-1]
		}
	}
}

// curatedStores is AT0(a)'s in-memory and external state, hand-identified
// (no single code registration point to extract this from mechanically).
// Each entry was confirmed by reading its owning package during this
// session, not guessed.
var curatedStores = [][3]string{
	{"session/permission token cache", "memory", "server/middleware (authcache)"},
	{"named locks (storage.WithNamedLock)", "memory+db", "internal/storage/store (Postgres advisory lock / SQLite mutex)"},
	{"scheduler lock lease", "db+memory", "internal/storage/models.SchedulerLockLease + server/main.go runScheduler"},
	{"config in-memory snapshot (hot reload)", "memory", "internal/config"},
	{"DEK/KEK in-process key material", "memory", "internal/encryption (KeyManager)"},
	{"dynamic-secret upstream credentials (DB users, cloud IAM)", "external", "internal/dynamic, internal/connect"},
	{"k8s secret sync target", "external", "internal/k8ssync"},
	{"SIEM / evidence sink delivery target", "external", "internal/evidencesink, internal/audit/siem"},
	{"notification channel delivery target (SMTP/ntfy/webhook)", "external", "internal/core (notification dispatch)"},
	{"audit hash-chain head (in-memory tip cache, if any)", "memory+db", "internal/audit, internal/core/audit*.go"},
	{"key files on disk (DEK, salt, checkpoint keys)", "file", "internal/encryption, internal/keyfiles"},
	{"config file, backup files, evidence exports", "file", "internal/config, internal/backupfmt, internal/core/evidence_export.go"},
}

func must(err error) {
	if err != nil {
		fatal(err)
	}
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "statemapgen:", err)
	os.Exit(1)
}
