// Command statemapgen regenerates docs/state-map/*.tsv from source. Never
// imported by the server binary -- a standalone generator, run manually
// (`go run ./cmd/statemapgen`) and verified by
// internal/statemap/completeness_test.go, which re-extracts the same data
// on every `go test ./...` and fails if the checked-in TSVs have drifted
// from the code (a new route/RPC/job/command, or DB table, added without
// regenerating), OR if any entrypoints.tsv row is missing a class.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/keyorixhq/keyorix/internal/statemap"
)

func main() {
	repoRoot, err := findRepoRoot()
	if err != nil {
		fatal(err)
	}

	outDir := filepath.Join(repoRoot, "docs", "state-map")
	if err := os.MkdirAll(outDir, 0750); err != nil {
		fatal(err)
	}

	entries, err := statemap.AllEntries(repoRoot)
	if err != nil {
		fatal(err)
	}
	classified, err := statemap.Classify(repoRoot, entries)
	if err != nil {
		fatal(err)
	}
	classified = append(classified, knownGapRows()...)
	writeEntrypoints(filepath.Join(outDir, "entrypoints.tsv"), classified)

	tables, err := statemap.DBTables(repoRoot)
	if err != nil {
		fatal(err)
	}
	sites, err := statemap.FileWriteSites(repoRoot)
	if err != nil {
		fatal(err)
	}
	writeStores(filepath.Join(outDir, "stores.tsv"), tables, sites)

	fmt.Printf("wrote %d entry points (+%d known-gap rows), %d DB tables, %d file-write sites to %s\n",
		len(entries), len(knownGapRows()), len(tables), len(sites), outDir)
}

// findRepoRoot walks up from the working directory to the file that
// actually identifies KEYORIX'S OWN root: go.work. This repo is a
// multi-module workspace (operator/ and the migrate/ Vault-import tool are
// each their own module with their own go.mod) -- stopping at the first
// go.mod found while walking up would incorrectly anchor on one of those
// NESTED modules' own go.mod if statemapgen were ever run from inside
// operator/ or migrate/, silently scanning the wrong tree. go.work exists
// exactly once, at the true root, by construction.
func findRepoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	start := dir
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.work")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("could not find repo root (go.work) from %s", start)
		}
		dir = parent
	}
}

func writeEntrypoints(path string, entries []statemap.Entry) {
	var b strings.Builder
	b.WriteString("# Generated by cmd/statemapgen -- DO NOT HAND-EDIT. Re-run `go run ./cmd/statemapgen` after\n")
	b.WriteString("# adding/removing a route, RPC, scheduled job, CLI command, or MCP tool; internal/statemap/\n")
	b.WriteString("# completeness_test.go fails CI if this drifts from what the extractors find in code, or if\n")
	b.WriteString("# any row's class column is empty. See internal/statemap/statemap.go's and classify.go's\n")
	b.WriteString("# package docs for each extractor/classifier's named blind spots.\n")
	b.WriteString("#\n")
	b.WriteString("# Classes: A/S/B/C/D/F/R/X/L (see docs/atomicity-exempt.tsv's own class definitions --\n")
	b.WriteString("# reused, not redefined here) | none (single/no write, or read-only by design) |\n")
	b.WriteString("# REVIEW (this generator's 1-hop write-count scan found 2+ candidate write calls, or could\n")
	b.WriteString("# not resolve the handler at all / resolved it ambiguously -- needs a human to read the\n")
	b.WriteString("# reason and either downgrade to \"none\" (false positive -- mutually exclusive branches,\n")
	b.WriteString("# generic non-domain calls like a stdlib method that happens to match the write-verb regex,\n")
	b.WriteString("# etc., the SAME false-positive shape internal/core/atomicity_guard_test.go's own scan has\n")
	b.WriteString("# and documents) or assign a real class with a reason, mirroring atomicity-exempt.tsv's\n")
	b.WriteString("# TEMP-A precedent for \"flagged, not yet triaged\") | gap (an entry-point CATEGORY this\n")
	b.WriteString("# generator does not enumerate at all -- see the reason for why, and whether it's covered\n")
	b.WriteString("# elsewhere).\n")
	b.WriteString("#\n# kind\tid\tfile\tline\thandler\tclass\treason\n")
	for _, e := range entries {
		fmt.Fprintf(&b, "%s\t%s\t%s\t%d\t%s\t%s\t%s\n", e.Kind, e.ID, e.File, e.Line, tsvSafe(e.Handler), e.Class, tsvSafe(e.Reason))
	}
	must(os.WriteFile(path, []byte(b.String()), 0644)) // #nosec G306 -- generated docs artifact, not sensitive; world-readable like any other checked-in doc
}

// tsvSafe strips tabs/newlines from a field so a free-text reason can never
// desynchronize this TSV's column count.
func tsvSafe(s string) string {
	s = strings.ReplaceAll(s, "\t", " ")
	s = strings.ReplaceAll(s, "\n", " ")
	return s
}

// knownGapRows are entry-point CATEGORIES this generator does NOT enumerate
// at all (as opposed to individual entries within an enumerated category
// that couldn't be classified, which get class "REVIEW" above). Each is a
// considered decision, not an oversight -- reasons state why, per the
// coordinator's B3 review comment on this PR ("Either enumerate them or
// list each as an explicit known-gap row").
func knownGapRows() []statemap.Entry {
	return []statemap.Entry{
		{
			Kind: "gap", ID: "operator/ reconcile loops", File: "operator/", Line: 0,
			Class: "gap", Reason: "operator/ is a separate Go module (its own go.mod, controller-runtime reconcile-loop entry points, not REST/gRPC/CLI/job in this codebase's sense) and is on SESSION-AT's MUST-NOT-EDIT list. Not enumerated here; recommend a follow-up session scoped to operator/ specifically, using its own entry-point shape (Reconcile methods on each controller).",
		},
		{
			Kind: "gap", ID: "server startup/shutdown sequence", File: "server/main.go", Line: 0,
			Class: "gap", Reason: "main()'s own linear startup (config load, storage init, migration check, startSchedulers, listener start) and shutdown (signal handling, graceful drain) is a single run-once sequence per process, not a repeatable/lookupable entry point the way a route or CLI command is -- there is no clean registration point to enumerate \"hooks\" from (unlike runScheduler's own named-call pattern, which IS enumerated under kind=job). Scheduled jobs themselves (the repeatable part of startup) ARE enumerated (kind=job, 17 rows). Recommend a manual, one-time trace of main()'s own sequence rather than a generator, if this needs auditing.",
		},
		{
			Kind: "gap", ID: "SSO/SAML/webhook callbacks", File: "server/http/router.go", Line: 0,
			Class: "gap", Reason: "NOT actually a gap -- checked explicitly per the coordinator's review: /auth/sso/{provider}/callback, /auth/saml/{provider}/acs, and similar IdP-callback routes are plain chi routes already captured by the kind=rest extractor (confirmed: `grep -n callback server/http/router.go` shows them registered exactly like any other route, inside the same unauthenticated r.Group). Listed here only so this decision is visible in the TSV itself, not just in a PR body someone has to go find.",
		},
	}
}

func writeStores(path string, tables []statemap.DBTable, sites []statemap.FileWriteSite) {
	var b strings.Builder
	b.WriteString("# Generated by cmd/statemapgen -- DO NOT HAND-EDIT for the db_table/file_write rows below\n")
	b.WriteString("# (db_table rows are internal/storage/all_models.go's AllModels(), already drift-guarded by\n")
	b.WriteString("# TestAllModels_MatchesLiveMigratedTables; file_write rows are every os.WriteFile/os.Create/\n")
	b.WriteString("# securefiles.Secure* call site outside _test.go files -- BOTH kinds are drift-checked by\n")
	b.WriteString("# internal/statemap/completeness_test.go, not just db_table). The memory/external rows below\n")
	b.WriteString("# the marker are hand-curated (AT0(a) requires them; there is no single registration point in\n")
	b.WriteString("# code to extract them from) -- see SESSION-AT's report for how each was identified.\n")
	b.WriteString("#\n# store\tkind\towner\n")
	for _, t := range tables {
		fmt.Fprintf(&b, "%s\tdb_table\tinternal/storage/models\n", t.Model)
	}
	for _, s := range sites {
		fmt.Fprintf(&b, "%s:%d (%s)\tfile_write\t%s\n", s.File, s.Line, s.Func, filepath.Dir(s.File))
	}
	b.WriteString("#\n# --- hand-curated: in-memory state that must agree with the DB, and external systems ---\n")
	for _, row := range curatedStores {
		fmt.Fprintf(&b, "%s\t%s\t%s\n", row[0], row[1], row[2])
	}
	must(os.WriteFile(path, []byte(b.String()), 0644)) // #nosec G306 -- generated docs artifact, not sensitive; world-readable like any other checked-in doc
}

// curatedStores is AT0(a)'s in-memory and external state, hand-identified
// (no single code registration point to extract this from mechanically).
// Each entry was confirmed by reading its owning package during this
// session, not guessed.
var curatedStores = [][3]string{
	{"session/permission token cache", "memory", "server/middleware (authcache)"},
	{"named locks (storage.WithNamedLock)", "memory+db", "internal/storage/store (Postgres advisory lock / SQLite mutex)"},
	{"scheduler lock lease", "db+memory", "internal/storage/models.SchedulerLockLease + server/main.go runScheduler"},
	{"config in-memory snapshot (hot reload)", "memory", "internal/config"},
	{"DEK/KEK in-process key material", "memory", "internal/encryption (KeyManager)"},
	{"dynamic-secret upstream credentials (DB users, cloud IAM)", "external", "internal/dynamic, internal/connect"},
	{"k8s secret sync target", "external", "internal/k8ssync"},
	{"SIEM / evidence sink delivery target", "external", "internal/evidencesink, internal/audit/siem"},
	{"notification channel delivery target (SMTP/ntfy/webhook)", "external", "internal/core (notification dispatch)"},
	{"audit hash-chain head (in-memory tip cache, if any)", "memory+db", "internal/audit, internal/core/audit*.go"},
	{"key files on disk (DEK, salt, checkpoint keys)", "file", "internal/encryption, internal/keyfiles"},
	{"config file, backup files, evidence exports", "file", "internal/config, internal/backupfmt, internal/core/evidence_export.go"},
}

func must(err error) {
	if err != nil {
		fatal(err)
	}
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "statemapgen:", err)
	os.Exit(1)
}
