name: Anchore Syft SBOM scan

on:
  push:
    branches: [main]
    paths-ignore: ['**/*.md', 'docs/**']

permissions: {}

jobs:
  sbom:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4

      - name: Generate SBOM
        uses: anchore/sbom-action@3ad7283483fc7af8ff2b4ea19663c2d5ca935e26 # v0.24.2.20.24.2.0.24.2
        with:
          path: .
          artifact-name: sbom.spdx.json
