name: OSV-Scanner

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  schedule:
    - cron: '19 17 * * 5'

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  scan:
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@8bd1ce1c4be9d98053ffd9e6e14585276a36762c" # v1.9.1
    with:
      scan-args: |-
        --recursive
        --skip-git
        ./
      fail-on-vuln: false
