name: OSV-Scanner

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  schedule:
    - cron: '19 17 * * 5'

permissions: {}

jobs:
  scan:
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@9fd1bcce27f67e3bd819a0a7620e332803dc43bc" # v1.9.1
    permissions:
      contents: read
      security-events: write
      actions: read
    with:
      scan-args: |-
        --recursive
        --skip-git
        ./
      fail-on-vuln: false
