name: SonarCloud analysis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  pull-requests: read

jobs:
  Analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v4
        with:
          fetch-depth: 0

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=keyorixhq_keyorix
            -Dsonar.organization=keyorixhq
          projectBaseDir: .
